src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Classified_Minor_Category__c</fullName>
        <label>Classified - Minor Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accessories &amp; Soft Furnishings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia &amp; New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balearics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blackpool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bournemouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building &amp; Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Businesses For Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire &amp; Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clerical &amp; Secretarial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conservatories, Lofts &amp; Extensions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts &amp; Tenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cornwall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotswolds</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CustomerRef1__c</fullName>
        <label>CCI Metro Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef2__c</fullName>
        <label>AdVance Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef3__c</fullName>
        <label>CCI Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef4__c</fullName>
        <label>Operative Cust Ref</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IndClassLvl1__c</fullName>
        <label>Classified - Main Category</label>
        <picklist>
            <picklistValues>
                <fullName>Business &amp; Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &amp; Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homes &amp; Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noticeboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal &amp; Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IndClassLvl2__c</fullName>
        <label>Classified - Sub Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Airlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airport Parking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apprenticeships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (General)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Motors)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Property)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;B/Guest Houses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bars/Clubs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battlefields</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Births, Deaths and Marriages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business to Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping and Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravans &amp; Motorhomes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars wanted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinemas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City Living</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Trials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collectables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complementary Therapies &amp; Wellbeing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Revenue_Last_Year__c</fullName>
        <label>Revenue Last Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Mappings</relationshipLabel>
        <relationshipName>Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Key__c</fullName>
        <label>Customer Ref</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operative One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nielsen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDM Origins</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Mapping</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/SalesRevenue__c.object
<CustomObject>
    <description>This Object has been created as part of the Quick Wins Project. It will be populated from an external system.</description>
    <fields>
        <fullName>AdvertiserID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AdvertiserID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesRevenue</relationshipLabel>
        <relationshipName>SalesRevenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrandID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BrandID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesRevenue (BrandID)</relationshipLabel>
        <relationshipName>SalesRevenue1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_AgencyID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice_AgencyID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesRevenue (Invoice_AgencyID)</relationshipLabel>
        <relationshipName>SalesRevenue2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period_End_Date__c</fullName>
        <label>Revenue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Amount__c</fullName>
        <label>Revenue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SalesRevenue</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>SalesRevenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesRevenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchAccountRevenueUpdateLastYear.cls
global with sharing class BatchAccountRevenueUpdateLastYear implements Database.Batchable < sObject > , Database.Stateful {

	global BatchAccountRevenueUpdateLastYear() {

	}

	global Database.querylocator start(Database.BatchableContext ctx) {
		return Database.getQueryLocator(
		[
		Select
		BrandID__c,
		AdvertiserID__c,
		Invoice_AgencyID__c,
		Revenue_Amount__c
		From SalesRevenue__c
		Where Period_End_Date__c = LAST_YEAR
		And(BrandID__c != Null Or AdvertiserID__c != Null Or Invoice_AgencyID__c != Null)]);
	}

	global void execute(Database.BatchableContext BC, List < sObject > scope) {
		List < SalesRevenue__c > srList = scope;
		Map < Id, Decimal > brandMap = new Map < Id, Decimal > ();
		Map < Id, Decimal > advertiserMap = new Map < Id, Decimal > ();
		Map < Id, Decimal > agencyMap = new Map < Id, Decimal > ();

		for (SalesRevenue__c s: srList) {
			if (s.BrandID__c != Null) {
				if (brandMap.containsKey(s.BrandID__c)) {
					brandMap.put(s.BrandID__c, (brandMap.get(s.BrandID__c) == null ? 0 : brandMap.get(s.BrandID__c)) + s.Revenue_Amount__c);
				} else {
					brandMap.put(s.BrandId__c, s.Revenue_Amount__c);
				}
			} else if (s.AdvertiserID__c != Null) {
				if (advertiserMap.containsKey(s.AdvertiserID__c)) {
					advertiserMap.put(s.AdvertiserID__c, (advertiserMap.get(s.AdvertiserID__c) == null ? 0 : advertiserMap.get(s.AdvertiserID__c)) + s.Revenue_Amount__c);
				} else {
					advertiserMap.put(s.AdvertiserID__c, s.Revenue_Amount__c);
				}
			} else {
				if (agencyMap.containsKey(s.Invoice_AgencyID__c)) {
					agencyMap.put(s.Invoice_AgencyID__c, (agencyMap.get(s.Invoice_AgencyID__c) == null ? 0 : agencyMap.get(s.Invoice_AgencyID__c)) + s.Revenue_Amount__c);
				} else {
					agencyMap.put(s.Invoice_AgencyID__c, s.Revenue_Amount__c);
				}
			}
		}

		Set < Id > allAccountMap = new Set < Id > ();

		allAccountMap.addAll(brandMap.KeySet());
		allAccountMap.addAll(advertiserMap.KeySet());
		allAccountMap.addAll(agencyMap.KeySet());

		Map < Id, Account > AccountMap = new Map < Id, Account > ([Select
		Revenue_Last_Year__c
		From Account
		Where Id IN: allAccountMap]);

		for (Id d: brandMap.KeySet()) {
			if (accountMap.containsKey(d)) {
				accountMap.put(d, new Account(id = d, Revenue_Last_Year__c = (accountMap.get(d).Revenue_Last_Year__c == null ? 0 : accountMap.get(d).Revenue_Last_Year__c) + brandMap.get(d)));
			} else {
				accountMap.put(d, new Account(id = d, Revenue_Last_Year__c = brandMap.get(d)));
			}
			// accountList.add(new Account(Id=d, Revenue_Last_Year__c=brandMap.get(d)));
		}
		for (Id d: advertiserMap.KeySet()) {
			if (accountMap.containsKey(d)) {
				accountMap.put(d, new Account(id = d, Revenue_Last_Year__c = (accountMap.get(d).Revenue_Last_Year__c == null ? 0 : accountMap.get(d).Revenue_Last_Year__c) + advertiserMap.get(d)));
			} else {
				accountMap.put(d, new Account(id = d, Revenue_Last_Year__c = advertiserMap.get(d)));
			}
			// accountList.add(new Account(Id=d, Revenue_Last_Year__c=advertiserMap.get(d)));
		}
		for (Id d: agencyMap.KeySet()) {
			if (accountMap.containsKey(d)) {
				accountMap.put(d, new Account(id = d, Revenue_Last_Year__c = (accountMap.get(d).Revenue_Last_Year__c == null ? 0 : accountMap.get(d).Revenue_Last_Year__c) + agencyMap.get(d)));
			} else {
				accountMap.put(d, new Account(id = d, Revenue_Last_Year__c = agencyMap.get(d)));
			}
			// accountList.add(new Account(Id=d, Revenue_Last_Year__c=agencyMap.get(d)));
		}
		// update accountList;
		update accountMap.Values();
	}

	global void finish(Database.BatchableContext ctx) {
		database.executebatch(new BatchUpdateTotalRevenue(), 1000);
	}



	// Test Method
	private static TestMethod void testBatchAccountRevenueUpdateLastYear() {
		insert TestData.createCountriesList();
		Test.startTest();
		User testUser = [
		select name, email, ProfileId, Profile.Name
		from User
		where isActive = true
		and Profile.Name = 'System Administrator'
		limit 1];

		String testProfileId = [select id
		from Profile
		limit 1].id;

		ConstantsH__c newConstH = new ConstantsH__c(
		Acc_and_Contact_owner__c = testUser.Name,
		Department__c = 'Test Department 1',
		IsManager__c = false,
		//Price_Book__c             = testPB.Name,
		SetupOwnerId = testUser.ProfileId);
		insert newConstH;
		insert TestData.createBookingSystemSettings();
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
		insert TestData.createCountryCodeSettings();

		Map < String, RecordTypeInfo > oppRecTypesByName = Account.SObjectType.getDescribe().getRecordTypeInfosByName();
		System.debug('oppRecTypesByName:' + oppRecTypesByName);

		Account agency = new Account(
		Name = 'TestAgency',
		AccountNumber = 'ABC123456',
		Type = 'Agency',
		BillingStreet = 'Test Billing Street',
		BillingState = 'Test Billing State',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'London',
		Industry = 'Finance',
		IndClassLvl1__c = 'Finance',
		IndClassLvl2__c = 'Finance',
		Classified_Minor_Category__c = 'Finance',
		CustomerRef1__c = '12345',
		CustomerRef2__c = '23456',
		CustomerRef3__c = '34567',
		CustomerRef4__c = 'TestA',
		RecordTypeId = oppRecTypesByName.get('Agency').RecordTypeId);
		insert agency;

		Account acct = new Account(
		Name = 'TestAccount',
		AccountNumber = 'ABC123456',
		Type = 'Client',
		BillingStreet = 'Test Billing Street',
		BillingState = 'Test Billing State',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'London',
		Industry = 'Finance',
		IndClassLvl1__c = 'Finance',
		IndClassLvl2__c = 'Finance',
		Classified_Minor_Category__c = 'Finance',
		CustomerRef1__c = '12345',
		CustomerRef2__c = '23456',
		CustomerRef3__c = '34567',
		CustomerRef4__c = 'TestA',
		RecordTypeId = oppRecTypesByName.get('Advertiser').RecordTypeId);
		insert acct;

		Account brand = new Account(
		Name = 'TestBrand',
		ParentId = acct.Id,
		AccountNumber = 'ABC123456',
		Type = 'Brand',
		BillingStreet = 'Test Billing Street',
		BillingState = 'Test Billing State',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'London',
		Industry = 'Finance',
		IndClassLvl1__c = 'Finance',
		IndClassLvl2__c = 'Finance',
		Classified_Minor_Category__c = 'Finance',
		CustomerRef1__c = '12345',
		CustomerRef2__c = '23456',
		CustomerRef3__c = '34567',
		CustomerRef4__c = 'TestA',
		RecordTypeId = oppRecTypesByName.get('Advertiser').RecordTypeId);
		insert brand;


		List < Account_Mapping__c > accMapList = new List < Account_Mapping__c > ();
		accMapList.add(new Account_Mapping__c(
		Account__c = acct.Id,
		Source_System__c = 'CCI Metro',
		Source_Key__c = '23747',
		Active__c = True));
		accMapList.add(new Account_Mapping__c(
		Account__c = acct.Id,
		Source_System__c = 'CCI Mail',
		Source_Key__c = '28462',
		Active__c = True));
		accMapList.add(new Account_Mapping__c(
		Account__c = acct.Id,
		Source_System__c = 'Advance',
		Source_Key__c = '2347239',
		Active__c = True));

		insert accMapList;

		List < SalesRevenue__c > salesRevList = new List < SalesRevenue__c > ();
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Metro', Department__c = 'London Classified', AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-12), Revenue_Amount__c = 1000));
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Metro', Department__c = 'Metro', AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-12), Revenue_Amount__c = 3000));

		salesRevList.add(new SalesRevenue__c(Publication__c = 'You', Department__c = 'Daily Mail', BrandID__c = brand.ID, AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-12), Revenue_Amount__c = 1500));
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Daily Mail', Department__c = 'Daily Mail', BrandID__c = brand.ID, AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-12), Revenue_Amount__c = 4000));

		salesRevList.add(new SalesRevenue__c(Publication__c = 'You', Department__c = 'Daily Mail', Invoice_AgencyID__c = agency.ID, Period_End_Date__c = Date.today().addMonths(-12), Revenue_Amount__c = 7000));
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Daily Mail', Department__c = 'Daily Mail', Invoice_AgencyID__c = agency.ID, Period_End_Date__c = Date.today().addMonths(-12), Revenue_Amount__c = 10000));


		insert salesRevList;

		BatchAccountRevenueUpdateLastYear batchrun = new BatchAccountRevenueUpdateLastYear();
		Integer batchSize = 6;
		database.executebatch(batchrun, batchSize);
		Test.stopTest();

		Set < Id > accountSet = new Set < Id > ();
		accountSet.add(brand.Id);
		accountSet.add(acct.Id);
		accountSet.add(agency.Id);
		Map < Id, Account > accMap = new Map < Id, Account > (
		[Select
		Revenue_Last_Year__c
		From Account
		Where Id IN: accountSet]);
		System.assertEquals(4000.00, accMap.get(acct.ID).Revenue_Last_Year__c);
		System.assertEquals(5500.00, accMap.get(brand.ID).Revenue_Last_Year__c);
		System.assertEquals(17000.00, accMap.get(agency.ID).Revenue_Last_Year__c);
	}

}