src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/Nielsen_Data__c.object
<CustomObject>
    <description>This Object has been created as part of the CRM Quick Wins2 Project. It will be populated from an external system by BIU.</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>NielsenData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Advert_Size__c</fullName>
        <label>Advert Size</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <label>Brand Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreativeId__c</fullName>
        <label>CreativeId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expenditure__c</fullName>
        <label>Expenditure</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Seen__c</fullName>
        <label>First Seen</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Incidence__c</fullName>
        <label>Incidence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Seen__c</fullName>
        <label>Last Seen</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Media_Type__c</fullName>
        <label>Media Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Group__c</fullName>
        <label>Publication Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Nielsen Data</label>
    <nameField>
        <displayFormat>ND-{00000000}</displayFormat>
        <label>ND Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nielsen Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewNielsenDataWithinAccountControl_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */@isTest
private class ViewNielsenDataWithinAccountControl_Test {

	static testMethod void testNielsenData() {
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
		insert TestData.createCountryCodeSettings();
		insert TestData.createCountriesList();

		Map < String, RecordTypeInfo > oppRecTypesByName = Account.SObjectType.getDescribe().getRecordTypeInfosByName();
		final String developerName = 'Advertiser';

		id Profile1 = userinfo.getProfileId();
		String timeZone = UserInfo.getTimeZone().getID();

		User ownerInit = new User(ProfileId = Profile1, LastName = 'A&N Media', Alias = 'ANMedia', email = 'a@dmgmedia.co.uk', username = 'A&NMedia@dmgmedia.co.uk', TimeZoneSidKey = timeZone, LocaleSidKey = 'en_GB', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US');
		insert ownerInit;

		User owner = [Select Name, ProfileId
		From User
		Where Id = : ownerInit.Id];

		System.debug(owner.Name);

		ConstantsH__c newConstH = new ConstantsH__c(
		Acc_and_Contact_owner__c = owner.Name,
		Department__c = 'IT',
		IsManager__c = false,
		Price_Book__c = owner.Name,
		SetupOwnerId = owner.ProfileId);
		insert newConstH;

		Account acct = new Account(
		Name = 'Test - TestNielsenData',
		AccountNumber = 'ABC123456',
		Industry = 'Finance',
		Type = 'Booking Agency',
		BillingStreet = 'Agency Street',
		BillingState = 'Agency TestState',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'Agency City',
		RecordTypeId = oppRecTypesByName.get(developerName).RecordTypeId);
		insert acct;

		Nielsen_Data__c nd = new Nielsen_Data__c(
		Publication__c = 'Metro London',
		Publication_Group__c = '',
		Media_Type__c = 'Press',
		Last_Seen__c = date.today(),
		Incidence__c = 1,
		First_Seen__c = date.today(),
		Expenditure__c = 100000,
		Description__c = 'test',
		CreativeId__c = 123456,
		Category__c = 'test',
		Brand_Name__c = 'test',
		Advert_Size__c = '10X10',
		AccountID__c = acct.Id);
		insert nd;

		ApexPages.StandardController sc = new ApexPages.StandardController(acct);
		ViewNielsenDataWithinAccountController c = new ViewNielsenDataWithinAccountController(sc);
		System.assertEquals(1, c.getAllNielsenData().size());
	}
}