src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Relationship_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Relationship_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Active__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationship Contacts</relationshipLabel>
        <relationshipName>Relationship_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Relationship__c</referenceTo>
        <relationshipLabel>Relationship Contacts</relationshipLabel>
        <relationshipName>Relationship_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Contact</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountReactivateController.cls
public with sharing class AccountReactivateController {

private ApexPages.StandardController controller;
    public Account reacc;
    List<Contact> UpdatedContacts=new List<Contact>();
    List<Relationship__c> UpdatedRelations=new List<Relationship__c>();
    List<Relationship_Contact__c> UpdatedRelationshipContacts=new List<Relationship_Contact__c>();
    Public Boolean accountstatus;
    public AccountReactivateController(ApexPages.StandardController stdcontroller) {
    //controller = stdController;
        this.reacc= (Account)stdController.getRecord();
         System.debug('*******Account:'+reacc);
        
        reacc=[Select IsActive__c from Account Where id= :reacc.id ];
        accountstatus=reacc.IsActive__c;
        System.debug('*******IsActive__c:'+accountstatus);
        //if(reacc.IsActive__c=false)
        if(!accountstatus)
        {
            reacc.IsActive__c=true;
        }          
    }

  public PageReference myreactivate(){
                 
             if (reacc != Null && !accountstatus )
             {
                update reacc;
             }
             controller = new ApexPages.standardController(reacc);
             return controller.view();
  }           
}