src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <recordTypes>
        <fullName>Media_Partner</fullName>
        <active>true</active>
        <description>Please select this record type to create a Media Partner.</description>
        <label>Media Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/objects/Constants__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Advertiser_Record_Type__c</fullName>
        <defaultValue>&apos;Advertiser&apos;</defaultValue>
        <label>Advertiser Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Record_Type__c</fullName>
        <defaultValue>&apos;Agency&apos;</defaultValue>
        <label>Agency Record Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef1email__c</fullName>
        <label>CustomerRef1email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef2email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef2email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef3email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef3email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef4email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef4email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef5email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef5email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Media_Lead_Opp_Record_Type__c</fullName>
        <defaultValue>&apos;Media_Opportunities&apos;</defaultValue>
        <label>Media Lead Opp Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Media_Partner_Record_Type__c</fullName>
        <defaultValue>&apos;Media_Partner&apos;</defaultValue>
        <label>Media Partner Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regular_Opp_Record_Type__c</fullName>
        <defaultValue>&apos;New_Business&apos;</defaultValue>
        <label>Regular Opp Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Constants</label>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Agency account type should be Agency or Direct Advertiser and it needs to be Active.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Direct Advertiser,Billing Agency,Charity,Private Advertiser,Brand, Booking Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pitches (Agency)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Insertion_Date__c</fullName>
        <label>MigFirst Insertion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Insertion_Date__c</fullName>
        <label>MigLast Insertion Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>Metro Display - Opportunities</businessProcess>
        <description>Please use this Type to create a standard Pitch</description>
        <label>Pitch</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Insertion_Date__c</fullName>
        <label>First Insertion Date Old</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Insertion_Date__c</fullName>
        <label>Last Insertion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revenue_Group__c</fullName>
        <label>Revenue Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Revenue__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Schedule_Revenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Schedule Revenue</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Group__c</fullName>
        <label>Revenue Group</label>
        <picklist>
            <picklistValues>
                <fullName>ROP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Projects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wraps</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Schedule_Revenue__c</fullName>
        <label>Schedule Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>Manual</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/RevenueSchedule_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */@isTest(SeeAllData = true)
private class RevenueSchedule_Test {
	static{
		BookingSystemSettings__c bSS = BookingSystemSettings__c.getInstance('CCI');
		if (bSS == null) insert TestData.createBookingSystemSettings();
		if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
			insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
		}
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
	}
	static testMethod void TestRevenueSchedule() {

		Constants__c oldC = [select id, Name from Constants__c where Name = 'All'
		limit 1];
		if (oldC != null) delete oldC;

		Constants__c newC = new Constants__c(
		Name = 'All',
		Regular_Opp_Record_Type__c = 'New_Business',
		Media_Partner_Record_Type__c = 'Media_Partner',
		Media_Lead_Opp_Record_Type__c = 'Media_Opportinities',
		Agency_Record_Type__c = 'Agency',
		Advertiser_Record_Type__c = 'Advertiser',
		CustomerRef5email__c = 'ssfoperative@anmedia.co.uk.andev',
		CustomerRef4email__c = 'ssfoperative@anmedia.co.uk.andev',
		CustomerRef3email__c = 'ssfoperative@anmedia.co.uk.andev',
		CustomerRef2email__c = 'ssfoperative@anmedia.co.uk.andev',
		CustomerRef1email__c = 'ssfoperative@anmedia.co.uk.andev');
		insert newC;

		// Set up an Account
		String advertiserRecTypeId = [Select id From RecordType Where Name = : Constants__c.getInstance('All').Advertiser_Record_Type__c limit 1].id;
		String agencyRecTypeId = [Select id from RecordType Where Name = : Constants__C.getInstance('All').Agency_Record_Type__c limit 1].id;

		User tmpUser = [select id from User where UserType = : 'Standard' /*and managerId != null*/ and isActive = true LIMIT 1];
		User testUser = [select name, email, ProfileId, Profile.Name from User where isActive = true /*and managerId != null*/ and Profile.Name = 'System Administrator'
		limit 1];

		List < Pricebook2 > standardPB = [select id, name from Pricebook2 where isStandard = true limit 1];
		// system.debug('+++++++++ Standard Pricebook: ' + testPB);

		String testProfileId = [select id from Profile limit 1].id;

		ConstantsH__c oldConstH = [select id, Name, Price_Book__c, Acc_and_Contact_owner__c from ConstantsH__c where SetupOwnerId = : testUser.ProfileId limit 1];
		if (oldConstH != null) delete oldConstH;

		ConstantsH__c newConstH = new ConstantsH__c(
		Acc_and_Contact_owner__c = testUser.Name,
		Department__c = 'None',
		IsManager__c = false,
		Price_Book__c = standardPB[0].Name,
		SetupOwnerId = testUser.ProfileId);
		insert newConstH;

		List < Account > acctsToInsert = new List < Account > ();

		Account client = new Account(
		Name = 'Test Account',
		AccountNumber = 'ABC123456',
		Type = 'Client',
		Industry = 'Finance',
		RecordTypeId = advertiserRecTypeId,
		BillingCountry = 'United Kingdom',
		ownerId = tmpUser.Id,
		BillingPostalCode = 'A111AA',
		Phone = '0123654789654');
		acctsToInsert.Add(client);

		Account agency = new Account(
		Name = 'Test Agency',
		AccountNumber = 'AGN123456',
		Type = 'Billing Agency',
		Industry = 'Finance',
		RecordTypeId = agencyRecTypeId,
		BillingStreet = '1',
		BillingPostalCode = 'A111AA',
		Phone = '0123654789654',
		BillingCountry = 'United Kingdom',
		ownerId = tmpUser.Id);
		acctsToInsert.Add(agency);
		//system.debug('++++++++++ Accounts: ' + acctsToInsert);

		insert acctsToInsert;

		Opportunity opp = new Opportunity(
		Name = 'Test Opportunity',
		AccountId = acctsToInsert[0].Id,
		Agency__c = acctsToInsert[1].Id,
		StageName = 'Qualification',
		CloseDate = date.newinstance(2012, 10, 20));
		insert opp;

		Product2 prod1 = new Product2(
		Name = 'Prod1',
		Schedule_Revenue__c = 'Monthly',
		Revenue_Group__c = 'Digital',
		IsActive = true);
		insert prod1;

		PricebookEntry pbeToInsert = new PricebookEntry(
		UnitPrice = 100,
		Product2Id = prod1.Id,
		Pricebook2Id = standardPB[0].Id,
		IsActive = true,
		CurrencyIsoCode = 'GBP');
		insert pbeToInsert;

		Date firstDate = date.newinstance(2012, 10, 20);
		Date lastDate = date.newinstance(2013, 10, 20);
		OpportunityLineItem oli = new OpportunityLineItem(
		Quantity = 1,
		PricebookEntryId = pbeToInsert.Id,
		OpportunityId = opp.Id,
		ServiceDate = firstDate,
		First_Insertion_Date__c = firstDate,
		Last_Insertion_Date__c = lastDate,
		Active__c = true,
		UnitPrice = 100);
		insert oli;

		OpportunityLineItem o = [select ServiceDate, Last_Insertion_Date__c, UnitPrice from OpportunityLineItem where ServiceDate = : firstDate limit 1];

		RevenueSchedule rs = new RevenueSchedule();
		List < RevenueSchedule.RevenueScheduleItem > rsi;
		rsi = rs.generateSchedule(o.ServiceDate, o.Last_Insertion_Date__c, o.UnitPrice);

	}
}