src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCIMailCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMailCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCIMetroCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMetroCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Industry_Minor_Category__c</fullName>
        <label>Industry Minor Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>04.01.30 - GIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.10 - BEER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.12 - LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.05 - ALCOHOL FREE BEER &amp; LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.20 - BRANDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.80 - VODKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.40 - PORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.89 - CHAMPAGNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.50 - SHERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.93 - ALCOPOPS ALCOHOL SOFT DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.25 - CIDER &amp; PERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.00 - TOBACCO ACCESSORIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.05 - LIGHTERS,MATCHES,OTHER ACCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.00 - TOBACCO RANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.10 - CIGARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.05 - CIGARETTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.99.99 - COSMETICS &amp; TOILETRIES CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.00 - PROFESSIONAL/B2B HAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.40 - SALONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.00 - MEN &amp; WOMENS FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.10 - PREMIUM MENS/WOMENS FRAG RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.05 - PREMIUM WOMENS PERFUMES/FRAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.11 - MASS MKT MENS/WOMENS FRAG RG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.00 - PERSONAL HYGIENE &amp; HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.55 - SHAVING PREPARATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.50 - SANITARY PROTECTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.65 - WET RAZORS &amp; BLADES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.91 - PERSONAL HYGIENE &amp; HEALTH GE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.05 - DENTALCARE-DENTURE CLEANERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.20 - DENTALCARE-TOOTHPASTE,POLISH</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <fields>
        <fullName>BookingPluginPath__c</fullName>
        <label>BookingPluginPath</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <description>OAUTH2 Client Id for CCI. This will be updated by CCI on a regular basis.</description>
        <externalId>true</externalId>
        <label>ClientId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>ContentType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EditBookingPluginPath__c</fullName>
        <label>EditBookingPluginPath</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderPath__c</fullName>
        <label>OrderPath</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PackagePath__c</fullName>
        <label>PackagePath</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SharedSecret__c</fullName>
        <description>OAUTH2 Shared Secret for CCI. This will be updated by CCI on a regular basis.</description>
        <label>SharedSecret</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TempDomain__c</fullName>
        <description>Should be removed for Production</description>
        <label>TempDomain</label>
        <type>Url</type>
    </fields>
    <label>BookingSystemSettings</label>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/FinanceAccount__c.object
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Agency account type should be Agency or Direct Advertiser and it needs to be Active.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Direct Advertiser,Billing Agency,Charity,Private Advertiser,Brand, Booking Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pitches (Agency)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CustomerRef__c</fullName>
        <label>CustomerRef</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCI_Order_ID__c</fullName>
        <description>CCI AdDesk Sales Order Id</description>
        <externalId>true</externalId>
        <label>CCI Order ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderParams__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Accountid__c</fullName>
        <label>Accountid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Advertiser__c</fullName>
        <label>Advertiser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>ClientId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfirmationURL__c</fullName>
        <label>ConfirmationURL</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <label>OpportunityId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedCustomers__c</fullName>
        <label>RelatedCustomers</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>OrderParams</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CustomerRef__c</fullName>
        <label>CustomerRef</label>
        <picklist>
            <picklistValues>
                <fullName>CustomerRef1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CCI_User_Id__c</fullName>
        <label>CCI User Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCI_User_Password__c</fullName>
        <label>CCI User Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CCIManager.cls
/******************
*****
Crafted by :yuvikaAggarwal
Date Created:  2014-01-24
Api Version   :v1
****************************/
public without sharing class CCIManager {

    public static String metroUser = 'Metro';
    public static String mailDisplayUser = 'MailDisplay';
    
   


    public static String createDirectAccountOrder(String accId, String selectedBillingAccount, String sopId, String cciCustomerId, String bookingAgency, String bookingcciId, String parentcciId, String holdingCoCCIId, String holdingAgencyCCIId, String cciProfile, String cciGroup) {
        List < String > accsToQuery = new List < String > ();
        accsToQuery.add(accId);
        accsToQuery.add(selectedBillingAccount);
        String domain;
        String bookingPluginPath;
        BookingSystemSettings__c setting = Common.cci;
        OrderParams__c orderParams = Common.cciOrderParams;
        if (setting != null) {
            domain = setting.Domain__c;
            bookingPluginPath = setting.BookingPluginPath__c;
            if (domain == null || bookingPluginPath == null) throw new BookingSystemSettingsException();
        }


        String url = domain + bookingPluginPath;
        System.debug('URL after bookingsettings' + url);
        String errorResponse;
        String errorResponseAcc;
        String cciAccountId;
        FinanceAccount__c newFinAcc;
        String billingCustomerId;
        Account acc = [SELECT CCIMailCustID__c, CCIMetroCustID__c, Name, Type, Phone,
        BillingStreet, Industry_Minor_Category__c, BillingPostalCode,
        Industry, BillingState, BillingCountry
        FROM Account
        WHERE ID = : accId Limit 1];

        User u = Common.getUserInfo();
        System.debug('User is' + u);
        //String userType = Common.getUserType(u);

        if (Common.sharedSecret != null) {
            List < String > sList = common.userInformation.Email.split('@', 2);
            // url = url + 'userid=' + sList[0] + '&clientid=' + Common.cci.ClientId__c + '&clientsecret=' + Common.cci.SharedSecret__c + '&group=' + Common.userGroup() + '&profile=' + Common.userProfile();
            // url = url + 'userid=' + sList[0] + '&group=' + Common.userGroup() + '&profile=' + Common.userProfile();
            // url = url + orderParams.UserId__c + Common.cciuser  + orderParams.Group__c + Common.userGroup() + orderParams.Profile__c + Common.userProfile();
            url = url + orderParams.UserId__c + Common.cciuser  + orderParams.Group__c + cciGroup + orderParams.Profile__c + cciProfile;
            //'userid='+u.CCI_User_Id__c+'&password='+u.CCI_User_Password__c+'&group='+Common.userGroup()+'&profile='+Common.userProfile();
        } else {
            if (String.IsBlank(u.CCI_User_Id__c)) {
                throw new CCIAPIException(Label.InvalidCCIUser);
            }
            // url = url + 'userid=' + u.CCI_User_Id__c + '&password=' + u.CCI_User_Password__c + '&group=' + Common.userGroup() + '&profile=' + Common.userProfile();
            // url = url + orderParams.UserId__c + u.CCI_User_Id__c + orderParams.Password__c + u.CCI_User_Password__c + orderParams.Group__c + Common.userGroup() + orderParams.Profile__c + Common.userProfile();
            url = url + orderParams.UserId__c + u.CCI_User_Id__c + orderParams.Password__c + u.CCI_User_Password__c + orderParams.Group__c + cciGroup + orderParams.Profile__c + cciProfile;
        }
        // if(Common.mailUser.equal(userType))GAR-190
        //assign mailcustomerif of topparentaccount to URL else metrocustomer of topparentacc



        // url = url + '&accountid=' + sopId + '&advertiserid=' + cciCustomerId;
        url = url + orderParams.Accountid__c + sopId + orderParams.Advertiser__c + cciCustomerId;
        if ((bookingcciId != null) || parentcciId != null|| holdingCoCCIId!=null|| holdingAgencyCCIId!=null) {
            Integer relationsCount = 0;
            url = url+orderParams.RelatedCustomers__c+'{';
            if (bookingcciId != null) {
                 if(relationsCount>0)
                    url = url + ',';
                 url = url + '"Booking Agency":"' + bookingcciId + '"';
                 relationsCount++;
                 }
            if (parentcciId != null) {
                if(relationsCount>0)
                    url = url + ',';
                url = url+'"Client":"' + parentcciId + '"';
                relationsCount++;
                }
            if (holdingCoCCIId != null){
                if(relationsCount>0) url = url + ',';
                url = url + '"Holding Company":"' + holdingCoCCIId + '"';
                relationsCount++;
             }
             if (holdingAgencyCCIId != null){
                  if(relationsCount>0)
                    url = url + ',';
                    url = url + '"Holding Agency":"' + holdingAgencyCCIId + '"';
                 }
                    
                url = url+'}';
             
                }


            
          System.debug('URLbefore creating oppportunity' + url);
        //Step 3-Create opportunity-start of comment 1
     /*   Opportunity opp = createOpportunity(acc.Id, acc.Name, selectedBillingAccount);
        //Step4 Create OpportunityLineItem
      OpportunityLineItem newOpline = CreateOppLineItem(opp.Id, opp.CurrencyIsoCode);
        boolean closed = CloseOpportunity(opp);

        Datetime firstInsertionDate = datetime.newInstance(newOpline.ServiceDate.year(), newOpline.ServiceDate.month(), newOpline.ServiceDate.day());
        url = url + orderParams.OpportunityId__c + newOpline.OpportunityId;*/
        //end of comment 1
        // url = getURLBasedOnAccountType(userType,'1','1',url,acc,newOpline,firstInsertionDate);
        System.debug('URL before exiting createDirectAccountOrder method ' + url);
        // url = url+'&confirmationurl='+ ApexPages.currentPage().getHeaders().get('Host')+'/'+accId;
        //   url = url+'&confirmationurl='+ System.URL.getSalesforceBaseUrl().getHost().remove('-api' ) +'/'+accId;
        //  url=url+'&confirmationurl=https://cs7.salesforce.com/'+accId;
        //need to uncomment below line
        url = url + orderParams.ConfirmationURL__c + Common.GetBaseUrlForInstance() + '/' + accId;
        System.debug('URL before exiting the system ...' + url);
        return url;

    }



    //Step1-Create opportunity before creating an order
    public static Opportunity CreateOpportunity(Id accId, String accName, String agencyId) {
        System.debug('Entering CreateOpportunity....');
        Id oppId;
        Opportunity newOp = new Opportunity();
        if (accId != null) {

            newOp.AccountId = accId;
            newOp.Name = 'Direct Order for ' + +accName +' '+ System.now();
            newOp.Type = 'Proactive';
            newOp.StageName = 'Preparation';
            newOp.Agency__c = agencyId;
            newOp.closeDate = System.Today();
            newOp.CurrencyIsoCode = 'GBP';


            insert newOp;
        }

        return newOp;
    }


    public static OpportunityLineItem CreateOppLineItem(Id oppId, String CurrencyIsoCode) {
        System.debug('Entering createOppLineItem and currencyIsocode' + CurrencyIsoCode);
        Id profileId = userinfo.getProfileId();
        String profileName = [Select Id, Name from Profile where Id = : profileId].Name;
        System.debug('Profile Name is' + profileName);
        //ConstantsH__c constant = ConstantsH__c.getInstance(profileName);
        ConstantsH__c constant = ConstantsH__c.getInstance(profileId);
        String priceBook = constant.Price_Book__c;
        System.debug('Pricebook is' + priceBook);
        List < PricebookEntry > priceBooks = [Select Id, Product2Id From PricebookEntry Where Pricebook2.Name = : priceBook and isactive = true and Product2.CustomerRef__c = 'CustomerRef3'
        and Pricebook2.CurrencyIsoCode = : CurrencyIsoCode];

        OpportunityLineItem newOpline = new OpportunityLineItem();
        newOpline.OpportunityId = oppId;
        newOpline.PriceBookEntryId = priceBooks[0].Id;
        //newOpline.PriceBookEntryId = priceBooks[0].Product2Id;
        newOpline.UnitPrice = 0.01;
        newOpline.Quantity = 1;
        newOpline.ServiceDate = System.Today();

        insert newOpLine;
        return newOpline;

    }



    public static boolean CloseOpportunity(Opportunity opp) {
        if (opp.StageName != 'Closed Won') opp.StageName = 'Closed Won';
        try {
            upsert opp;
            return true;
        } catch (Exception e) {
            System.debug('Exception while closing an opportunity.' + opp.id);
            return false;
        }
    }

/*This is a method to cancel an existing order
*/
  /*  public static String cancelOrder(Id orderId,String code,String reason){
         BookingSystemSettings__c setting = Common.cci;
         String domain;
         String orderPath;
         String accessToken;
         
         if(setting != null){
            domain = setting.Domain__c;
            orderPath = setting.OrderPath__c;
            if (domain == null || orderPath == null) throw new BookingSystemSettingsException();
        }else throw new BookingSystemSettingsException();
         
         if(Common.cciToken != null) {
                accessToken = Common.cciToken.access_token;
           } else {
                throw new CCIApiException('Can not read Access Token.');
            }
        CCIOrderCancel cancelOrder = new CCIOrderCancel(code,reason);
        String jsonreq = cancelOrder.getReqJsonBody();
        //creating HttpRequest
        HttpRequest req = new HttpRequest();  
        req.setMethod('POST');  
        req.setEndpoint(domain+orderPath+'/'+orderId+'/cancellation');   
        req.setHeader('Content-Type', 'application/json');  
        req.SetHeader('x-cci-user', Common.cciuser);
        req.SetHeader('x-cci-profile', common.userProfile());
        req.SetHeader('x-cci-group', common.userGroup());
        req.SetHeader('Authorization', 'bearer ' + accessToken);
        req.setBody(jsonreq);
        req.setTimeout(60000);
        
        Http http = new Http();
        HttpResponse res = new HttpResponse();
        res = http.send(req);
        if (!(res.getStatusCode() == 201 || res.getStatusCode() == 200)) {
            return 'Failure';
        }
       return 'Success';
     //   req.setCompressed(true);   
 

}*/


    public static String editAccountOrder(String orderId, String cciProfile, String cciGroup) {
        String domain;
        String bookingPluginPath;
        BookingSystemSettings__c setting = BookingSystemSettings__c.getInstance('CCI');
        OrderParams__c orderParams = Common.cciOrderParams;

        if (setting != null) {
            domain = setting.Domain__c;
            //   domain = setting.TempDomain__c;
            bookingPluginPath = setting.EditBookingPluginPath__c;
            if (domain == null || bookingPluginPath == null) throw new BookingSystemSettingsException();
        }


        String url = domain + bookingPluginPath;
        System.debug('URL after bookingsettings' + url);
        String errorResponse;
        String errorResponseAcc;


        Order order = [SELECT id, CCI_Order_ID__c
        FROM Order
        WHERE ID = : orderId Limit 1];

        User u = Common.getUserInfo();
        System.debug('User is' + u);
        String userType = Common.getUserType(u);


        if (String.IsBlank(order.CCI_Order_ID__c)) {
            throw new CCIAPIException(Label.NoOrder);
        }
        if (Common.sharedSecret != null) {
            List <String > sList = common.userInformation.Email.split('@', 2);
            //  url = url + order.CCI_Order_ID__c + '?userid=' + u.CCI_User_Id__c + '&password=' + u.CCI_User_Password__c + '&group=' + Common.userGroup() + '&profile=' + Common.userProfile();
             url = url + order.CCI_Order_ID__c + '?'+orderParams.UserId__c +Common.cciuser  + orderParams.Group__c + cciGroup + orderParams.Profile__c + cciProfile;
        } else {
            url = url + order.CCI_Order_ID__c + orderParams.UserId__c + u.CCI_User_Id__c + orderParams.Password__c + u.CCI_User_Password__c + orderParams.Group__c + cciGroup + orderParams.Profile__c + cciProfile;
        }


        System.debug('Before exiting editOrder' + url);

        // url =  url+'&confirmationurl='+ ApexPages.currentPage().getHeaders().get('Host')+'/'+order.Id;   
        url = url + '&confirmationurl=' + Common.GetBaseUrlForInstance() + '/' + order.Id;
        System.debug('Before exiting editOrder 2part' + url);
        return url;

    }
  // method to get CCI packages to display for opportunity creation
 /*  public static void getcciPackages(){
        BookingSystemSettings__c setting = Common.cci;
        String packageEndpoint = setting.Domain__c + setting.PackagePath__c;
        String contentType =  setting.ContentType__c;
        if (String.IsBlank(packageEndpoint) || String.IsBlank(contentType)) {
                    throw new BookingSystemSettingsException();
           }
      
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint(packageEndpoint);
        req.setHeader('Content-Type', contentType);
        req.SetHeader('x-cci-user', Common.cciuser);
        req.SetHeader('x-cci-profile', common.userProfile());
        req.SetHeader('x-cci-group', common.userGroup());
        req.SetHeader('Authorization', 'bearer ' + common.cciToken);
        try{
            //creating an HttpRequest
             Http http = new Http();
             HttpResponse res = new HttpResponse();
             res = http.send(req);
             System.debug('Response is' + res);
            if (!(res.getStatusCode() == 200)) {
                throw new CCIAPIException(Label.ErrorGettingPackages);
            } else {
              //  List<packageobject> deserializedPackages = 
           //   (List<packageobject>)JSON.deserialize(JSONString, List<packageobject>.class);
            String updatedResponse = res.getBody().replace('desc','description');
               List<CCIPackages> deserializedPackages = 
              (List<CCIPackages>)System.JSON.deserialize(updatedResponse ,List<CCIPackages>.class);
            
        }}catch(Exception e){
        
       }
       
   }*/
   

}