src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry_Minor_Category__c</fullName>
        <label>Industry Minor Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>04.01.30 - GIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.10 - BEER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.12 - LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.05 - ALCOHOL FREE BEER &amp; LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.20 - BRANDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.80 - VODKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.40 - PORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.89 - CHAMPAGNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.50 - SHERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.93 - ALCOPOPS ALCOHOL SOFT DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.25 - CIDER &amp; PERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.00 - TOBACCO ACCESSORIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.05 - LIGHTERS,MATCHES,OTHER ACCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.00 - TOBACCO RANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.10 - CIGARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.05 - CIGARETTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.99.99 - COSMETICS &amp; TOILETRIES CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.00 - PROFESSIONAL/B2B HAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.40 - SALONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.00 - MEN &amp; WOMENS FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.10 - PREMIUM MENS/WOMENS FRAG RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.05 - PREMIUM WOMENS PERFUMES/FRAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.11 - MASS MKT MENS/WOMENS FRAG RG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.00 - PERSONAL HYGIENE &amp; HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.55 - SHAVING PREPARATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.50 - SANITARY PROTECTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.65 - WET RAZORS &amp; BLADES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.91 - PERSONAL HYGIENE &amp; HEALTH GE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.05 - DENTALCARE-DENTURE CLEANERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.20 - DENTALCARE-TOOTHPASTE,POLISH</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Industry_Sub_Category__c</fullName>
        <label>Industry Sub Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>00.00 - UNKNOWN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.01 - BAKERY GOODS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.02 - CONFECTIONERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.03 - COOKING PRODUCTS &amp; SEASONING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.04 - DAIRY PRODUCTS &amp; SUBSTITUTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.05 - USE 4.4.X</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.06 - FRUIT, VEGETABLES, PASTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.07 - MEAT, FISH &amp; POULTRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.08 - PREPARED &amp; CONVENIENCE FOODS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.09 - ORGANIC FOODS RGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.90 - FOOD - SPONSORSHIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02.99 - FOOD CORPORATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01 - ALCOHOLIC DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.02 - SOFT DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.03 - ORGANIC DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.04 - BEVERAGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01 - TOBACCO RANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02 - TOBACCO ACCESSORIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.01 - BATH TOILETRIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.02 - BEAUTY AIDS &amp; COSMETICS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.03 - HAIR PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04 - PERSONAL HYGIENE &amp; HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05 - MEN &amp; WOMENS FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06 - PROFESSIONAL/B2B HAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.99 - COSMETICS &amp; TOILETRIES CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.01 - FIRST AID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.02 - MEDICATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.03 - CHEMIST RELATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.04 - FAMILY PLANNING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.05 - HEALTH &amp; FITNESS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/classes/AccountIndustryCategoryControllerTest.cls
@isTest(seeAllData = false)
public with sharing class AccountIndustryCategoryControllerTest {

	public static testMethod void testAcccIndCategoryControllerSave() {
		insert TestData.createCountriesList();
		ConstantsH__c ch = new ConstantsH__c();
		ch.Acc_and_Contact_owner__c = 'A&N Media';
		ch.Department__c = 'IT';
		insert ch;

		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

		User u = new User(Alias = 'anmedia', Email = 'ANMedia@dmgmedia.com',
		EmailEncodingKey = 'UTF-8', FirstName = 'A&N', LastName = 'Media', LanguageLocaleKey = 'en_US',
		LocaleSidKey = 'en_US', ProfileId = p.Id,
		TimeZoneSidKey = 'America/Los_Angeles', UserName = 'ANMedia@dmgmedia.com');

		insert u;
		insert TestData.createBookingSystemSettings();
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
		insert TestData.createCountryCodeSettings();

		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		acc.Industry = '04-Drink';
		acc.Industry_Sub_Category__c = '04.01-Alcohalic Drinks';
		acc.Industry_Minor_Category__c = '04.01.10 BEER';
		insert acc;
		Map < String, List < String >> parentDepMapData = new Map < String, List < String >> ();
		//insert acc;
		ApexPages.StandardController sc = new ApexPages.StandardController(acc);
		AccountIndustryCategoryController controller = new AccountIndustryCategoryController(sc);
		List < String > subValues = new List < String > ();
		subValues.add('04.01-Alcohalic Drinks');
		subValues.add('04.02-SOFT DRINKS');
		subValues.add('04.03-ORGANIC DRINKS');

		List < String > minorValues = new List < String > ();
		minorValues.add('04.01.00 ALCOHLIC DRINKS');
		minorValues.add('04.01.10 BEER');

		controller.parentPicklistVal = '04-Drink';
		controller.childMultiPicklistVal = subValues;
		controller.ChildSinglePicklistVal = minorValues;



		controller.save();
		// controller.getParentPicklistOptions();
		//controller.getChildMultiPicklistOptions();
		// controller.getChildSinglePicklistOptions();
		controller.edit();
	}
}