src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_Minor_Category__c</fullName>
        <label>Industry Minor Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>04.01.30 - GIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.10 - BEER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.12 - LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.05 - ALCOHOL FREE BEER &amp; LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.20 - BRANDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.80 - VODKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.40 - PORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.89 - CHAMPAGNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.50 - SHERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.93 - ALCOPOPS ALCOHOL SOFT DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.25 - CIDER &amp; PERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.00 - TOBACCO ACCESSORIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.05 - LIGHTERS,MATCHES,OTHER ACCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.00 - TOBACCO RANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.10 - CIGARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.05 - CIGARETTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.99.99 - COSMETICS &amp; TOILETRIES CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.00 - PROFESSIONAL/B2B HAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.40 - SALONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.00 - MEN &amp; WOMENS FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.10 - PREMIUM MENS/WOMENS FRAG RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.05 - PREMIUM WOMENS PERFUMES/FRAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.11 - MASS MKT MENS/WOMENS FRAG RG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.00 - PERSONAL HYGIENE &amp; HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.55 - SHAVING PREPARATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.50 - SANITARY PROTECTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.65 - WET RAZORS &amp; BLADES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.91 - PERSONAL HYGIENE &amp; HEALTH GE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.05 - DENTALCARE-DENTURE CLEANERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.20 - DENTALCARE-TOOTHPASTE,POLISH</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>NPA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miss.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honorable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <label>CountryCode</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/CustomerCategory__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>CCI Customer Categories</description>
    <fields>
        <fullName>CategoryCode__c</fullName>
        <label>CategoryCode</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CustomerCategory</label>
</CustomObject>

src/classes/CCICustomerWrapper.cls
public class CCICustomerWrapper {


	public String name;
	public String addressAs;
	public String initials;
	public String surname;
	public String companyName;
	public Telephone mainTelephone;
	public Address mainAddress;
	public BusinessUnit businessUnit;
	public CustomerCategoryExt customerCategory;
	public String externalCustomerId;
	public IndustryCodes industryCodes;


	public CCICustomerWrapper() {}

	public CCICustomerWrapper(Account acc, String dbType) {
		if (acc.Type.equals('Private Advertiser')) {
			this.addressAs = acc.Salutation__c;
			this.initials = acc.FirstName__c;
			this.surname = acc.Name;
		} else {
			this.companyName = acc.name;
		}
		this.name = acc.name;

		this.externalCustomerId = acc.id;
		List < String > minorCategories = new List < String > ();
		List < IndustryCode > codes = new List < IndustryCode > ();
		//try{
		if (!String.isBlank(acc.Industry_Minor_Category__c)) {
			minorCategories = acc.Industry_Minor_Category__c.split(';');
			System.debug('Minor categories list' + minorCategories);
			for (String s: minorCategories) {
				IndustryCode c = new IndustryCode(s.split('-')[0].trim());
				codes.add(c);
			}
		}

		if (codes.size() > 0) {
			this.industryCodes = new IndustryCodes(codes);
		}
		CustomerCategory__c categories;


		if (acc.Type.contains('Agency') && !acc.Type.contains('Holding Agency')) {
			if (acc.NPA__c) categories = CustomerCategory__c.getInstance('NPA');
			else categories = CustomerCategory__c.getInstance('NonNPA');
		} else categories = CustomerCategory__c.getInstance(acc.Type);

		this.mainAddress = new Address(acc.BillingStreet, 'UK', acc.BillingCity, acc.BillingCountry, acc.BillingPostalCode, acc.BillingState);
		this.MainTelephone = new Telephone(acc.Phone);

		if (dbType == 'Mail') {
			this.businessUnit = new BusinessUnit('ML');

		} else {
			this.businessUnit = new BusinessUnit('Global');

		}
		if (categories != null) this.customerCategory = new CustomerCategoryExt(categories.CategoryCode__c);
		else {
			throw new CCIApiException('Customer Category does not exist for this account type');
		}
		/*   }catch(Exception e){
               throw new CCIApiException(e)  ;
               }*/
	}

	public class CustomerCategoryExt {
		public String categoryCode;
		public String categoryName;
		public String categoryDesc;
		public CustomerCategoryExt() {}
		public CustomerCategoryExt(String categoryCode) {
			this.categoryCode = categoryCode;
		}
	}

	public class BusinessUnit {
		String businessUnitCode;
		String businessUnitName;
		String businessUnitDesc;

		public BusinessUnit() {}
		public BusinessUnit(String businessUnitCode) {
			this.businessUnitCode = businessUnitCode;
		}

	}

	public class Address {

		//   public String streetAddress;
		public String city;
		public String county;
		public String zipCode;
		public String countryCode;
		public String countryName;
		// public String roomNo;
		public String collection1;

		public Address() {}
		public Address(String streetAdd, String countryCode, String billingCity, String countryName, String zipCode, String billingState) {
			// this.streetAddress = streetAdd;
			//  this.roomNo = streetAdd;

			this.collection1 = streetAdd;
			BookingSystemCountryCodes__c cciCountry = new BookingSystemCountryCodes__c();
			/*try
		        {*/
			if (String.IsBlank(countryName) || countryName == 'UK' || countryName == 'England' || countryName == 'Wales' || countryName == 'Scotland') {
				countryName = 'United Kingdom';
			}
			cciCountry = BookingSystemCountryCodes__c.getInstance(countryName);
			if (cciCountry == null) {
				throw new CCIApiException('Invalid Country - ' + countryName);
			}

			/*}
		        catch(Exception e)
		        {
		        	throw new CCIApiException ('Invalid Country - '+countryName);	
		        }*/


			//this.countryCode = countryCode;
			//this.countryName = countryName;
			this.countryCode = cciCountry.CountryCode__c;
			//this.countryCode = countryCode;
			this.countryName = countryName;
			this.zipCode = zipCode;
			this.city = billingCity;
			this.county = billingState;
		}
	}
	public class Telephone {

		public String id;
		public String phNumber;
		public String description;
		public Telephone() {}
		public Telephone(String phNumber) {
			this.phNumber = phNumber;
		}
	}


	public class IndustryCodes {
		//String partiallink = null;
		List < IndustryCode > industryCode;

		public IndustryCodes() {}
		public IndustryCodes(List < IndustryCode > industryCode) {
			this.industryCode = industryCode;

		}

	}

	public class IndustryCode {
		String code;
		public IndustryCode() {}
		public IndustryCode(String code) {
			this.code = code;
		}

	}

	public class AccountInfo {
		public Id accountId {
			get;
			set;
		}
		public String name {
			get;
			set;
		}
		public String phone {
			get;
			set;
		}
		public String billingStreet {
			get;
			set;
		}
		public String billingCity {
			get;
			set;
		}
		public String billingPostalCode {
			get;
			set;
		}
		public String billingState {
			get;
			set;
		}
		public String billingCountry {
			get;
			set;
		}
		public String industry_Minor_Category {
			get;
			set;
		}
		public String cciMailId {
			get;
			set;
		}
		public String cciMetroId {
			get;
			set;
		}
		public Boolean npa {
			get;
			set;
		}
		public String accountType {
			get;
			set;
		}
		public String firstName {
			get;
			set;
		}
		public String salutation {
			get;
			set;
		}

		public AccountInfo(Id accId, String n, String ph, String bs, String bc, String bp, String bstate, String bco, String im, String cma, String cme, Boolean npa, string tempType, String tempFirstName, String tempSalutation) {
			this.accountId = accId;
			this.name = n;
			this.phone = ph;
			bs = bs != null && bs != '' ? bs.replaceAll('\r', ' ') : '';
			bs = bs != null && bs != '' ? bs.replaceAll('\n', ' ') : '';
			this.billingStreet = bs;
			this.billingCity = bc;
			this.billingPostalCode = bp;
			this.billingState = bstate;
			this.billingCountry = bco;
			this.industry_Minor_Category = im;
			this.cciMailId = cma;
			this.cciMetroId = cme;
			this.npa = npa;
			this.accountType = tempType;
			this.firstName = tempFirstName;
			this.salutation = tempSalutation;
		}
	}


	public class AccessToken {
		public String access_token {
			get;
			set;
		}
		public String token_type {
			get;
			set;
		}
		public String refresh_token {
			get;
			set;
		}
		public String expires_in {
			get;
			set;
		}
		public String read {
			get;
			set;
		}

		public AccessToken(String ato, String tto, String rto, String exp, String rd) {
			this.access_token = ato;
			this.token_type = tto;
			this.refresh_token = rto;
			this.expires_in = exp;
			this.read = rd;
		}
	}

	/*public class IntegInfo
    {
        public String source {get; set;}
        public String account {get; set;}
        public String description {get; set;}

        public IntegInfo(String src, String acc, String descrip)
        {
            this.source=src;
            this.account=acc;
            this.description=descrip;
        
        }
    }*/

	public class ChatterInfo {
		public Id itemID {
			get;
			set;
		}
		public String message {
			get;
			set;
		}

		public ChatterInfo(Id itemID, String message) {
			this.itemID = itemID;
			this.message = message;
		}
	}
}