src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Agency account type should be Agency or Direct Advertiser and it needs to be Active.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Direct Advertiser,Billing Agency,Charity,Private Advertiser,Brand, Booking Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pitches (Agency)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account_A__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account A</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are some relationships which have Inactive Agencies attached to this Account. Please identify them and correct as necessary.</errorMessage>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Outgoing)</relationshipLabel>
        <relationshipName>Account_Account_rel_A</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_B__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account B</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are some relationships which have Inactive Agencies attached to this Account. Please identify them and correct as necessary.</errorMessage>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Incoming)</relationshipLabel>
        <relationshipName>Account_Account_rel_B</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityPitchController_Test.cls
/**
 *  @author: Andrey Gavrikov (westbrook)
 *  @date: 2013-11-08 11:43:04 
 *  @description:
 *      Test methods for OpportunityPitchController
 *  
 *  Version History :   
 *      
 */@isTest(SeeAllData = true) //There's no way to create a Standard Price Book in Apex, hence SeeAllData=true
public class OpportunityPitchController_Test {
	private static Pricebook2 stdPricebook;
	private static List < PricebookEntry > stdPBEntries;
	static {
		//standard price book and product prices
		stdPricebook = [select id from Pricebook2 where isStandard = true];
		stdPBEntries = Mock.many('PricebookEntry', new Map < String, Object > {
			'UnitPrice' => new Decimal[] {
				1, 2, 3
			},
				'Pricebook2Id' => stdPricebook.Id
		}, 3, true);
		BookingSystemSettings__c bSS = BookingSystemSettings__c.getInstance('CCI');
		if (bSS == null) insert TestData.createBookingSystemSettings();
	}
	/**
	 * Jira: Gl-10
	 * check when loading from Advertiser account
	 */
	static testMethod void testAsAsvertiser() {

		Mock.MOCK_DATA.addSingletonObjectType('Pricebook2');

		//create pricebook
		Pricebook2 pricebook = (Pricebook2) Mock.one('Pricebook2', true);

		String department = 'Test Dep 1';
		User usr = MockData.getTestUserWithConstantsH('System Administrator', department, pricebook.Name);
		List < User > teamMembers = Mock.many('User', new Map < String, Object > {
			'LastName' => 'Member #{COUNTER}',
				'ProfileId' => MockUtils.getProfile('System Administrator').Id
		}, 3, true);

		System.runAs(usr) {

			//create couple of Agency <-> Advertiser relationships
			List < Relationship__c > rels = Mock.many('Relationship__c#AdvertiserAgency', 2, true);
			final Id advertiser_Id = rels[0].Account_A__c;
			final Id agency_Id = rels[0].Account_B__c;

			//campaigns must belong to selected advertiser
			List < Campaign > campaigns = Mock.many('Campaign', new Map < String, Object > {
				'Account__c' => advertiser_Id
			}, 3, true);

			//add few products
			List < PricebookEntry > pbes = Mock.many('PricebookEntry', new Map < String, Object > {
				'UnitPrice' => new Decimal[] {
					10, 20, 30
				},
					'Product2Id' => Mock.toIds(stdPBEntries, 'Product2Id')
			}, 3, true);


			PageReference ref = Page.OpportunityPitch;
			Test.setCurrentPage(ref);
			Account acc = new Account(Id = advertiser_Id, Name = 'Acc1',
			RecordType = MockUtils.getRecordType('Account', 'Advertiser'));
			OpportunityPitchController con = new OpportunityPitchController(new ApexPages.StandardController(acc));
			test.startTest();
			Opportunity opp = con.getOpportunity();
			System.assertEquals(usr.Id, opp.OwnerId, 'Owner Id must be set to current user');
			System.assertEquals(advertiser_Id, opp.AccountId, 'Advertiser must not be blank, because there is existing relationship');
			System.assertEquals(agency_Id, opp.Agency__c, 'Agency must not be blank, because there is existing relationship');


			//following methods are difficult to verify for exact results because we have to work in SeeAllData environment
			System.assert(con.getCampaigns().size() >= campaigns.size(), 'Expected at least ' + campaigns.size() + ' campaigns');
			System.assert(con.getAdvertisers().size() > 0, 'Expected at least one Advertiser');
			System.assert(con.getAgencies().size() > 0, 'Expected at least one Agency');
			System.assert(con.getProductIconRows().size() > 0, 'Expected at least one product icon row');
			System.assert(OpportunityPitchController.getProductsByIcon(OpportunityPitchController.NO_ICON).size() >= 3,
				'Expected at least 3 products, because this many we created above');

			System.assert(OpportunityPitchController.getAvailableUserMap().size() >= 1, 'Expected some users');


			opp.CloseDate = Date.newInstance(2013, 01, 09);
			opp.Name = 'Test Opp';

			String productJSON = '';
			//'[{"pbeId":"01tD0000002McPgIAK", "id":"01tD0000002McPgIAK","name":"Daily Mail newspaper - Advertorials","amount":1,"startDate":"10/01/2013, 10/02/2013,...", "endDate":"10/01/2013"}]'
			for (PricebookEntry pbe: pbes) {
				String val = '';
				val += '"pbeId":"' + pbe.Id + '",';
				val += '"id":"' + pbe.Id + '",';
				val += '"name":" not used ",';
				val += '"startDate":"10/01/2013",';
				val += '"endDate":"11/01/2013",';
				val += '"amount":10';
				if ('' != productJSON) {
					productJSON += ',';
				}
				productJSON += '{' + val + '}';
			}
			con.productDataJSON = '[' + productJSON + ']';

			con.teamMemberIds = String.join(Mock.toIds(teamMembers), ',');
			con.selectedAdvertiserId15 = advertiser_Id;
			con.selectedAgencyId15 = agency_Id;
			con.selectedCampaign15 = campaigns[0].Id;
			System.assertEquals(advertiser_Id, con.selectedAdvertiserId15);
			System.assertEquals(agency_Id, con.selectedAgencyId15);
			System.assertEquals(campaigns[0].Id, con.selectedCampaign15);

			con.save();
			if (ApexPages.hasMessages(ApexPages.Severity.ERROR)) {
				//check if this is about "scheduling not enabled on product" or something else
				for (ApexPages.Message msg: ApexPages.getMessages()) {
					if (msg.getDetail().contains('scheduling not enabled on product')) {
						continue; //can safely ignore this message
					}
					System.assert(false, 'Did not expect any errors, but got this: ' + msg + '; productJSON=' + productJSON);
				}

			}
			//just code coverage for methods not containing any logic
			con.getUserLocale();
			con.cancel();
			con.reloadCampaigns();
			con.getAdvertiserType();
			test.stopTest();
		}
	}
	/**
	 * Jira: Gl-10
	 * check when loading from Agency account
	 */
	static testMethod void testAsAgency() {

		Mock.MOCK_DATA.addSingletonObjectType('Pricebook2');

		//create pricebook
		Pricebook2 pricebook = (Pricebook2) Mock.one('Pricebook2', true);

		String department = 'Test Dep 1';
		User usr = MockData.getTestUserWithConstantsH('System Administrator', department, pricebook.Name);

		System.runAs(usr) {

			//create couple of Agency <-> Advertiser relationships
			List < Relationship__c > rels = Mock.many('Relationship__c#AdvertiserAgency', 2, true);

			//add few products
			List < PricebookEntry > pbes = Mock.many('PricebookEntry', new Map < String, Object > {
				'UnitPrice' => new Decimal[] {
					10, 20, 30
				},
					'Product2Id' => Mock.toIds(stdPBEntries, 'Product2Id')
			}, 3, true);

			final Id advertiser_Id = rels[0].Account_A__c;
			final Id agency_Id = rels[0].Account_B__c;

			PageReference ref = Page.OpportunityPitch;
			Test.setCurrentPage(ref);
			Account acc = new Account(Id = agency_Id, Name = 'Acc1',
			RecordType = MockUtils.getRecordType('Account', 'Agency'), BillingPostalCode = 'a111aa',
			Phone = '01236547896');
			OpportunityPitchController con = new OpportunityPitchController(new ApexPages.StandardController(acc));

			Opportunity opp = con.getOpportunity();
			System.assertEquals(advertiser_Id, opp.AccountId, 'Advertiser must not be blank, because there is existing relationship');
			System.assertEquals(agency_Id, opp.Agency__c, 'Agency must not be blank, because there is existing relationship');

			opp.CloseDate = Date.newInstance(2013, 01, 09);
			opp.Name = 'Test Opp';
			con.productDataJSON = '[{invalid product JSON}]';

			con.save();
			System.assert(ApexPages.hasMessages(ApexPages.Severity.ERROR), 'Expected error message, because product JSON is invalid');

		}
	}
}