src/objects/Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Mappings</relationshipLabel>
        <relationshipName>Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_Key__c</fullName>
        <label>Customer Ref</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operative One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nielsen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDM Origins</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Mapping</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ObjectUpdateFromCCIResponse.cls
public Class ObjectUpdateFromCCIResponse {



	public static String createAccounMapping(String jsonResponse, String dbType, Id accId) {


		System.debug('Response is' + jsonResponse);

		// consume response (json)
		Map < String, Object > mWholeResponse = (Map < String, Object > ) JSON.deserializeUntyped(jsonResponse);
		System.debug('Whole response is' + mWholeResponse);
		//  Map<String, Object> mRespContent = (Map<String, Object>)mWholeResponse.get('Content');
		String customerId = (String) mWholeResponse.get('customerId');

		Account_Mapping__c accMapping = new Account_Mapping__c();
		if (dbType == 'Mail') {
			accMapping.Account__c = accId;
			accMapping.Source_Key__c = customerId;
			accMapping.Source_System__c = 'CCI Mail';
		} else if (dbType == 'Metro') {
			accMapping.Account__c = accId;
			accMapping.Source_Key__c = customerId;
			accMapping.Source_System__c = 'CCI Metro';
		}
		insert accMapping;


		return customerId;
	}



	public static String updateFinanceMapping(String jsonResponse) {



		// consume response (json)
		Map < String, Object > mWholeResponse = (Map < String, Object > ) JSON.deserializeUntyped(jsonResponse);
		System.debug('Whole response is' + mWholeResponse);
		String accountID = (String) mWholeResponse.get('accountId');
		System.debug('Account ID is' + accountID);

		return accountID;
	}



}