src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Classified_Minor_Category__c</fullName>
        <label>Classified - Minor Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accessories &amp; Soft Furnishings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia &amp; New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balearics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blackpool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bournemouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building &amp; Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Businesses For Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire &amp; Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clerical &amp; Secretarial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conservatories, Lofts &amp; Extensions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts &amp; Tenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cornwall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotswolds</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CustomerRef1__c</fullName>
        <label>CCI Metro Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef2__c</fullName>
        <label>AdVance Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef3__c</fullName>
        <label>CCI Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef4__c</fullName>
        <label>Operative Cust Ref</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IndClassLvl1__c</fullName>
        <label>Classified - Main Category</label>
        <picklist>
            <picklistValues>
                <fullName>Business &amp; Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &amp; Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homes &amp; Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noticeboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal &amp; Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IndClassLvl2__c</fullName>
        <label>Classified - Sub Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Airlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airport Parking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apprenticeships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (General)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Motors)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Property)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;B/Guest Houses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bars/Clubs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battlefields</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Births, Deaths and Marriages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business to Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping and Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravans &amp; Motorhomes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars wanted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinemas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City Living</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Trials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collectables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complementary Therapies &amp; Wellbeing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Business_Team_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Team Activities</relationshipLabel>
        <relationshipName>Business_Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Team Activity</label>
    <nameField>
        <label>Business Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Team Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/classes/BatchDelete_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */@isTest
private class BatchDelete_Test {

	static testMethod void myUnitTest1() {
		// Test Method
		{
			insert TestData.createCountriesList();
			Test.startTest();
			User testUser = [
			select name, email, ProfileId, Profile.Name
			from User
			where isActive = true /*and managerId != null*/ and Profile.Name = 'System Administrator'
			limit 1];

			String testProfileId = [select id from Profile limit 1].id;

			ConstantsH__c newConstH = new ConstantsH__c(
			Acc_and_Contact_owner__c = testUser.Name,
			Department__c = 'Test Department 1',
			IsManager__c = false,
			//Price_Book__c             = testPB.Name,
			SetupOwnerId = testUser.ProfileId);
			insert newConstH;
			insert TestData.createBookingSystemSettings();
			insert TestData.buildCompany();
			insert TestData.buildMetroCompany();
			insert TestData.createCountryCodeSettings();
			String advertiserRecTypeId = [
			select id
			from RecordType
			where DeveloperName = 'Advertiser'
			limit 1].id;

			Account acct = new Account(
			Name = 'TestAccount',
			AccountNumber = 'ABC123456',
			Type = 'Client',
			BillingStreet = 'Test Billing Street',
			BillingState = 'Test Billing State',
			BillingPostalCode = 'A111AA',
			BillingCountry = 'United Kingdom',
			BillingCity = 'London',
			Industry = 'Finance',
			IndClassLvl1__c = 'Finance',
			IndClassLvl2__c = 'Finance',
			Classified_Minor_Category__c = 'Finance',
			CustomerRef1__c = '12345',
			CustomerRef2__c = '23456',
			CustomerRef3__c = '34567',
			CustomerRef4__c = 'TestA',
			RecordTypeId = advertiserRecTypeId);
			insert acct;

			Account acct1 = new Account(
			Name = 'TestAccount1',
			AccountNumber = 'ABC123456',
			Type = 'Client',
			BillingStreet = 'Test Billing Street',
			BillingState = 'Test Billing State',
			BillingPostalCode = 'A111AA',
			BillingCountry = 'United Kingdom',
			BillingCity = 'London',
			Industry = 'Finance',
			IndClassLvl1__c = 'Finance',
			IndClassLvl2__c = 'Finance',
			Classified_Minor_Category__c = 'Finance',
			CustomerRef1__c = '12345',
			CustomerRef2__c = '23456',
			CustomerRef3__c = '34567',
			CustomerRef4__c = 'TestA',
			RecordTypeId = advertiserRecTypeId);
			insert acct1;

			merge acct acct1;
			Test.stopTest();
			List < Business_Team_Activity__c > deletedbtas = new List < Business_Team_Activity__c > ();
			deletedbtas = [Select Id From Business_Team_Activity__c Where Account__c = : acct1.id];
			/* List<Sobject> objList=new List<Sobject>();
     
        
         List<Business_Team_Activity__c> btaList1 = [Select Id, Name
                                                    From Business_Team_Activity__c
                                                    Where Account__c =:acct.id];
         List<Business_Team_Activity__c> btaList2 = [Select Id, Name
                                                    From Business_Team_Activity__c
                                                    Where Account__c =:acct1.id];
         
         
         for (Business_Team_Activity__c bta :  btaList1) {
            bta.Account__c=acct1.id;
            objList.add(bta);
         }
         for (Business_Team_Activity__c bta1 :  btaList2) {
            bta1.Account__c=acct.id;
            objList.add(bta1);
         }
        
        BatchDelete taskcontroller = new BatchDelete(btaList2,'Business_Team_Activity__c') ;
        Integer batchSize = 1;
        database.executebatch(taskcontroller , batchSize);
        
        List<Business_Team_Activity__c> deletedbtas=new List<Business_Team_Activity__c>();
        deletedbtas=[SELECT id FROM Business_Team_Activity__c WHERE Id in :btaList2];
                
        Test.stopTest();
        System.assertEquals(0,deletedbtas.size());  */
		}
	}
}