src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_for_inactive__c</fullName>
        <label>Reason for inactive</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account_A__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account A</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are some relationships which have Inactive Agencies attached to this Account. Please identify them and correct as necessary.</errorMessage>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Outgoing)</relationshipLabel>
        <relationshipName>Account_Account_rel_A</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_B__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account B</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are some relationships which have Inactive Agencies attached to this Account. Please identify them and correct as necessary.</errorMessage>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Incoming)</relationshipLabel>
        <relationshipName>Account_Account_rel_B</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Relationship_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Account_A__c</fullName>
        <formula>Relationship__r.Account_A__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account A</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_B__c</fullName>
        <formula>Relationship__r.Account_B__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account B</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status of the Relationship Contact</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Active__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationship Contacts</relationshipLabel>
        <relationshipName>Relationship_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Relationship__c</referenceTo>
        <relationshipLabel>Relationship Contacts</relationshipLabel>
        <relationshipName>Relationship_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Contact</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountDeactivateController.cls
public with sharing class AccountDeactivateController {
private ApexPages.StandardController controller;
    public Account acc;
    List<Contact> UpdatedContacts=new List<Contact>();
    List<Relationship__c> UpdatedRelations=new List<Relationship__c>();
    List<Relationship_Contact__c> UpdatedRelationshipContacts=new List<Relationship_Contact__c>();
    Public Boolean accountstatus;
    public AccountDeactivateController(ApexPages.StandardController stdcontroller) {
    //controller = stdController;
        this.acc= (Account)stdController.getRecord();
         System.debug('*******Account:'+acc);
        
        acc=[Select IsActive__c from Account Where id= :acc.id ];
        accountstatus=acc.IsActive__c;
        
        if(acc.IsActive__c=true)
        {
            acc.IsActive__c=false;
        }
        //else
        //{
        	//acc.IsActive__c=True;
        	//update acc;
        	//acc.IsActive__c=False;
        //}           
                    
    }

    
public List<Contact> AllContacts 
{
        get
        {
            if(AllContacts == null) 
            {
                
                AllContacts = [select id, Active__c, Reason_for_inactive__c from Contact c where c.AccountId = :acc.id And c.Active__c=True];
            }
            return AllContacts;
        }
        set;    
    }
    
public List<Relationship__c> AllRelations 
{
        get
        {
            if(AllRelations == null) 
            {
                
                AllRelations = [select Active__c from Relationship__c r where (r.Account_A__c= :acc.id OR r.Account_B__c = :acc.id) And r.Active__c=True];
            }
            return AllRelations;
        }
        set;    
    }    

public List<Relationship_Contact__c> AllRelationshipContacts 
{
        get
        {
            if(AllRelationshipContacts == null) 
            {
                
                AllRelationshipContacts = [select Active__c from Relationship_Contact__c d where (d.Relationship__r.Account_A__c= :acc.id OR d.Relationship__r.Account_B__c = :acc.id) And d.Active__c=True];
            }
            return AllRelationshipContacts;
        }
        set;    
    }

  public PageReference mydeactivate(){
                 
              for (Contact con : AllContacts)
              {               
                 if(AllContacts != null) 
                 {
                        con.Active__c=False;
                        con.Reason_for_inactive__c='Account was made Inactive';
                        UpdatedContacts.add(con);
                 }	
              } 
             for (Relationship_Contact__c rc : AllRelationshipContacts)
             {               
             	rc.Active__c=False;
                UpdatedRelationshipContacts.add(rc);
             }  
                                                 
             for (Relationship__c rel : AllRelations)
             {               
                 if(AllRelations != null) 
                 {
                        rel.Active__c=False;
                        UpdatedRelations.add(rel);
                 }    
             }              
            
			
            
             if(UpdatedRelationshipContacts.size() > 0)
             {
             	System.debug('*******UpdatedRelationshipContacts:'+UpdatedRelationshipContacts);
                update UpdatedRelationshipContacts;
             }                 
            
             if(UpdatedRelations.size() > 0)
             {
                update UpdatedRelations;
             }
              
              if(UpdatedContacts.size() > 0)
             {
             System.debug('*******UpdatedContacts:'+UpdatedContacts);
                update UpdatedContacts;
             }   
             if (acc != Null || accountstatus)
             {
             	update acc;
             }
             controller = new ApexPages.standardController(acc);
             return controller.view();
  }           
   
}