src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCIMailCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMailCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Industry_Minor_Category__c</fullName>
        <label>Industry Minor Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>04.01.30 - GIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.10 - BEER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.12 - LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.05 - ALCOHOL FREE BEER &amp; LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.20 - BRANDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.80 - VODKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.40 - PORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.89 - CHAMPAGNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.50 - SHERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.93 - ALCOPOPS ALCOHOL SOFT DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.25 - CIDER &amp; PERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.00 - TOBACCO ACCESSORIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.05 - LIGHTERS,MATCHES,OTHER ACCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.00 - TOBACCO RANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.10 - CIGARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.05 - CIGARETTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.99.99 - COSMETICS &amp; TOILETRIES CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.00 - PROFESSIONAL/B2B HAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.40 - SALONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.00 - MEN &amp; WOMENS FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.10 - PREMIUM MENS/WOMENS FRAG RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.05 - PREMIUM WOMENS PERFUMES/FRAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.11 - MASS MKT MENS/WOMENS FRAG RG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.00 - PERSONAL HYGIENE &amp; HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.55 - SHAVING PREPARATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.50 - SANITARY PROTECTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.65 - WET RAZORS &amp; BLADES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.91 - PERSONAL HYGIENE &amp; HEALTH GE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.05 - DENTALCARE-DENTURE CLEANERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.20 - DENTALCARE-TOOTHPASTE,POLISH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.01.00 - FIRST AID</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/classes/HoldingCompanyDetailsTest.cls
@isTest(SeeAllData = true)
private class HoldingCompanyDetailsTest {
	static{
		BookingSystemSettings__c bSS = BookingSystemSettings__c.getInstance('CCI');
		if (bSS == null) insert TestData.createBookingSystemSettings();
		if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
			insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
		}
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
	}
	
	static testmethod void HoldingAgencyDetailsTestMailInvoke() {
		//  setUpData(); 
		Account acc = TestData.buildAccount('Agency', 'Billing Agency');
		insert acc;

		Account acc2 = new Account();
		acc2.Name = 'TestAccount2';
		acc2.Type = 'Billing Agency';
		acc2.Phone = '0208426234';
		acc2.BillingStreet = 'testStreet2';
		acc2.BillingPostalCode = 'ha5 4re';
		Id agencyRecordTypeId = Account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Agency').RecordTypeId;
		acc2.RecordTypeId = agencyRecordTypeId;
		acc2.Parent = acc;
		acc2.CCIMailCustID__c = '1';
		insert acc2;
		HoldingAgencyDetails plugin = new HoldingAgencyDetails();

		Map < String, Object > inputParams = new Map < String, Object > ();
		InputParams.put('Id', acc2.id);
		InputParams.put('userType', 'Mail');
		Test.startTest();
		plugin.describe();
		Process.PluginRequest request = new Process.PluginRequest(inputParams);
		plugin.invoke(request);
		Test.stopTest();
	}

	static testmethod void HoldingCompanyDetailsTestMailInvoke() {
		//  setUpData(); 
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		acc.Industry_Minor_Category__c = '10.01.00 - FIRST AID';
		insert acc;

		Account acc2 = new Account();
		acc2.Name = 'TestAccount2';
		acc2.Type = 'Direct Advertiser';
		acc2.Phone = '0208426234';
		acc2.BillingStreet = 'testStreet2';
		acc2.BillingPostalCode = 'ha5 4re';
		Id advertiserRecordTypeId = Account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Advertiser').RecordTypeId;
		acc2.RecordTypeId = advertiserRecordTypeId;
		acc2.Industry = '04-Drinks'; // Industry only valid for Advertiser
		acc2.Parent = acc;
		acc2.CCIMailCustID__c = '1';
		insert acc2;
		HoldingCompanyDetails plugin = new HoldingCompanyDetails();

		Map < String, Object > inputParams = new Map < String, Object > ();
		InputParams.put('Id', acc2.id);
		InputParams.put('userType', 'Mail');
		Test.startTest();
		plugin.describe();
		Process.PluginRequest request = new Process.PluginRequest(inputParams);

		plugin.invoke(request);
		Test.stopTest();
	}
	static testmethod void HoldingCompanyDetailsTestMetroInvoke() {
		//  setUpData(); 
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		acc.Industry_Minor_Category__c = '10.01.00 - FIRST AID';
		insert acc;

		Account acc2 = new Account();
		acc2.Name = 'TestAccount2';
		acc2.Type = 'Direct Advertiser';
		acc2.Phone = '0208426234';
		acc2.BillingStreet = 'testStreet2';
		acc2.BillingPostalCode = 'ha5 4re';
		Id advertiserRecordTypeId = Account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Advertiser').RecordTypeId;
		acc2.RecordTypeId = advertiserRecordTypeId;
		acc2.Industry = '04-Drinks'; // Industry only valid for Advertiser
		acc2.Parent = acc;
		acc2.CCIMailCustID__c = '1';
		insert acc2;
		HoldingCompanyDetails plugin = new HoldingCompanyDetails();
		Map < String, Object > inputParams = new Map < String, Object > ();

		InputParams.put('Id', acc2.id);
		InputParams.put('userType', 'Metro');
		Test.startTest();
		Process.PluginRequest request = new Process.PluginRequest(inputParams);

		plugin.invoke(request);
		Test.stopTest();
	}
}