src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCIMailCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMailCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCIMetroCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMetroCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Industry_Minor_Category__c</fullName>
        <label>Industry Minor Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>04.01.30 - GIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.10 - BEER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.12 - LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.05 - ALCOHOL FREE BEER &amp; LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.20 - BRANDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.80 - VODKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.40 - PORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.89 - CHAMPAGNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.50 - SHERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.93 - ALCOPOPS ALCOHOL SOFT DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.25 - CIDER &amp; PERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.00 - TOBACCO ACCESSORIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.05 - LIGHTERS,MATCHES,OTHER ACCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.00 - TOBACCO RANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.10 - CIGARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.05 - CIGARETTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.99.99 - COSMETICS &amp; TOILETRIES CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.00 - PROFESSIONAL/B2B HAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.40 - SALONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.00 - MEN &amp; WOMENS FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.10 - PREMIUM MENS/WOMENS FRAG RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.05 - PREMIUM WOMENS PERFUMES/FRAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.11 - MASS MKT MENS/WOMENS FRAG RG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.00 - PERSONAL HYGIENE &amp; HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.55 - SHAVING PREPARATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.50 - SANITARY PROTECTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.65 - WET RAZORS &amp; BLADES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.91 - PERSONAL HYGIENE &amp; HEALTH GE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.05 - DENTALCARE-DENTURE CLEANERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.20 - DENTALCARE-TOOTHPASTE,POLISH</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HoldingCompanyDetails.cls
global class HoldingCompanyDetails implements Process.Plugin {
    global Process.PluginResult invoke(Process.PluginRequest request) {
        String accId = (String) request.inputParameters.get('Id');
        String userType = (String) request.inputParameters.get('userType');
        System.debug('Id' + accId + 'UserType' + userType);
        String topParentCCIId;
        String topParentAcId = Common.RootAccount(accId);
        System.debug('Top Parent Account Id' + topParentAcId);
        Account topParentAcc;
        if (!Test.isRunningTest()) {
            topParentAcc = [SELECT CCIMailCustID__c, CCIMetroCustID__c, Name, Type, Phone,
            BillingStreet, Industry_Minor_Category__c, BillingPostalCode,
            Industry, BillingState, BillingCountry
            FROM Account
            WHERE ID = : topParentAcId Limit 1];
        } else {
            topParentAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
            topParentAcc.CCIMailCustID__c = '1';
            topParentAcc.CCIMetroCustID__c = '1';
        }

        if (userType.contains('Metro Display')|| userType.contains('London Classified')) topParentCCIId = topParentAcc.CCIMetroCustID__c;
        else topParentCCIId = topParentAcc.CCIMailCustID__c;


        System.debug('topParentAcc' + topParentAcc);
        System.debug('topParentCCIId' + topParentCCIId);
        Map < String, Object > outcome = new Map < String, Object > ();
        //  outcome.put('Result', 'Success');
        // outcome.put('URL',url);
        outcome.put('TopParentCCIId', topParentCCIId);
        System.debug('Outcome is' + outcome);
        return new Process.PluginResult(outcome);
    }
    global Process.PluginDescribeResult describe() {
        Process.PluginDescribeResult result = new Process.PluginDescribeResult();
        result.description = 'This plug-in gets top parent id.';
        result.tag = 'Get TopParent';
        result.inputParameters = new List < Process.PluginDescribeResult.InputParameter > {
            new Process.PluginDescribeResult.InputParameter('Id',
            Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('userType',
            Process.PluginDescribeResult.ParameterType.STRING, true)

        };
        result.outputParameters = new List < Process.PluginDescribeResult.OutputParameter > {
            new Process.PluginDescribeResult.OutputParameter('TopParentCCIId',
            Process.PluginDescribeResult.ParameterType.STRING)

        };
        return result;
    }

}