src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Group - read/write</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Group - read only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Business_Team_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Team Activities</relationshipLabel>
        <relationshipName>Business_Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_s_Department__c</fullName>
        <defaultValue>$Setup.ConstantsH__c.Department__c</defaultValue>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Group - read/write</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group - read only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Departmental</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business Team Activity</label>
    <nameField>
        <label>Business Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Team Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/classes/AccountBTAsUtility.cls
public with sharing class AccountBTAsUtility 
{
	public static void CreateBTAs(Id accountId)
	{
		Business_Team_Activity__c[] newBTAs = new Business_Team_Activity__c[] {};
		
		Set<String> uniqueDepartments = new Set<String>();
		Set<String> uniqueNames	= new Set<String>();
		
		Map<String, String> departmentOwnerMap		= new Map<String, String>();
		Map<String, String> mapUserNameId 			= new Map<String, String>();
		
		
		ConstantsH__c[] constHlst = [select id, Name, Department__c, Acc_and_Contact_owner__c from ConstantsH__c];
		ConstantsH__c[] filteredConstH = new ConstantsH__c[] {};
			
		for(ConstantsH__c cnstH : constHlst)
		{	
			if(cnstH.Department__c != null && cnstH.Department__c != '' && cnstH.Department__c != 'None')
			{
				if(!uniqueDepartments.contains(cnstH.Department__c))
				{	 
					 uniqueDepartments.add(cnstH.Department__c);
					 filteredConstH.add(cnstH);
					 departmentOwnerMap.put(cnstH.Department__c, cnstH.Acc_and_Contact_owner__c);
					 
					 if(!uniqueNames.contains(cnstH.Acc_and_Contact_owner__c)) 
					 {
					 	uniqueNames.add(cnstH.Acc_and_Contact_owner__c);
					 }
				}
			}
		}
			
		//#
		//# Create a map where key will be user's name and value will be id of that user
		//#
		Map<Id, User> mapUser;
		if (uniqueNames.size() > 0)
		{
			mapUser = new Map<Id, User>([select id, Name from User where Name in : uniqueNames]);
			
			for(String tmpKey : mapUser.keyset())
			{
				string tmpUsername = mapUser.get(tmpKey).Name;
				
				if (!mapUserNameId.containsKey(tmpUsername))
				{
					mapUserNameId.put(tmpUsername, tmpKey);
				}
			}
		}
			
Account acc = [select name from Account where id =:accountId];

		for(ConstantsH__c constH : filteredConstH)
		{
			Business_Team_Activity__c bta = new Business_Team_Activity__c
			(
				Account__c				= accountId,
				Visibility__c	        = 'Departmental', 
				Owner_s_Department__c 	= constH.Department__c,
				//Name					= constH.Department__c,
				Name                    = acc.name + ' ('+constH.Department__c+')',
				OwnerId					= mapUserNameId.get(constH.Acc_and_Contact_owner__c)
			);
			
			newBTAs.add(bta);
		}
		
		insert newBTAs;
	}
}