src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unlocked</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinanceAccount__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Finance Accounts</relationshipLabel>
        <relationshipName>Finance_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCIMailCustomerID__c</fullName>
        <formula>Account__r.CCIMailCustID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CCIMailCustomerID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCIMetroCustomerID__c</fullName>
        <formula>Account__r.CCIMetroCustID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CCIMetroCustomerID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Finance Accounts</relationshipLabel>
        <relationshipName>Finance_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Neo_ID__c</fullName>
        <inlineHelpText>Neo ID</inlineHelpText>
        <label>Neo ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOP_ID__c</fullName>
        <label>SOP ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOP_Source__c</fullName>
        <label>SOP Source</label>
        <picklist>
            <picklistValues>
                <fullName>ADV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Logs__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Finance_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Account</label>
        <referenceTo>FinanceAccount__c</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>CCI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Integration Logs</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Finance_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Account</label>
        <referenceTo>FinanceAccount__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CCI_Group_Id__c</fullName>
        <label>CCI Group Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCI_Profile__c</fullName>
        <label>CCI Profile</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCI_User_Id__c</fullName>
        <label>CCI User Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCI_User_Password__c</fullName>
        <label>CCI User Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CCIAccountWebService.cls
global class CCIAccountWebService {

	private final Id accID;

	WebService static String createCCIAccount(String accId, boolean directOrder) {
		System.debug('Direct order on top' + directOrder);
		FinanceAccount__c acc;

		String errorResponse;
		String successResponse;
		String dbType;

		try {

			acc = [SELECT ID, Neo_ID__c, Account__r.Type, Company__r.Name, CCIMailCustomerID__c, CCIMetroCustomerID__c, SOP_ID__c, SOP_Source__c
			FROM FinanceAccount__c WHERE ID = : accID LIMIT 1];

			if ((acc.Company__r.Name).contains('Mail')) {
				dbType = 'Mail';
			} else if (acc.Company__r.Name.contains('Metro')) {
				dbType = 'Metro';
			}

			User u = Common.getUserInfo();
			System.debug('User is' + u);
			String userType = Common.getUserType(u);
			System.debug('UserType' + userType);
			System.debug('User Type is ' + userType);
			//if(String.IsBlank(u.CCI_User_Id__c)||String.IsBlank(u.CCI_Profile__c)||String.IsBlank(u.CCI_User_Password__c)||String.IsBlank(u.CCI_Group_Id__c) )
			//   errorResponse = Label.InvalidCCIUser;
			/* if (String.IsBlank(Common.sharedSecret) ){
                errorResponse = Label.Missing_Shared_Secret;
            } */
			if (userType != Common.mailUser && userType != Common.metroUser && userType != Common.londonClassified && userType != Common.systemAdministrator && userType != Common.groupClientSales && userType != Common.creditController) {
				errorResponse = Label.Invalid_Finance_User;
			} else if (acc.SOP_Source__c == 'CCI' && !String.IsBlank(acc.SOP_ID__c)) {
				errorResponse = Label.CCIAccount_already_exists;
			} else if (acc.Account__r.Type != 'Direct Advertiser' && acc.Account__r.Type != 'Billing Agency' && acc.Account__r.Type != 'Charity' && acc.Account__r.Type != 'Private Advertiser' && acc.Account__r.Type != 'Brand') {
				errorResponse = 'CCI Finance account can not be created for this account type';
			} else if (dbType == 'Mail' && String.IsBlank(acc.CCIMailCustomerID__c)) {
				errorResponse = Label.CCICustomer_does_not_exist;
			} else if (dbType == 'Metro' && String.IsBlank(acc.CCIMetroCustomerID__c)) {
				errorResponse = Label.CCICustomer_does_not_exist;
			} else {
				List < Id > accIds = new List < Id > ();
				List < FinanceAccount__c > accs = new List < FinanceAccount__c > ();
				// accIds.add(acc.Id);
				accs.add(acc);
				// Map <ID, String> mResponse = CCIFinanceAccountManager.createCCIAccount(accIds,u,directOrder);
				Map < String, String > mResponse = CCIFinanceAccountManager.createCCIAccount(accs, u, directOrder);
				if (directorder) successResponse = mResponse.get(acc.ID);
				else errorResponse = mResponse.get(acc.ID);
			}
		} Catch(Exception e) {
			// pr = new Pagereference('/' + acc.ID);
			//  ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR,Label.CCI_Exception));
		}

		System.debug('Error is' + errorResponse);
		if (String.isBlank(errorResponse)) {
			Common.addChatterFeedToObject((Id) accId, 'Finance Account has been successfully integrated with CCI Mail.');
			Integration_Logs__c intL = new Integration_Logs__c(Source__c = 'CCI', Finance_Account__c = (Id) accId, Status__c = 'Success',
			Description__c = 'Finance Account has been successfully integrated with CCI.');
			insert intL;
		}
		System.debug('Direct order on bottom' + directOrder);
		if (directOrder) return successResponse;
		return errorResponse;
	}

	@future(callout = true)
	WebService static void createCCIAccountFromOrder(String accId) {

		FinanceAccount__c acc;

		String errorResponse;
		String successResponse;
		String dbType;



		try {

			acc = [SELECT ID, Account__r.Type, Neo_ID__c, Company__r.Name, CCIMailCustomerID__c, CCIMetroCustomerID__c, SOP_ID__c, SOP_Source__c
			FROM FinanceAccount__c
			WHERE ID = : accID LIMIT 1];

			if ((acc.Company__r.Name).contains('Mail')) {
				dbType = 'Mail';
			} else if (acc.Company__r.Name.contains('Metro')) {
				dbType = 'Metro';
			}


			User u = Common.getUserInfo();
			System.debug('User is' + u);
			String userType = Common.getUserType(u);
			System.debug('UserType' + userType);
			System.debug('User Type is ' + userType);
			//if(String.IsBlank(u.CCI_User_Id__c)||String.isBlank(u.CCI_Profile__c)||String.IsBlank(u.CCI_User_Password__c)||String.IsBlank(u.CCI_Group_Id__c))
			//   errorResponse = Label.InvalidCCIUser;
			/*  if (String.IsBlank(Common.sharedSecret) )
            {
                errorResponse = Label.Missing_Shared_Secret;
            }*/
			if (userType != Common.mailUser && userType != Common.metroUser && userType != Common.londonClassified && userType != Common.systemAdministrator && userType != Common.groupClientSales && userType != Common.creditController) {
				errorResponse = Label.Invalid_Finance_User;
			} else if (acc.SOP_Source__c == 'CCI' && acc.SOP_ID__c != null && acc.SOP_ID__c != '') {
				errorResponse = Label.CCIAccount_already_exists;


			} else if (acc.Account__r.Type != 'Direct Advertiser' && acc.Account__r.Type != 'Private Advertiser' && acc.Account__r.Type != 'Charity' && acc.Account__r.Type != 'DMGT Group' && acc.Account__r.Type != 'Billing Agency' && acc.Account__r.Type != 'Brand') {
				errorResponse = 'CCI Finance account can not be created for this user';
			} else if (dbType == 'Mail' && String.IsBlank(acc.CCIMailCustomerID__c)) {
				errorResponse = Label.CCICustomer_does_not_exist;
			} else if (dbType == 'Metro' && String.IsBlank(acc.CCIMetroCustomerID__c)) {
				errorResponse = Label.CCICustomer_does_not_exist;
			} else {
				List < Id > accIds = new List < Id > ();
				List < FinanceAccount__c > accs = new List < FinanceAccount__c > ();
				//                 accIds.add(acc.Id);
				accs.add(acc);
				// Map <ID, String> mResponse = CCIFinanceAccountManager.createCCIAccount(accIds,u,true);
				Map < String, String > mResponse = CCIFinanceAccountManager.createCCIAccount(accs, u, true);

				successResponse = mResponse.get(accID);

			}



		} Catch(Exception e) {
			// pr = new Pagereference('/' + acc.ID);
			//  ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR,Label.CCI_Exception));

		}

		System.debug('Error is' + errorResponse);
		if (String.isBlank(errorResponse) && successResponse != null) {
			Common.addChatterFeedToObject((Id) accId, 'Finance Account has been successfully integrated with CCI Mail.');
			Integration_Logs__c intL = new Integration_Logs__c(
			Source__c = 'CCI',
			Finance_Account__c = (Id) accId, Status__c = 'Success',
			Description__c = 'Finance Account has been successfully integrated with CCI.');
			insert intL;

		}


	}
	
	@future(callout = true)
	WebService static void createFutureCCIAccount(String accId, boolean directOrder)
	{
		createNonFutureCCIAccount(accId, directOrder);
	}
	
	public static void createNonFutureCCIAccount(String accId, boolean directOrder) {
		System.debug('Direct order on top' + directOrder);
		FinanceAccount__c acc;

		String errorResponse;
		String successResponse;
		String dbType;



		try {

			acc = [SELECT ID, Neo_ID__c, Account__r.Type, Company__r.Name, CCIMailCustomerID__c, CCIMetroCustomerID__c, SOP_ID__c, SOP_Source__c
			FROM FinanceAccount__c
			WHERE ID = : accID LIMIT 1];

			if ((acc.Company__r.Name).contains('Mail')) {
				dbType = 'Mail';
			} else if (acc.Company__r.Name.contains('Metro')) {
				dbType = 'Metro';
			}


			User u = Common.getUserInfo();
			System.debug('User is' + u);
			String userType = Common.getUserType(u);
			System.debug('UserType' + userType);
			System.debug('User Type is ' + userType);
			//if(String.IsBlank(u.CCI_User_Id__c)||String.IsBlank(u.CCI_Profile__c)||String.IsBlank(u.CCI_User_Password__c)||String.IsBlank(u.CCI_Group_Id__c))
			//   errorResponse = Label.InvalidCCIUser;
			/*  if (String.IsBlank(Common.sharedSecret) )
            {
                errorResponse = Label.Missing_Shared_Secret;
            }
            else */
			if (userType != Common.mailUser && userType != Common.metroUser && userType != Common.londonClassified && userType != Common.systemAdministrator && userType != Common.groupClientSales && userType != Common.creditController) {
				errorResponse = Label.Invalid_Finance_User;
			} else if (acc.SOP_Source__c == 'CCI' && String.IsBlank(acc.SOP_ID__c)) {
				errorResponse = Label.CCIAccount_already_exists;


			} else if (acc.Account__r.Type != 'Direct Advertiser' && acc.Account__r.Type != 'Billing Agency' && acc.Account__r.Type != 'Charity' && acc.Account__r.Type != 'Private Advertiser' && acc.Account__r.Type != 'Brand') {
				errorResponse = 'CCI Finance account can not be created for this user';
			} else if (dbType == 'Mail' && String.IsBlank(acc.CCIMailCustomerID__c)) {
				errorResponse = Label.CCICustomer_does_not_exist;
			} else if (dbType == 'Metro' && String.IsBlank(acc.CCIMetroCustomerID__c)) {
				errorResponse = Label.CCICustomer_does_not_exist;
			} else {
				List < Id > accIds = new List < Id > ();
				List < FinanceAccount__c > accs = new List < FinanceAccount__c > ();
				//                 accIds.add(acc.Id);
				accs.add(acc);
				//  Map <ID, String> mResponse = CCIFinanceAccountManager.createCCIAccount(accIds,u,directOrder);
				Map < String, String > mResponse = CCIFinanceAccountManager.createCCIAccount(accs, u, directOrder);
				if (directorder) successResponse = mResponse.get(accID);
				else errorResponse = mResponse.get(accID);
			}



		} Catch(Exception e) {
			// pr = new Pagereference('/' + acc.ID);
			//  ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR,Label.CCI_Exception));

		}

		System.debug('Error is' + errorResponse);
		if (String.isBlank(errorResponse)) {
			Common.addChatterFeedToObject((Id) accId, 'Finance Account has been successfully integrated with CCI Mail.');
			Integration_Logs__c intL = new Integration_Logs__c(
			Source__c = 'CCI',
			Finance_Account__c = (Id) accId, Status__c = 'Success',
			Description__c = 'Finance Account has been successfully integrated with CCI.');
			insert intL;

		}
		System.debug('Direct order on bottom' + directOrder);

	}



}