src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Classified_Minor_Category__c</fullName>
        <label>Classified - Minor Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accessories &amp; Soft Furnishings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia &amp; New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balearics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blackpool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bournemouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building &amp; Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Businesses For Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire &amp; Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clerical &amp; Secretarial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conservatories, Lofts &amp; Extensions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts &amp; Tenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cornwall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotswolds</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CustomerRef1__c</fullName>
        <label>CCI Metro Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef2__c</fullName>
        <label>AdVance Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef3__c</fullName>
        <label>CCI Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef4__c</fullName>
        <label>Operative Cust Ref</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Revenue_Last_Month__c</fullName>
        <label>Hierarchy Revenue Last Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Revenue_Last_Quarter__c</fullName>
        <label>Hierarchy Revenue Last Quarter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Revenue_Last_Year__c</fullName>
        <label>Hierarchy Revenue Last Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IndClassLvl1__c</fullName>
        <label>Classified - Main Category</label>
        <picklist>
            <picklistValues>
                <fullName>Business &amp; Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &amp; Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homes &amp; Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noticeboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal &amp; Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IndClassLvl2__c</fullName>
        <label>Classified - Sub Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Airlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airport Parking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apprenticeships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (General)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Motors)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Property)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;B/Guest Houses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bars/Clubs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battlefields</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Births, Deaths and Marriages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business to Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping and Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravans &amp; Motorhomes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars wanted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinemas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City Living</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Trials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collectables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complementary Therapies &amp; Wellbeing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Revenue_Last_Month__c</fullName>
        <label>Revenue Last Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue_Last_Quarter__c</fullName>
        <label>Revenue Last Quarter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue_Last_Year__c</fullName>
        <label>Revenue Last Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <description>This field will be used to determine the status of the Account</description>
        <label>Review Status</label>
        <picklist>
            <picklistValues>
                <fullName>Needs Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReCheck</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Mappings</relationshipLabel>
        <relationshipName>Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Mapping</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/SalesRevenue__c.object
<CustomObject>
    <description>This Object has been created as part of the Quick Wins Project. It will be populated from an external system.</description>
    <fields>
        <fullName>AdvertiserID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AdvertiserID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesRevenue</relationshipLabel>
        <relationshipName>SalesRevenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrandID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BrandID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesRevenue (BrandID)</relationshipLabel>
        <relationshipName>SalesRevenue1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_AgencyID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice_AgencyID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesRevenue (Invoice_AgencyID)</relationshipLabel>
        <relationshipName>SalesRevenue2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Amount__c</fullName>
        <label>Revenue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SalesRevenue</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>SalesRevenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesRevenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchUpdateTotalRevenue.cls
global with sharing class BatchUpdateTotalRevenue implements Database.Batchable < sObject > , Database.Stateful {

	global BatchUpdateTotalRevenue() {

	}

	global Database.querylocator start(Database.BatchableContext ctx) {
		return Database.getQueryLocator(
		[
		Select
		BrandID__c,
		AdvertiserID__c,
		Invoice_AgencyID__c,
		Revenue_Amount__c
		From SalesRevenue__c
		// Where   (BrandID__c != Null Or AdvertiserID__c != Null Or Invoice_AgencyID__c != Null)
		Where(BrandID__r.ParentID != Null Or AdvertiserID__r.ParentID != Null Or Invoice_AgencyID__r.ParentId != Null)]);
	}

	global void execute(Database.BatchableContext BC, List < sObject > scope) {
		List < SalesRevenue__c > srList = scope;

		Set < Id > accSet = new Set < Id > ();
		for (SalesRevenue__c s: srList) {
			if (s.BrandID__c != null) {
				accSet.add(s.BrandID__c);
			}
			if (s.AdvertiserID__c != null) {
				accSet.add(s.AdvertiserID__c);
			}
			if (s.Invoice_AgencyID__c != null) {
				accSet.add(s.Invoice_AgencyID__c);
			}
		}

		List < AggregateResult > accountList = [
		Select ParentId, Sum(Revenue_Last_Month__c), Sum(Revenue_Last_Quarter__c), Sum(Revenue_Last_Year__c)
		From Account
		Where Id IN: accSet
		And ParentId != null
		Group By ParentId];

		List < Account > accountsToUpdateList = new List < Account > ();
		for (AggregateResult ag: accountList) {
			accountsToUpdateList.add(new Account(Id = (Id) ag.get('ParentId'),
			Hierarchy_Revenue_Last_Month__c = (Decimal) ag.get('expr0'),
			Hierarchy_Revenue_Last_Quarter__c = (Decimal) ag.get('expr1'),
			Hierarchy_Revenue_Last_Year__c = (Decimal) ag.get('expr2')));
		}
		System.debug('accountsToUpdateList:' + accountsToUpdateList);
		update accountsToUpdateList;

	}

	global void finish(Database.BatchableContext ctx) {

	}



	// Test Method
	private static TestMethod void testBatchAccountRevenueUpdate() {
		Test.startTest();
		User testUser = [
		select name, email, ProfileId, Profile.Name
		from User
		where isActive = true
		and Profile.Name = 'System Administrator'
		limit 1];

		String testProfileId = [select id
		from Profile
		limit 1].id;

		ConstantsH__c newConstH = new ConstantsH__c(
		Acc_and_Contact_owner__c = testUser.Name,
		Department__c = 'Test Department 1',
		IsManager__c = false,
		//Price_Book__c             = testPB.Name,
		SetupOwnerId = testUser.ProfileId);
		insert newConstH;

		insert TestData.createBookingSystemSettings();
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
		insert TestData.createCountryCodeSettings();
		insert TestData.createCountriesList();

		Map < String, RecordTypeInfo > oppRecTypesByName = Account.SObjectType.getDescribe().getRecordTypeInfosByName();
		System.debug('oppRecTypesByName:' + oppRecTypesByName);


		Account agency = new Account(
		Name = 'TestAgency',
		AccountNumber = 'ABC123456',
		Type = 'Agency',
		BillingStreet = 'Test Billing Street',
		BillingState = 'Test Billing State',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'London',
		Industry = 'Finance',
		IndClassLvl1__c = 'Finance',
		IndClassLvl2__c = 'Finance',
		Classified_Minor_Category__c = 'Finance',
		CustomerRef1__c = '12345',
		CustomerRef2__c = '23456',
		CustomerRef3__c = '34567',
		CustomerRef4__c = 'TestA',
		RecordTypeId = oppRecTypesByName.get('Agency').RecordTypeId,
		Review_Status__c = 'Reviewed');
		insert agency;

		Account acct = new Account(
		Name = 'TestAccount',
		AccountNumber = 'ABC123456',
		Type = 'Client',
		BillingStreet = 'Test Billing Street',
		BillingState = 'Test Billing State',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'London',
		Industry = 'Finance',
		IndClassLvl1__c = 'Finance',
		IndClassLvl2__c = 'Finance',
		Classified_Minor_Category__c = 'Finance',
		CustomerRef1__c = '12345',
		CustomerRef2__c = '23456',
		CustomerRef3__c = '34567',
		CustomerRef4__c = 'TestA',
		RecordTypeId = oppRecTypesByName.get('Advertiser').RecordTypeId,
		Review_Status__c = 'Reviewed');
		insert acct;

		Account brand = new Account(
		Name = 'TestBrand',
		ParentId = acct.Id,
		AccountNumber = 'ABC123456',
		Type = 'Brand',
		BillingStreet = 'Test Billing Street',
		BillingState = 'Test Billing State',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'London',
		Industry = 'Finance',
		IndClassLvl1__c = 'Finance',
		IndClassLvl2__c = 'Finance',
		Classified_Minor_Category__c = 'Finance',
		CustomerRef1__c = '12345',
		CustomerRef2__c = '23456',
		CustomerRef3__c = '34567',
		CustomerRef4__c = 'TestA',
		RecordTypeId = oppRecTypesByName.get('Advertiser').RecordTypeId,
		Review_Status__c = 'Reviewed');
		insert brand;


		List < Account_Mapping__c > accMapList = new List < Account_Mapping__c > ();
		accMapList.add(new Account_Mapping__c(
		Account__c = acct.Id,
		Source_System__c = 'CCI Metro',
		Source_Key__c = '23747',
		Active__c = True));
		accMapList.add(new Account_Mapping__c(
		Account__c = acct.Id,
		Source_System__c = 'CCI Mail',
		Source_Key__c = '28462',
		Active__c = True));
		accMapList.add(new Account_Mapping__c(
		Account__c = acct.Id,
		Source_System__c = 'Advance',
		Source_Key__c = '2347239',
		Active__c = True));

		insert accMapList;

		List < SalesRevenue__c > salesRevList = new List < SalesRevenue__c > ();
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Metro', Department__c = 'London Classified', AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-1), Revenue_Amount__c = 1000));
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Metro', Department__c = 'Metro', AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-1), Revenue_Amount__c = 3000));

		salesRevList.add(new SalesRevenue__c(Publication__c = 'You', Department__c = 'Daily Mail', BrandID__c = brand.ID, AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-1), Revenue_Amount__c = 1500));
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Daily Mail', Department__c = 'Daily Mail', BrandID__c = brand.ID, AdvertiserID__c = acct.ID, Period_End_Date__c = Date.today().addMonths(-1), Revenue_Amount__c = 4000));

		salesRevList.add(new SalesRevenue__c(Publication__c = 'You', Department__c = 'Daily Mail', Invoice_AgencyID__c = agency.ID, Period_End_Date__c = Date.today().addMonths(-1), Revenue_Amount__c = 7000));
		salesRevList.add(new SalesRevenue__c(Publication__c = 'Daily Mail', Department__c = 'Daily Mail', Invoice_AgencyID__c = agency.ID, Period_End_Date__c = Date.today().addMonths(-1), Revenue_Amount__c = 10000));


		insert salesRevList;

		List < Account > simAccount = new List < Account > ();

		simAccount.add(new Account(Id = brand.Id, Revenue_Last_Month__c = 5500, Revenue_Last_Quarter__c = 5500, Revenue_Last_Year__c = 5500));
		simAccount.add(new Account(Id = acct.Id, Revenue_Last_Month__c = 4000, Revenue_Last_Quarter__c = 4000, Revenue_Last_Year__c = 4000));
		simAccount.add(new Account(Id = agency.Id, Revenue_Last_Month__c = 17000, Revenue_Last_Quarter__c = 17000, Revenue_Last_Year__c = 17000));
		update simAccount;

		BatchUpdateTotalRevenue batchrun = new BatchUpdateTotalRevenue();
		Integer batchSize = 6;
		database.executebatch(batchrun, batchSize);
		Test.stopTest();

		Set < Id > accountSet = new Set < Id > ();
		accountSet.add(brand.Id);
		accountSet.add(acct.Id);
		accountSet.add(agency.Id);

		Map < Id, Account > accMap = new Map < Id, Account > (
		[Select
		Hierarchy_Revenue_Last_Month__c,
		Hierarchy_Revenue_Last_Quarter__c,
		Hierarchy_Revenue_Last_Year__c,
		Total_Revenue_Last_Month__c,
		Total_Revenue_Last_Quarter__c,
		Total_Revenue_Last_Year__c
		From Account
		Where Id IN: accountSet]);

		System.assertEquals(5500.00, accMap.get(acct.ID).Hierarchy_Revenue_Last_Month__c);
		System.assertEquals(9500.00, accMap.get(acct.ID).Total_Revenue_Last_Month__c);

	}

}