src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Mappings</relationshipLabel>
        <relationshipName>Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Key__c</fullName>
        <label>Customer Ref</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operative One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nielsen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDM Origins</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Mapping</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Agency account type should be Agency or Direct Advertiser and it needs to be Active.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Direct Advertiser,Billing Agency,Charity,Private Advertiser,Brand, Booking Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pitches (Agency)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AutoTaskWonCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoTaskWonCreated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Insertion_Date__c</fullName>
        <label>MigLast Insertion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <label>Close Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Activity already booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity discussed as value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business titles only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign date moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Date moved Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did not use online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn’t Use Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editorial/Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entered in Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free/House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea Not Suited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to A&amp;N Media Brand Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to DR/Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mids only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed a tactical opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed Campaign Targets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Creative Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Final Decision Before Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not core to activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed to classified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pops only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quals only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong target audience</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product (Account)</relationshipLabel>
        <relationshipName>Opportunity_Product1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomerRef__c</fullName>
        <label>CustomerRef</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Insertion_Date__c</fullName>
        <label>Last Insertion Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CustomerRef__c</fullName>
        <label>CustomerRef</label>
        <picklist>
            <picklistValues>
                <fullName>CustomerRef1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>false</active>
        <description>DO NOT ACTIVATE</description>
        <label>Test</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AutoCreateTaskOnOpportunity_Test.cls
@isTest(SeeAllData = true)
private class AutoCreateTaskOnOpportunity_Test {
    //GB-106 : Collaboration
    static{
        BookingSystemSettings__c bSS = BookingSystemSettings__c.getInstance('CCI');
        if (bSS == null) insert TestData.createBookingSystemSettings();
        if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
            insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
        }
        insert TestData.buildCompany();
        insert TestData.buildMetroCompany();
        insert TestData.buildCompany();
        insert TestData.buildMetroCompany();
        
        Product2 tmpproduct3 = new Product2();
        tmpproduct3.IsActive = true;
        tmpproduct3.Family = 'Test Family3';
        tmpproduct3.Name = 'Test product3';
        tmpproduct3.CustomerRef__c = 'CustomerRef3';
        tmpproduct3.CurrencyIsoCode = 'GBP';
        insert tmpproduct3;

    }
    static testMethod void testOppTask() {
        Map < string, RecordTypeInfo > oppRecTypesByName = Opportunity.SObjectType.getDescribe().getRecordTypeInfosByName();
        Id oppRecordTypeId = oppRecTypesByName.get('Pitch').RecordTypeId;




        List < RecordType > agencyRecType = [
        Select
        Name
        From RecordType
        Where SObjectType = 'Account'
        And DeveloperName = 'Agency'];

        List < RecordType > accRecType = [
        Select
        Name
        From RecordType
        Where SObjectType = 'Account'
        And DeveloperName = 'Advertiser'];



        Pricebook2 testPB = [Select
        name
        From Pricebook2
        Where isActive = true
        limit 1];



PricebookEntry priceBookEntry = [
        select id, name, Product2Id
        from PricebookEntry
        where Product2.CustomerRef__c = 'CustomerRef3'
        and CurrencyIsoCode = 'GBP'
        and IsActive = true and (Not name like '%Provisional%') 
        limit 1];
        System.debug('ProcebookEntry is' + priceBookEntry);
        User mailClassTestUser = [
        select name, email, ProfileId, Profile.Name
        from User
        where isActive = true
        and Profile.Name = 'System Administrator'
        limit 1];
        //'Mail Classified Manager
        //'Mail Classified User
        User mailClassTestUser1 = [
        select name, email, ProfileId, Profile.Name
        from User
        where isActive = true
        and Profile.Name = 'Mail Classified User'
        limit 1];
        
        System.debug('mailClassTestUser:' + mailClassTestUser);
        Account newAccount = new Account();
        Contact newContact = new Contact();

        newAccount = new Account(
        name = 'Test Account1',
        RecordTypeId = accRecType[0].Id,
        Type = 'Direct Advertiser',
        BillingStreet = 'Westminster Rd',
        BillingPostalCode = 'SW1 2AU',
        BillingCountry = 'United Kingdom',
        Industry = 'Display',
        isActive__c = True,
        Phone = '01236554482');
        insert newAccount;


        Account_mapping__c mapping1 = new Account_mapping__c(
        Source_system__c = 'CCI Metro',
        Account__c = newAccount.Id,
        Active__c = true,
        Source_Key__c = '98756254');
        insert mapping1;

        Account_mapping__c mapping2 = new Account_mapping__c(
        Source_system__c = 'CCI Mail',
        Account__c = newAccount.Id,
        Active__c = true,
        Source_Key__c = '23456');
        insert mapping2;

        Account newAgency = new Account(
        Name = 'Test Account2',
        AccountNumber = 'ABC1234562',
        RecordTypeId = agencyRecType[0].Id,
        BillingStreet = 'Street',
        BillingState = 'TestState',
        BillingPostalCode = 'A111AA',
        BillingCountry = 'United Kingdom',
        BillingCity = 'City',
        Phone = '01236547891');
        insert newAgency;

       /* Account_mapping__c mapping3 = new Account_mapping__c(
        Source_system__c = 'CCI Metro',
        Account__c = newAgency.Id,
        Active__c = true,
        Source_Key__c = '92364723');
        insert mapping3;

        Account_mapping__c mapping4 = new Account_mapping__c(
        Source_system__c = 'CCI Mail',
        Account__c = newAgency.Id,
        Active__c = true,
        Source_Key__c = '92364726');
        insert mapping4;*/

        Contact cnt1 = new Contact();
        cnt1.AccountId = newAccount.Id;
        cnt1.Active__c = True;
        cnt1.LastName = 'Test Last Name';
        cnt1.FirstName = 'Test First Name';
        cnt1.MailingCity = 'Test Mailing City';
        cnt1.MailingCountry = 'Test Mailing Country';
        cnt1.MailingPostalCode = 'TestMPC';
        cnt1.MailingState = 'Test Mailing State';
        cnt1.MailingStreet = 'Test Mailing Street';
        cnt1.MailingCountry = 'United Kingdom';
        insert cnt1;
        test.starttest();
        System.runAs(mailClassTestUser) {

            Opportunity op = new Opportunity(
            Name = 'Test MailClass1',
            AccountId = newAccount.Id,
            //Agency__c=newAgency.id,
            RecordTypeId = oppRecordTypeId,
            StageName = 'Preparation',
            CloseDate = Date.today(),
            Type = 'Proactive',
            OwnerId = mailClassTestUser1.id,
            CurrencyIsoCode = 'GBP');
            insert op;

            OpportunityContactRole op1ContactRole = new OpportunityContactRole(OpportunityId = op.Id, Role = 'Agency Planning', ContactId = cnt1.Id, IsPrimary = True);
            insert op1ContactRole;


            /*Opportunity op1 = new Opportunity(
                                            Name='Test MailClass2',
                                            AccountId=newAccount.Id, 
                                            Agency__c=newAgency.id,
                                            RecordTypeId=oppRecordTypeId,
                                            StageName='Brief',
                                            CloseDate=Date.today(),
                                            Type='Proactive',
                                            OwnerId = mailClassTestUser.id);
            insert op1;

            OpportunityContactRole opContactRole = new OpportunityContactRole(OpportunityId=op1.Id, Role='Agency Planning', ContactId=cnt1.Id, IsPrimary=True);
            insert opContactRole;
         */

            OpportunityLineItem newline1 = new OpportunityLineItem();

            newline1.OpportunityId = op.id;
            newline1.ServiceDate = date.today() + 5;
            newline1.Description = 'Test Description';
            newline1.UnitPrice = 1000;
            newline1.Quantity = 1;
            newline1.PriceBookEntryId = priceBookEntry.id;
            newline1.Last_Insertion_Date__c = System.today() + 6;


            insert newline1;

            /*           OpportunityLineItem newline=new OpportunityLineItem();
                
                newline.OpportunityId= op1.id;
                newline.ServiceDate = date.today() + 5;
                newline.Description      = 'Test Description';
                newline.UnitPrice        = 1000;
                newline.Quantity=1;
                newline.PriceBookEntryId=priceBookEntry.id;
                
                
               insert newline;*/
            List < Opportunity > newopps = new List < Opportunity > ();
            List < OpportunityLineItem > newlines = new List < OpportunityLineItem > ();

            newopps.add(op);
            //newopps.add(op1);

            //Auto-Task on Opportunity
            if (mailClassTestUser.Profile.Name.contains('Mail Classified') || mailClassTestUser.Profile.Name.contains('System Administrator')) {
                List < Opportunity > newopps1 = new List < Opportunity > ();
                List < OpportunityContactRole > newocrs = new List < OpportunityContactRole > ();
                //newopps1.add(op1);
                newocrs.add(op1ContactRole);
                newlines.add(newline1);
                //newlines.add(newline1);
                map < Id, List < OpportunityContactRole >> newocrsmap = new map < Id, List < OpportunityContactRole >> ();
                map < Id, List < OpportunityLineItem >> newopplinesmap = new map < Id, List < OpportunityLineItem >> ();

                newocrsmap.put(op.id, newocrs);
                newopplinesmap.put(op.id, newlines);

                AutoCreateTaskOnOpportunity.createTasks(newopps, newopplinesmap, newocrsmap);
            }



            //newopps.add(op1);
            //system.runAs(tmpUser)
            //test.startTest();     
            if (newopps.size() > 0) {
                for (Opportunity opp1: newopps) {
                    opp1.Stagename = 'Closed Won';
                    //opp1.Loss_Reason__c='Did not use online';
                    opp1.AutoTaskWonCreated__c = False;
                    //AutoCreateTaskOnOpportunity.createClosedOppTasks(newopps1, newopplinesmap, newocrsmap);
                }
                update newopps;
            }



            //System.assertEquals(1, newtasksToUpdate.size());
            //System.assertEquals(2, newtasksToUpdate.size());    

            test.stopTest();
        }
    }
//////////////////////////////////////////////////////////////////////////////////////////////////////////
    static testMethod void testOppTask1() {
        Map < string, RecordTypeInfo > oppRecTypesByName = Opportunity.SObjectType.getDescribe().getRecordTypeInfosByName();
        Id oppRecordTypeId = oppRecTypesByName.get('Pitch').RecordTypeId;




        List < RecordType > agencyRecType = [
        Select
        Name
        From RecordType
        Where SObjectType = 'Account'
        And DeveloperName = 'Agency'];

        List < RecordType > accRecType = [
        Select
        Name
        From RecordType
        Where SObjectType = 'Account'
        And DeveloperName = 'Advertiser'];



        Pricebook2 testPB = [Select
        name
        From Pricebook2
        Where isActive = true
        limit 1];



PricebookEntry priceBookEntry = [
        select id, name, Product2Id
        from PricebookEntry
        where Product2.CustomerRef__c = 'CustomerRef3'
        and CurrencyIsoCode = 'GBP'
        and IsActive = true and (Not name like '%Provisional%') 
        limit 1];
        System.debug('ProcebookEntry is' + priceBookEntry);
        
        User mailClassTestUser = [
        select name, email, ProfileId, Profile.Name
        from User
        where isActive = true
        and Profile.Name = 'System Administrator'
        limit 1];
        
        User mailClassTestUser1 = [
        select name, email, ProfileId, Profile.Name
        from User
        where isActive = true
        and Profile.Name Like 'Mail Display Manager'
        limit 1];
        
        System.debug('mailClassTestUser:' + mailClassTestUser);
        Account newAccount = new Account();
        Contact newContact = new Contact();

        newAccount = new Account(
        name = 'Test Account1',
        RecordTypeId = accRecType[0].Id,
        Type = 'Direct Advertiser',
        BillingStreet = 'Westminster Rd',
        BillingPostalCode = 'SW1 2AU',
        BillingCountry = 'United Kingdom',
        Industry = 'Display',
        isActive__c = True,
        Phone = '01236554482');
        insert newAccount;


        Account_mapping__c mapping1 = new Account_mapping__c(
        Source_system__c = 'CCI Metro',
        Account__c = newAccount.Id,
        Active__c = true,
        Source_Key__c = '98756254');
        insert mapping1;

        Account_mapping__c mapping2 = new Account_mapping__c(
        Source_system__c = 'CCI Mail',
        Account__c = newAccount.Id,
        Active__c = true,
        Source_Key__c = '23456');
        insert mapping2;

        Account newAgency = new Account(
        Name = 'Test Account2',
        AccountNumber = 'ABC1234562',
        RecordTypeId = agencyRecType[0].Id,
        BillingStreet = 'Street',
        BillingState = 'TestState',
        BillingPostalCode = 'A111AA',
        BillingCountry = 'United Kingdom',
        BillingCity = 'City',
        Phone = '01236547891');
        insert newAgency;

       /* Account_mapping__c mapping3 = new Account_mapping__c(
        Source_system__c = 'CCI Metro',
        Account__c = newAgency.Id,
        Active__c = true,
        Source_Key__c = '92364723');
        insert mapping3;

        Account_mapping__c mapping4 = new Account_mapping__c(
        Source_system__c = 'CCI Mail',
        Account__c = newAgency.Id,
        Active__c = true,
        Source_Key__c = '92364726');
        insert mapping4;*/

        Contact cnt1 = new Contact();
        cnt1.AccountId = newAccount.Id;
        cnt1.Active__c = True;
        cnt1.LastName = 'Test Last Name';
        cnt1.FirstName = 'Test First Name';
        cnt1.MailingCity = 'Test Mailing City';
        cnt1.MailingCountry = 'Test Mailing Country';
        cnt1.MailingPostalCode = 'TestMPC';
        cnt1.MailingState = 'Test Mailing State';
        cnt1.MailingStreet = 'Test Mailing Street';
        cnt1.MailingCountry = 'United Kingdom';
        insert cnt1;
        test.starttest();
        System.runAs(mailClassTestUser) {

            Opportunity op = new Opportunity(
            Name = 'Test MailClass1',
            AccountId = newAccount.Id,
            //Agency__c=newAgency.id,
            RecordTypeId = oppRecordTypeId,
            StageName = 'Preparation',
            CloseDate = Date.today(),
            Type = 'Proactive',
            OwnerId = mailClassTestUser.id,
            CurrencyIsoCode = 'GBP');
            insert op;

            OpportunityContactRole op1ContactRole = new OpportunityContactRole(OpportunityId = op.Id, Role = 'Agency Planning', ContactId = cnt1.Id, IsPrimary = True);
            insert op1ContactRole;


            /*Opportunity op1 = new Opportunity(
                                            Name='Test MailClass2',
                                            AccountId=newAccount.Id, 
                                            Agency__c=newAgency.id,
                                            RecordTypeId=oppRecordTypeId,
                                            StageName='Brief',
                                            CloseDate=Date.today(),
                                            Type='Proactive',
                                            OwnerId = mailClassTestUser.id);
            insert op1;

            OpportunityContactRole opContactRole = new OpportunityContactRole(OpportunityId=op1.Id, Role='Agency Planning', ContactId=cnt1.Id, IsPrimary=True);
            insert opContactRole;
         */

            OpportunityLineItem newline1 = new OpportunityLineItem();

            newline1.OpportunityId = op.id;
            newline1.ServiceDate = date.today() + 5;
            newline1.Description = 'Test Description';
            newline1.UnitPrice = 1000;
            newline1.Quantity = 1;
            newline1.PriceBookEntryId = priceBookEntry.id;
            newline1.Last_Insertion_Date__c = System.today() + 6;


            insert newline1;

            /*           OpportunityLineItem newline=new OpportunityLineItem();
                
                newline.OpportunityId= op1.id;
                newline.ServiceDate = date.today() + 5;
                newline.Description      = 'Test Description';
                newline.UnitPrice        = 1000;
                newline.Quantity=1;
                newline.PriceBookEntryId=priceBookEntry.id;
                
                
               insert newline;*/
            List < Opportunity > newopps = new List < Opportunity > ();
            List < OpportunityLineItem > newlines = new List < OpportunityLineItem > ();

            newopps.add(op);
            //newopps.add(op1);

            //Auto-Task on Opportunity
            if (mailClassTestUser.Profile.Name.contains('Mail Classified') || mailClassTestUser.Profile.Name.contains('System Administrator')) {
                List < Opportunity > newopps1 = new List < Opportunity > ();
                List < OpportunityContactRole > newocrs = new List < OpportunityContactRole > ();
                //newopps1.add(op1);
                newocrs.add(op1ContactRole);
                newlines.add(newline1);
                //newlines.add(newline1);
                map < Id, List < OpportunityContactRole >> newocrsmap = new map < Id, List < OpportunityContactRole >> ();
                map < Id, List < OpportunityLineItem >> newopplinesmap = new map < Id, List < OpportunityLineItem >> ();

                newocrsmap.put(op.id, newocrs);
                newopplinesmap.put(op.id, newlines);

                AutoCreateTaskOnOpportunity.createTasks(newopps, newopplinesmap, newocrsmap);
            }



            //newopps.add(op1);
            //system.runAs(tmpUser)
            //test.startTest();     
            if (newopps.size() > 0) {
                for (Opportunity opp1: newopps) {
                    opp1.Stagename = 'Closed Won';
                    //opp1.Loss_Reason__c='Did not use online';
                    opp1.AutoTaskWonCreated__c = False;
                    //AutoCreateTaskOnOpportunity.createClosedOppTasks(newopps1, newopplinesmap, newocrsmap);
                }
                update newopps;
            }



            //System.assertEquals(1, newtasksToUpdate.size());
            //System.assertEquals(2, newtasksToUpdate.size());    

            test.stopTest();
        }
    }
//////////////////////////////////////////////////////////////////////////////////////////////////////////    
//////////////////////////////////////////////////////////////////////////////////////////////////////////
    static testMethod void testOppTask2() {
        Map < string, RecordTypeInfo > oppRecTypesByName = Opportunity.SObjectType.getDescribe().getRecordTypeInfosByName();
        Id oppRecordTypeId = oppRecTypesByName.get('Pitch').RecordTypeId;

        List < RecordType > agencyRecType = [
        Select
        Name
        From RecordType
        Where SObjectType = 'Account'
        And DeveloperName = 'Agency'];

        List < RecordType > accRecType = [
        Select
        Name
        From RecordType
        Where SObjectType = 'Account'
        And DeveloperName = 'Advertiser'];



        Pricebook2 testPB = [Select
        name
        From Pricebook2
        Where isActive = true
        limit 1];



PricebookEntry priceBookEntry = [
        select id, name, Product2Id
        from PricebookEntry
        where Product2.CustomerRef__c = 'CustomerRef3'
        and CurrencyIsoCode = 'GBP'
        and IsActive = true and (Not name like '%Provisional%') 
        limit 1];
        System.debug('ProcebookEntry is' + priceBookEntry);
        
        User mailClassTestUser = [
        select name, email, ProfileId, Profile.Name
        from User
        where isActive = true
        and Profile.Name = 'System Administrator'
        limit 1];
        
        User mailClassTestUser1 = [
        select name, email, ProfileId, Profile.Name
        from User
        where isActive = true
        and Profile.Name Like 'Mail Classified Manager'
        limit 1];
        
        System.debug('mailClassTestUser:' + mailClassTestUser);
        Account newAccount = new Account();
        Contact newContact = new Contact();

        newAccount = new Account(
        name = 'Test Account1',
        RecordTypeId = accRecType[0].Id,
        Type = 'Direct Advertiser',
        BillingStreet = 'Westminster Rd',
        BillingPostalCode = 'SW1 2AU',
        BillingCountry = 'United Kingdom',
        Industry = 'Display',
        isActive__c = True,
        Phone = '01236554482');
        insert newAccount;


        Account_mapping__c mapping1 = new Account_mapping__c(
        Source_system__c = 'CCI Metro',
        Account__c = newAccount.Id,
        Active__c = true,
        Source_Key__c = '98756254');
        insert mapping1;

        Account_mapping__c mapping2 = new Account_mapping__c(
        Source_system__c = 'CCI Mail',
        Account__c = newAccount.Id,
        Active__c = true,
        Source_Key__c = '23456');
        insert mapping2;

        Account newAgency = new Account(
        Name = 'Test Account2',
        AccountNumber = 'ABC1234562',
        RecordTypeId = agencyRecType[0].Id,
        BillingStreet = 'Street',
        BillingState = 'TestState',
        BillingPostalCode = 'A111AA',
        BillingCountry = 'United Kingdom',
        BillingCity = 'City',
        Phone = '01236547891');
        insert newAgency;

       /* Account_mapping__c mapping3 = new Account_mapping__c(
        Source_system__c = 'CCI Metro',
        Account__c = newAgency.Id,
        Active__c = true,
        Source_Key__c = '92364723');
        insert mapping3;

        Account_mapping__c mapping4 = new Account_mapping__c(
        Source_system__c = 'CCI Mail',
        Account__c = newAgency.Id,
        Active__c = true,
        Source_Key__c = '92364726');
        insert mapping4;*/

        Contact cnt1 = new Contact();
        cnt1.AccountId = newAccount.Id;
        cnt1.Active__c = True;
        cnt1.LastName = 'Test Last Name';
        cnt1.FirstName = 'Test First Name';
        cnt1.MailingCity = 'Test Mailing City';
        cnt1.MailingCountry = 'Test Mailing Country';
        cnt1.MailingPostalCode = 'TestMPC';
        cnt1.MailingState = 'Test Mailing State';
        cnt1.MailingStreet = 'Test Mailing Street';
        cnt1.MailingCountry = 'United Kingdom';
        insert cnt1;
        test.starttest();
        System.runAs(mailClassTestUser) {

            Opportunity op = new Opportunity(
            Name = 'Test MailClass1',
            AccountId = newAccount.Id,
            //Agency__c=newAgency.id,
            RecordTypeId = oppRecordTypeId,
            StageName = 'Preparation',
            CloseDate = Date.today(),
            Type = 'Proactive',
            OwnerId = mailClassTestUser.id,
            CurrencyIsoCode = 'GBP');
            insert op;

            OpportunityContactRole op1ContactRole = new OpportunityContactRole(OpportunityId = op.Id, Role = 'Agency Planning', ContactId = cnt1.Id, IsPrimary = True);
            insert op1ContactRole;


            /*Opportunity op1 = new Opportunity(
                                            Name='Test MailClass2',
                                            AccountId=newAccount.Id, 
                                            Agency__c=newAgency.id,
                                            RecordTypeId=oppRecordTypeId,
                                            StageName='Brief',
                                            CloseDate=Date.today(),
                                            Type='Proactive',
                                            OwnerId = mailClassTestUser.id);
            insert op1;

            OpportunityContactRole opContactRole = new OpportunityContactRole(OpportunityId=op1.Id, Role='Agency Planning', ContactId=cnt1.Id, IsPrimary=True);
            insert opContactRole;
         */

            OpportunityLineItem newline1 = new OpportunityLineItem();

            newline1.OpportunityId = op.id;
            newline1.ServiceDate = date.today() + 5;
            newline1.Description = 'Test Description';
            newline1.UnitPrice = 1000;
            newline1.Quantity = 1;
            newline1.PriceBookEntryId = priceBookEntry.id;
            newline1.Last_Insertion_Date__c = System.today() + 6;


            insert newline1;

            /*           OpportunityLineItem newline=new OpportunityLineItem();
                
                newline.OpportunityId= op1.id;
                newline.ServiceDate = date.today() + 5;
                newline.Description      = 'Test Description';
                newline.UnitPrice        = 1000;
                newline.Quantity=1;
                newline.PriceBookEntryId=priceBookEntry.id;
                
                
               insert newline;*/
            List < Opportunity > newopps = new List < Opportunity > ();
            List < OpportunityLineItem > newlines = new List < OpportunityLineItem > ();

            newopps.add(op);
            //newopps.add(op1);

            //Auto-Task on Opportunity
            if (mailClassTestUser.Profile.Name.contains('Mail Classified') || mailClassTestUser.Profile.Name.contains('System Administrator')) {
                List < Opportunity > newopps1 = new List < Opportunity > ();
                List < OpportunityContactRole > newocrs = new List < OpportunityContactRole > ();
                //newopps1.add(op1);
                newocrs.add(op1ContactRole);
                newlines.add(newline1);
                //newlines.add(newline1);
                map < Id, List < OpportunityContactRole >> newocrsmap = new map < Id, List < OpportunityContactRole >> ();
                map < Id, List < OpportunityLineItem >> newopplinesmap = new map < Id, List < OpportunityLineItem >> ();

                newocrsmap.put(op.id, newocrs);
                newopplinesmap.put(op.id, newlines);

                AutoCreateTaskOnOpportunity.createTasks(newopps, newopplinesmap, newocrsmap);
            }



            //newopps.add(op1);
            //system.runAs(tmpUser)
            //test.startTest();     
            if (newopps.size() > 0) {
                for (Opportunity opp1: newopps) {
                    opp1.Stagename = 'Closed Won';
                    //opp1.Loss_Reason__c='Did not use online';
                    opp1.AutoTaskWonCreated__c = False;
                    //AutoCreateTaskOnOpportunity.createClosedOppTasks(newopps1, newopplinesmap, newocrsmap);
                }
                update newopps;
            }



            //System.assertEquals(1, newtasksToUpdate.size());
            //System.assertEquals(2, newtasksToUpdate.size());    

            test.stopTest();
        }
    }
//////////////////////////////////////////////////////////////////////////////////////////////////////////    
}