src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unlocked</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CreditApprover__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ANy Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CreditApprovalLevel__c</fullName>
        <label>Credit Approval Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>CreditApprovers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesSectionEmail__c</fullName>
        <label>Sales Section Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesSection__c</fullName>
        <label>Sales Section</label>
        <picklist>
            <controllingField>BusinessUnit__c</controllingField>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicester SSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order, Motors, Homes &amp; Gardens, Interiors &amp; Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility, Health, Career Mail, Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overseas Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy &amp; Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems &amp; Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Barry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Hendle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Stevens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Approver</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Approvers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Query__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ANy Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CreditApprovalLevel__c</fullName>
        <label>Credit Approval Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateOpened__c</fullName>
        <label>Date Opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SalesInvoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Invoice</label>
        <referenceTo>c2g__codaInvoice__c</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Queries (Sales Manager)</relationshipLabel>
        <relationshipName>Queries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesSectionEmail__c</fullName>
        <label>Sales Section Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesSection__c</fullName>
        <label>Sales Section</label>
        <picklist>
            <controllingField>BusinessUnit__c</controllingField>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicester SSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order, Motors, Homes &amp; Gardens, Interiors &amp; Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility, Health, Career Mail, Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overseas Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy &amp; Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems &amp; Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Barry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Hendle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Stevens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send48HrEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set by a background process to flag that a 48 Hour Email followup should be sent. This field is a trigger for an email to be sent via a workflow.</description>
        <inlineHelpText>Set by a background process to flag that a 48 Hour Email followup should be sent. This field is a trigger for an email to be sent via a workflow.</inlineHelpText>
        <label>Send 48hr Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Query</description>
        <inlineHelpText>Status of Query</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Approval Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Credit Controller Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note Created</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Query</label>
    <nameField>
        <displayFormat>QRY{00000}</displayFormat>
        <label>Query Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Send48HrQueryEmailServiceTest.cls
@isTest(SeeAllData=true)
private class Send48HrQueryEmailServiceTest
{
    private static c2g__codaInvoice__c s_invoice;
    private static CreditApprover__c s_manager;
    private static CreditApprover__c s_manager2;
    private static CreditApprover__c s_salesPerson;
    private static CreditApprover__c s_salesPerson2;
    private static CreditApprover__c s_approver;
    private static Contact s_contact;

    /**
     * Test the updateing of the Send48HrEmail field simulated on a Monday
     */
    static testMethod void test48HrFromMonday()
    {
        setup();

        // Nul the Invoice Document Credit Status
        s_invoice.ffps_dmg__DocumentCreditStatus__c = null;
        update s_invoice;

        // Create a new Query and set the status to Open
        Query__c qry = new Query__c(
            SalesInvoice__c = s_invoice.Id,
            Status__c = 'Open',
            CustomerContact__c = s_contact.Id
        );

        insert qry;

        try
        {
            qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                    From Query__c
                    Where Id = :qry.Id];

            System.debug('>>> qry=' + qry);
        }
        catch(System.QueryException e)
        {
            System.assert(false, 'Could not find Query. Error=' + e.getMessage());
        }

        System.assertNotEquals(null, qry.DateOpened__c);
        System.assertEquals(false, qry.Send48HrEmail__c);

        // Set the Test Date to Monday 30th June 1913 15:31:00
        Send48HrQueryEmailService.s_testDate = DateTime.newInstance(1913, 6, 30, 15, 31, 0);

        // Set the Date Opened to Friday 27th June 1913 15:30:00
        qry.DateOpened__c = DateTime.newInstance(1913, 6, 27, 15, 30, 0);
        update qry;

        // Initialise and execute the Service
        Send48HrQueryEmailService svc = new Send48HrQueryEmailService();
        svc.execute(null);

        // Requery and assert the Send48HrEmail Flag
        qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                From Query__c
                Where Id = :qry.Id];

        System.assertEquals(false, qry.Send48HrEmail__c);

        // Set the Date Opened to Thursday 26th June 1913 15:30:00
        qry.DateOpened__c = DateTime.newInstance(1913, 6, 26, 15, 30, 0);
        update qry;

        // Initialise and execute the Service
        svc = new Send48HrQueryEmailService();
        svc.execute(null);

        // Requery and assert the Send48HrEmail Flag
        qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                From Query__c
                Where Id = :qry.Id];

        System.assertEquals(true, qry.Send48HrEmail__c);
    }

    /**
     * Test the updateing of the Send48HrEmail field simulated on a Tuesday
     */
    static testMethod void test48HrFromTuesday()
    {
        setup();

        // Nul the Invoice Document Credit Status
        s_invoice.ffps_dmg__DocumentCreditStatus__c = null;
        update s_invoice;

        // Create a new Query and set the status to Open
        Query__c qry = new Query__c(
            SalesInvoice__c = s_invoice.Id,
            Status__c = 'Open',
            CustomerContact__c = s_contact.Id
        );

        insert qry;

        try
        {
            qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                    From Query__c
                    Where Id = :qry.Id];

            System.debug('>>> qry=' + qry);
        }
        catch(System.QueryException e)
        {
            System.assert(false, 'Could not find Query. Error=' + e.getMessage());
        }

        System.assertNotEquals(null, qry.DateOpened__c);
        System.assertEquals(false, qry.Send48HrEmail__c);

        // Set the Test Date to Tuesday 1st July 1913 15:31:00
        Send48HrQueryEmailService.s_testDate = DateTime.newInstance(1913, 7, 1, 15, 31, 0);

        // Set the Date Opened to Friday 27th June 1913 16:30:00
        qry.DateOpened__c = DateTime.newInstance(1913, 6, 27, 16, 30, 0);
        update qry;

        // Initialise and execute the Service
        Send48HrQueryEmailService svc = new Send48HrQueryEmailService();
        svc.execute(null);

        // Requery and assert the Send48HrEmail Flag
        qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                From Query__c
                Where Id = :qry.Id];

        System.assertEquals(false, qry.Send48HrEmail__c);

        // Set the Date Opened to Friday 27th June 1913 15:30:00
        qry.DateOpened__c = DateTime.newInstance(1913, 6, 27, 15, 30, 0);
        update qry;

        // Initialise and execute the Service
        svc = new Send48HrQueryEmailService();
        svc.execute(null);

        // Requery and assert the Send48HrEmail Flag
        qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                From Query__c
                Where Id = :qry.Id];

        System.assertEquals(true, qry.Send48HrEmail__c);
    }

    /**
     * Test the updateing of the Send48HrEmail field simulated on a Monday
     */
    static testMethod void test48HrFromWednesday()
    {
        setup();

        // Nul the Invoice Document Credit Status
        s_invoice.ffps_dmg__DocumentCreditStatus__c = null;
        update s_invoice;

        // Create a new Query and set the status to Open
        Query__c qry = new Query__c(
            SalesInvoice__c = s_invoice.Id,
            Status__c = 'Open',
            CustomerContact__c = s_contact.Id
        );

        insert qry;

        try
        {
            qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                    From Query__c
                    Where Id = :qry.Id];

            System.debug('>>> qry=' + qry);
        }
        catch(System.QueryException e)
        {
            System.assert(false, 'Could not find Query. Error=' + e.getMessage());
        }

        System.assertNotEquals(null, qry.DateOpened__c);
        System.assertEquals(false, qry.Send48HrEmail__c);

        // Set the Test Date to Wednesday 2nd July 1913 15:31:00
        Send48HrQueryEmailService.s_testDate = DateTime.newInstance(1913, 7, 2, 15, 31, 0);

        // Set the Date Opened to Tuesday 1st July 1913 15:30:00
        qry.DateOpened__c = DateTime.newInstance(1913, 7, 1, 15, 30, 0);
        update qry;

        // Initialise and execute the Service
        Send48HrQueryEmailService svc = new Send48HrQueryEmailService();
        svc.execute(null);

        // Requery and assert the Send48HrEmail Flag
        qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                From Query__c
                Where Id = :qry.Id];

        System.assertEquals(false, qry.Send48HrEmail__c);

        // Set the Date Opened to Monday 30th June 1913 15:30:00
        qry.DateOpened__c = DateTime.newInstance(1913, 6, 30, 15, 30, 0);
        update qry;

        // Initialise and execute the Service
        svc = new Send48HrQueryEmailService();
        svc.execute(null);

        // Requery and assert the Send48HrEmail Flag
        qry = [Select Id, Name, DateOpened__c, Send48HrEmail__c
                From Query__c
                Where Id = :qry.Id];

        System.assertEquals(true, qry.Send48HrEmail__c);
    }

    private static void setup()
    {
        // Create the Credit Approvers
        List<CreditApprover__c> managers = new List<CreditApprover__c>();

        s_manager = new CreditApprover__c(
            Name = 'Manager',
            Email__c = 'test_manager@financialforce.com',
            SalesSection__c = 'test_section1',
            SalesSectionEmail__c = 'test_manager_section@financialforce.com',
            BusinessUnit__c = 'test_bu1',
            CreditApprovalLevel__c = 99999
        );

        managers.add(s_manager);

        s_manager2 = new CreditApprover__c(
            Name = 'Manager2',
            Email__c = 'test_manager2@financialforce.com',
            SalesSection__c = 'test_section1-2',
            SalesSectionEmail__c = 'test_manager_section2@financialforce.com',
            BusinessUnit__c = 'test_bu1-2',
            CreditApprovalLevel__c = 99999
        );

        managers.add(s_manager2);

        insert managers;

        List<CreditApprover__c> approvers = new List<CreditApprover__c>();

        s_salesPerson = new CreditApprover__c(
            Name = 'Sales Person',
            Email__c = 'test_sales@financialforce.com',
            SalesSection__c = 'test_section2',
            SalesSectionEmail__c = 'test_sales_section@financialforce.com',
            BusinessUnit__c = 'test_bu2',
            CreditApprovalLevel__c = 99999,
            SalesManager__c = s_manager.Id
        );

        approvers.add(s_salesPerson);

        s_salesPerson2 = new CreditApprover__c(
            Name = 'Sales Person2',
            Email__c = 'test_sales2@financialforce.com',
            SalesSection__c = 'test_section2-2',
            SalesSectionEmail__c = 'test_sales_section2@financialforce.com',
            BusinessUnit__c = 'test_bu2-2',
            CreditApprovalLevel__c = 99999,
            SalesManager__c = s_manager2.Id
        );

        approvers.add(s_salesPerson2);

        s_approver = new CreditApprover__c(
            Name = 'Approver',
            Email__c = 'test_approver@financialforce.com',
            SalesSection__c = 'test_section3',
            SalesSectionEmail__c = 'test_approver_section@financialforce.com',
            BusinessUnit__c = 'test_bu3',
            CreditApprovalLevel__c = 99999
        );

        approvers.add(s_approver);

        insert approvers;

        // Grab an arbitary Invoice
        String qry = 'Select Id, Name, SalesPerson__c, c2g__Account__c, ffps_dmg__FinanceAccount__c, ffps_dmgi__Order_Billing_Notes__c, ' +
                        '(Select Id, Name, c2g__NetValue__c from c2g__InvoiceLineItems__r Order By c2g__LineNumber__c) ' +
                     'From c2g__codaInvoice__c Limit 1';

        c2g__codaInvoice__c inv = (c2g__codaInvoice__c)Database.query(qry);
        Id invId = inv.Id;

        // update the Sales Person
        inv.SalesPerson__c = s_salesPerson.Id;

        update inv;

        qry = 'Select Id, Name, SalesPerson__c, c2g__Account__c, ffps_dmg__FinanceAccount__c, ffps_dmgi__Order_Billing_Notes__c, ' +
                '(Select Id, Name, c2g__NetValue__c, ffps_dmgi__LongDescription__c ' +
                    'from c2g__InvoiceLineItems__r Order By c2g__LineNumber__c) ' +
              'From c2g__codaInvoice__c ' +
              'Where Id = :invId';
        
        inv = (c2g__codaInvoice__c)Database.query(qry);

        System.assertNotEquals(null, inv.SalesPerson__c);
        System.assertEquals(s_salesPerson.Id, inv.SalesPerson__c);

        s_invoice = inv;

        // Grab an arbitary Contact
        //s_contact = [Select Id, Name From Contact Limit 1];
        Contact c = new Contact(
            FirstName = 'My Test Contact', 
            LastName = 'My Test Contact', 
            Email = 'test_contact@financialforce.com', 
            AccountId = inv.c2g__Account__c
        );

        insert c;

        s_contact = [Select Id, Name From Contact Where Id = :c.Id];

        // Apply contact to finance account (if not set)
        ffps_dmg__FinanceAccount__c fa = [Select Id, ffps_dmg__DocumentDestinationContact__c From ffps_dmg__FinanceAccount__c Where Id = :inv.ffps_dmg__FinanceAccount__c];

        if (fa.ffps_dmg__DocumentDestinationContact__c == null)
        {
            fa.ffps_dmg__DocumentDestinationContact__c = s_contact.Id;
            update fa;
        }
    }
}