src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Group - read/write</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Group - read only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <recordTypes>
        <fullName>Media_Partner</fullName>
        <active>true</active>
        <description>Please select this record type to create a Media Partner.</description>
        <label>Media Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Group</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Constants__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Advertiser_Record_Type__c</fullName>
        <defaultValue>&apos;Advertiser&apos;</defaultValue>
        <label>Advertiser Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Record_Type__c</fullName>
        <defaultValue>&apos;Agency&apos;</defaultValue>
        <label>Agency Record Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Creative_Snapshot_URL__c</fullName>
        <defaultValue>&apos;http://www.addynamix.co.uk/Press/Alerts/CreativeSnapshot.aspx&apos;</defaultValue>
        <description>This URL will be used to display the Advert from the Account Page.</description>
        <label>Creative Snapshot URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>CustomerRef1email__c</fullName>
        <label>CustomerRef1email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef2email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef2email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef3email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef3email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef4email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef4email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerRef5email__c</fullName>
        <defaultValue>&apos;o2.generic@cloudsensesolutions.com&apos;</defaultValue>
        <label>CustomerRef5email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Media_Lead_Opp_Record_Type__c</fullName>
        <defaultValue>&apos;Media_Opportunities&apos;</defaultValue>
        <label>Media Lead Opp Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Media_Partner_Record_Type__c</fullName>
        <defaultValue>&apos;Media_Partner&apos;</defaultValue>
        <label>Media Partner Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regular_Opp_Record_Type__c</fullName>
        <defaultValue>&apos;New_Business&apos;</defaultValue>
        <label>Regular Opp Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wowcher_Lead_Owner__c</fullName>
        <defaultValue>&apos;Julian Boardman&apos;</defaultValue>
        <description>Wowcher Lead Owner will be used if the Lead has no activities after a period of time.</description>
        <label>Wowcher Lead Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Constants</label>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Group - read/write</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group - read only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Departmental</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Media_Opportunities</fullName>
        <active>false</active>
        <businessProcess>Metro Display - Media Leads</businessProcess>
        <description>DO NOT ACTIVATE: Please use this Type to create a Pitch from the Leads Meeting</description>
        <label>Media Lead</label>
    </recordTypes>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>Metro Display - Opportunities</businessProcess>
        <description>Please use this Type to create a standard Pitch</description>
        <label>Pitch</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Booking_Source__c</fullName>
        <label>Booking Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCI_Account_ID__c</fullName>
        <description>CCI Finance Account ID</description>
        <label>CCI Finance Account ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCI_Order_ID__c</fullName>
        <description>CCI AdDesk Sales Order Id</description>
        <externalId>true</externalId>
        <label>CCI Order ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Delivery_Date__c</fullName>
        <label>First Insertion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Delivery_Date__c</fullName>
        <label>Last Insertion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>CCI_Order_Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>CCI Order Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Delivery_Date__c</fullName>
        <label>Insertion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Delivery_Date__c</fullName>
        <label>Last Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication_Name__c</fullName>
        <label>Publication Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account_A__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account A</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are some relationships which have Inactive Agencies attached to this Account. Please identify them and correct as necessary.</errorMessage>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Outgoing)</relationshipLabel>
        <relationshipName>Account_Account_rel_A</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_B__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account B</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are some relationships which have Inactive Agencies attached to this Account. Please identify them and correct as necessary.</errorMessage>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Incoming)</relationshipLabel>
        <relationshipName>Account_Account_rel_B</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booking/Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Group - read/write</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Group - read only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MockData.cls
/**
 *    This is a template for custom fixtures, the existense and name of the class are irrelevant.
 *	Class name can be anything, but by default if class MockData exists then Mock will load it, unless told otherwise
 *	via Mock.MOCK_DATA variable assignment
 *
 */@isTest
public with sharing class MockData extends MockDataStandard {
	private static Map < String, Map < String, Object >> DEFAULT_VALUES_BY_TYPE = new Map < String, Map < String, Object >> ();

	public MockData() {
		super();
		addSingletonObjectType('Constants__c');
	}
	private static void setup() {}
	//add your own (new) fixture definitions here and then add their initialisation in the static section below


	//EXAMPLE
	//public static Map<String, Object> ORDER_LINE_VALUES = new Map<String, Object> {
	//	'Field_name__c' => 'value'
	//};

	//if you want to extend or overrdide standard fixture defined in MockDataStandard then do it here as well
	//EXAMPLE
	//public static Map<String, Object> ACCOUNT_VALUES = new Map<String, Object> {
	//	'Name' => 'My New Acount Name Value#{COUNTER}',//override Name definition specified in MockDataStandard
	//	'My_Field__c' => 5, //add definition for a custom field
	//	Mock.DEPENDS_ON => new Map<String, String>{'AccountId' => 'Account'} //add dependency on parent/related object
	//};

	public static Map < String, Object > CONSTANTS_VALUES = new Map < String, Object > {
		'Name' => 'All',
			'Advertiser_Record_Type__c' => 'Advertiser',
			'Agency_Record_Type__c' => 'Agency',
			'Creative_Snapshot_URL__c' => 'http://www.addynamix.co.uk/Press/Alerts/CreativeSnapshot.aspx',
			'CustomerRef1email__c' => 'ssfoperative@anmedia.co.uk.test',
			'CustomerRef2email__c' => 'ssfoperative@anmedia.co.uk.test',
			'CustomerRef3email__c' => 'ssfoperative@anmedia.co.uk.test',
			'CustomerRef4email__c' => 'ssfoperative@anmedia.co.uk.test',
			'CustomerRef5email__c' => 'ssfoperative@anmedia.co.uk.test',
			'Media_Lead_Opp_Record_Type__c' => 'Media_Opportunities',
			'Media_Partner_Record_Type__c' => 'Media_Partner',
			'Regular_Opp_Record_Type__c' => 'New_Business',
			'Wowcher_Lead_Owner__c' => 'Some Test User'
	};

	public static Map < String, Object > CAMPAIGN_VALUES = new Map < String, Object > {
		'Name' => 'Campaign #{COUNTER}',
			'IsActive' => true,
			'Status' => 'Planned',
			'Type' => 'Advertisement',
			'CurrencyIsoCode' => 'GBP',
			'StartDate' => System.today() - 365,
			'EndDate' => System.today() + 365
	};
	public static Map < String, Object > ACCOUNT_ADVERTISER_VALUES = new Map < String, Object > {
		'Name' => 'Advertiser #{COUNTER}',
			'RecordTypeId' => MockUtils.getRecordType('Account', 'Advertiser').Id,
			'Type' => 'Test Type',
			'IsActive__c' => true,
			'BillingStreet' => 'Advertiser Street',
			'BillingPostalCode' => 'A111AA',
			'Phone' => '0123654789'
	};
	public static Map < String, Object > ACCOUNT_DIRECT_ADVERTISER_VALUES = new Map < String, Object > {
		'Name' => 'Advertiser #{COUNTER}',
			'RecordTypeId' => MockUtils.getRecordType('Account', 'Advertiser').Id,
			'Type' => 'Direct Advertiser',
			'IsActive__c' => true,
			'BillingStreet' => 'Advertiser Street',
			'BillingPostalCode' => 'A111AA',
			'Phone' => '0123654789'
	};
	public static Map < String, Object > ACCOUNT_AGENCY_VALUES = new Map < String, Object > {
		'Name' => 'Agency #{COUNTER}',
			'RecordTypeId' => MockUtils.getRecordType('Account', 'Agency').Id,
			'Type' => 'Billing Agency',
			'IsActive__c' => true,
			'Phone' => '000000',
			'BillingStreet' => 'Agency Street',
			'BillingPostalCode' => 'A111AA',
			'Phone' => '0123654789'
	};

	public static Map < String, Object > OPPORTUNITY_VALUES = new Map < String, Object > {
		'StageName' => 'Prospecting',
			'CloseDate' => System.today(),
		Mock.DEPENDS_ON => new Map < String, String > {
			'AccountId' => 'Account#DirectAdvertiser'
		}
	};

	public static Map < String, Object > AGENCY_ADVERTISER_RELATIONSHIP_VALUES = new Map < String, Object > {
		'Name' => 'Agency <-> Advertiser #{COUNTER}',
			'Active__c' => true,
			'Role__c' => 'Creative',
			'Visibility__c' => 'Group - read/write',
		Mock.DEPENDS_ON => new Map < String, String > {
			'Account_A__c' => 'Account#Agency', 'Account_B__c' => 'Account#Advertiser'
		}
	};
	public static Map < String, Object > ADVERTISER_AGENCY_RELATIONSHIP_VALUES = new Map < String, Object > {
		'Name' => 'Agency <-> Advertiser #{COUNTER}',
			'Active__c' => true,
			'Role__c' => 'Creative',
			'Visibility__c' => 'Group - read/write',
		Mock.DEPENDS_ON => new Map < String, String > {
			'Account_B__c' => 'Account#Agency', 'Account_A__c' => 'Account#Advertiser'
		}
	};

	public static Map < String, Object > PRICEBOOK_VALUES = new Map < String, Object > {
		'Name' => 'Pricebook #{COUNTER}',
			'IsActive' => true
	};
	public static Map < String, Object > PRODUCT2_VALUES = new Map < String, Object > {
		'Name' => 'Product #{COUNTER}',
		/*'CurrencyIsoCode' => 'GBP',*/
		'IsActive' => true
	};

	public static Map < String, Object > PRICEBOOKENTRY_VALUES = new Map < String, Object > {
		'CurrencyIsoCode' => 'GBP',
			'UnitPrice' => 0.0,
			'IsActive' => true,
			'UseStandardPrice' => false,
		Mock.DEPENDS_ON => new Map < String, String > {
			'Pricebook2Id' => 'Pricebook2', 'Product2Id' => 'Product2'
		}
	};

	public static map < String, Object > ORDER_VALUES = new map < String, Object > {
		'EffectiveDate' => System.Today(),
			'Booking_Source__c' => 'CCIBookingPlugin',
			'Status' => 'Draft',
			'First_Delivery_Date__c' => System.Today(),
			'Last_Delivery_Date__c' => System.today(),
			'CurrencyIsoCode' => 'GBP',
			'Base_Price__c' => 0.0,
			'CCI_Order_ID__c' => 'Test#{COUNTER}',
			'CCI_Account_ID__c' => 'TestCCIAccountID#{COUNTER}',
		Mock.DEPENDS_ON => new Map < String, String > {
			'AccountID' => 'Account#Advertiser', 'Opportunity__c' => 'Opportunity'
		}
	};

	public static map < String, Object > ORDERLINEITEM_VALUES = new map < String, Object > {
		'Publication_Name__c' => 'test brand',
			'UnitPrice' => 100,
			'Quantity' => 1,
			'CCI_Order_Item_ID__c' => 'TestOrderItemID#{COUNTER}'
	};

	static {

		setup();
		//all fixture maps specified above need to be added here

		DEFAULT_VALUES_BY_TYPE.put('Constants__c', CONSTANTS_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Campaign', CAMPAIGN_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Opportunity', OPPORTUNITY_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Account#Advertiser', ACCOUNT_ADVERTISER_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Account#DirectAdvertiser', ACCOUNT_DIRECT_ADVERTISER_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Account#Agency', ACCOUNT_AGENCY_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Relationship__c#AgencyAdvertiser', AGENCY_ADVERTISER_RELATIONSHIP_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Relationship__c#AdvertiserAgency', ADVERTISER_AGENCY_RELATIONSHIP_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Pricebook2', PRICEBOOK_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Product2', PRODUCT2_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('PricebookEntry', PRICEBOOKENTRY_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('Order', ORDER_VALUES);
		DEFAULT_VALUES_BY_TYPE.put('OrderItem', ORDERLINEITEM_VALUES);
	}

	public override Map < String, Object > getValueMap(final String objApiName, final Map < String, Object > fieldValues) {
		return MockData.DEFAULT_VALUES_BY_TYPE.get(objApiName);
	}

	public static User getTestUserWithConstantsH(String profileName, String department) {
		return getTestUserWithConstantsH(profileName, department, null);
	}
	public static User getTestUserWithConstantsH(String profileName, String department, String priceBookName) {
		Profile p = MockUtils.getProfile(profileName);
		System.assertNotEquals(null, p, 'Invalid profile name: ' + profileName);
		User usr = (User) Mock.one('User', new Map < String, Object > {
			'ProfileId' => p.Id
		}, true);
		//if SeeAllData=true is used then delete existing setting
		final ConstantsH__c chExisting = ConstantsH__c.getInstance(usr.ProfileId);
		if (null != chExisting && null != chExisting.Id) {
			Database.delete(chExisting);
		}

		ConstantsH__c ch = new ConstantsH__c();
		ch.Acc_and_Contact_owner__c = usr.lastname;
		ch.Department__c = department;
		ch.IsManager__c = false;
		if (null != priceBookName) {
			ch.Price_Book__c = priceBookName;
		}
		ch.SetupOwnerId = usr.ProfileId;
		System.debug('agX ch=' + ch);

		Database.insert(ch);
		if (BookingSystemSettings__c.getAll().get('CCI') == null) {
			insert TestData.createBookingSystemSettings();
		}
		if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
			insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
		}
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();

		return usr;
	}
}