src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountMappingDone__c</fullName>
        <label>AccountMappingDone</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Classified_Minor_Category__c</fullName>
        <label>Classified - Minor Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accessories &amp; Soft Furnishings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia &amp; New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balearics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedrooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blackpool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bournemouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building &amp; Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Businesses For Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire &amp; Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clerical &amp; Secretarial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conservatories, Lofts &amp; Extensions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts &amp; Tenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cornwall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotswolds</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CountOfOpportunity__c</fullName>
        <label>CountOfOpportunity</label>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CustomerRef1__c</fullName>
        <label>CCI Metro Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef2__c</fullName>
        <label>AdVance Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef3__c</fullName>
        <label>CCI Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef4__c</fullName>
        <label>Operative Cust Ref</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerRef5__c</fullName>
        <label>Origins Irish Mail Cust Ref</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IndClassLvl1__c</fullName>
        <label>Classified - Main Category</label>
        <picklist>
            <picklistValues>
                <fullName>Business &amp; Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &amp; Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homes &amp; Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noticeboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal &amp; Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IndClassLvl2__c</fullName>
        <label>Classified - Sub Category</label>
        <picklist>
            <controllingField>IndClassLvl1__c</controllingField>
            <picklistValues>
                <fullName>Airlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airport Parking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apprenticeships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (General)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Motors)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auctions (Property)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;B/Guest Houses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bars/Clubs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battlefields</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Births, Deaths and Marriages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business to Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping and Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravan Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravans &amp; Motorhomes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cars wanted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinemas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City Living</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Trials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collectables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complementary Therapies &amp; Wellbeing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Mappings</relationshipLabel>
        <relationshipName>Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Key__c</fullName>
        <label>Customer Ref</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operative One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nielsen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDM Origins</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Mapping</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/classes/BatchCreateAccountMappingsAARef2.cls
public with sharing class BatchCreateAccountMappingsAARef2 implements Database.Batchable < sObject > , Database.Stateful {
	//Integer queryLimit;
	Double failedUpdates {
		get;
		set;
	}

	public final String custRef;
	public final Decimal oppCount;

	public BatchCreateAccountMappingsAARef2() {

	}

	//////////start
	public Database.querylocator start(Database.BatchableContext ctx) {
		return Database.getQueryLocator(
		[
		Select
		CustomerRef1__c,
		CustomerRef2__c,
		CustomerRef3__c,
		CustomerRef4__c,
		CustomerRef5__c
		From Account
		Where AccountMappingDone__c != 'Yes'
		And AccountMappingDone__c != 'Dupe'
		And IsActive__c = True
		And CustomerRef2__c != Null
		// And (CustomerRef1__c!=Null Or CustomerRef2__c!=Null Or CustomerRef3__c!=Null Or CustomerRef4__c!=Null Or CustomerRef5__c!=Null)
		]);
	}


	//////////execute

	public void execute(Database.BatchableContext BC, List < sObject > scope) {

		List < Account > accns = (List < Account > ) scope;
		List < Account > allaccs = new List < Account > ();
		List < Account_Mapping__c > newAccList = new List < Account_Mapping__c > ();
		Set < String > customerRef2List = new Set < String > ();

		for (Account a: accns) {
			if (a.CustomerRef2__c != null) {
				customerRef2List.add(a.CustomerRef2__c);
			}

		}


		List < AggregateResult > result = [Select
		CustomerRef2__c,
		MAX(CountOfOpportunity__c)
		From Account
		Where AccountMappingDone__c != 'Yes'
		And AccountMappingDone__c != 'Dupe'
		And IsActive__c = True
		And CustomerRef2__c IN: customerRef2List
		Group By CustomerRef2__c];
		for (AggregateResult ar: result) {
			//custRefList.add(new CallBatchAccountMappings.customerRef((String)ar.get('CustomerRef1__c'), (Decimal)ar.get('expr0')));  
			//Id batchInstanceId = Database.executeBatch(new BatchCreateNonDupeAccountMappings((String)ar.get('CustomerRef1__c'), (Decimal)ar.get('expr0')), 1);    
			createMappings((String) ar.get('CustomerRef2__c'), (Decimal) ar.get('expr0'));
		}



	}

	public void createMappings(String custRefInfo, Decimal oppCountInfo) {
		List < Account_Mapping__c > newAccList = new List < Account_Mapping__c > ();
		List < Account > allaccs = new List < Account > ();
		List < Account > accList = [Select
		CustomerRef1__c,
		CustomerRef2__c,
		CustomerRef3__c,
		CustomerRef4__c,
		CustomerRef5__c,
		CountOfOpportunity__c,
		AccountMappingDone__c
		From Account
		Where AccountMappingDone__c != 'Yes'
		And AccountMappingDone__c != 'Dupe'
		And IsActive__c = True
		And CustomerRef2__c = : custRefInfo];
		for (Account a: accList) {

			if (a.CountOfOpportunity__c == oppCountInfo) {
				if (a.CustomerRef1__c != Null) {
					String custref = a.CustomerRef1__c;
					List < string > split1 = new List < string > ();
					for (String ss1: custref.Split(',')) {
						if (ss1.trim() != null || ss1.trim() != '') {
							split1.add(ss1.trim());
						}
					}

					for (String s1: split1) {
						Account_Mapping__c am = new Account_Mapping__c();
						am.Account__c = a.Id;
						am.Source_System__c = 'CCI Metro';
						am.Source_Key__c = s1;
						am.Active__c = True;
						newAccList.add(am);
					}

				}
				if (a.CustomerRef2__c != Null)

				{
					String custref = a.CustomerRef2__c;
					List < string > split2 = new List < string > ();
					for (String ss2: custref.Split(',')) {
						if (ss2.trim() != null || ss2.trim() != '') {
							split2.add(ss2.trim());
						}
					}

					for (String s2: split2) {
						Account_Mapping__c am = new Account_Mapping__c();
						am.Account__c = a.Id;
						am.Source_System__c = 'Advance';
						am.Source_Key__c = s2;
						am.Active__c = True;
						newAccList.add(am);

					}

				}

				if (a.CustomerRef3__c != Null) {

					String custref = a.CustomerRef3__c;
					List < string > split3 = new List < string > ();
					for (String ss3: custref.Split(',')) {
						if (ss3.trim() != null || ss3.trim() != '') {
							split3.add(ss3.trim());
						}
					}

					for (String s3: split3) {

						Account_Mapping__c am = new Account_Mapping__c();
						am.Account__c = a.Id;
						am.Source_System__c = 'CCI Mail';
						am.Source_Key__c = s3;
						am.Active__c = True;
						newAccList.add(am);

					}

				}
				if (a.CustomerRef4__c != Null) {
					String custref = a.CustomerRef4__c;
					List < string > split4 = new List < string > ();
					for (String ss4: custref.Split(',')) {
						if (ss4.trim() != null || ss4.trim() != '') {
							split4.add(ss4.trim());
						}
					}

					for (String s4: split4) {

						Account_Mapping__c am = new Account_Mapping__c();
						am.Account__c = a.Id;
						am.Source_System__c = 'Operative One';
						am.Source_Key__c = s4;
						am.Active__c = True;
						newAccList.add(am);

					}

				}
				if (a.CustomerRef5__c != Null) {
					String custref = a.CustomerRef5__c;
					List < string > split5 = new List < string > ();
					for (String ss5: custref.Split(',')) {
						if (ss5.trim() != null || ss5.trim() != '') {
							split5.add(ss5.trim());
						}
					}

					for (String s5: split5) {

						Account_Mapping__c am = new Account_Mapping__c();
						am.Account__c = a.Id;
						am.Source_System__c = 'IDM Origins';
						am.Source_Key__c = s5;
						am.Active__c = True;
						newAccList.add(am);

					}

				}

				System.debug('***newAccMaps=' + newAccList.size());
				a.AccountMappingDone__c = 'Yes';
				allaccs.add(a);
			} else {
				a.AccountMappingDone__c = 'Dupe';
				allaccs.add(a);
			}

		}

		if (newAccList.size() > 0) {
			for (Account_Mapping__c a: newAccList) {
				try {
					insert a;
				} catch (Exception qe1) {

				}
			}
			// Insert newAccList;
		}
		if (allaccs.size() > 0) {
			update allaccs;
		}
	}
	/////////Finish
	public void finish(Database.BatchableContext bc) {


		AsyncApexJob a = [SELECT id, ApexClassId,
		JobItemsProcessed,
		TotalJobItems,
		NumberOfErrors,
		CreatedBy.Email
		FROM AsyncApexJob
		WHERE id = : bc.getJobId()];

		String emailMessage =
			'Your batch job ' + 'BatchCreateAccountMappingsActiveAccounts' + ' has finished.  It executed ' + a.totalJobItems +
			' batches.  Of which, ' + a.jobitemsprocessed + ' processed without any exceptions' + 'thrown and ' + a.numberOfErrors +
			' batches threw unhandled exceptions.' + '  Of the batches that executed' + 'without error, ' + failedUpdates + ' records were not updated successfully.';

		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		String[] toAddresses = new String[] {
			a.createdBy.email
		};
		mail.setToAddresses(toAddresses);
		mail.setReplyTo('noreply@salesforce.com');
		mail.setSenderDisplayName('Batch Job Summary');
		mail.setSubject('Batch job completed');
		mail.setPlainTextBody(emailMessage);
		mail.setHtmlBody(emailMessage);
		Messaging.sendEmail(new
		Messaging.SingleEmailMessage[] {
			mail
		});

	}

	//////////////Test
	// Test Method
	private static TestMethod void testAll() {
		insert TestData.createCountriesList();
		Test.startTest();
		User testUser = [
		select name, email, ProfileId, Profile.Name
		from User
		where isActive = true /*and managerId != null*/ and Profile.Name = 'System Administrator'
		limit 1];

		String testProfileId = [select id from Profile limit 1].id;

		ConstantsH__c newConstH = new ConstantsH__c(
		Acc_and_Contact_owner__c = testUser.Name,
		Department__c = 'Test Department 1',
		IsManager__c = false,
		//Price_Book__c             = testPB.Name,
		SetupOwnerId = testUser.ProfileId);
		insert newConstH;

		insert TestData.createBookingSystemSettings();
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
		insert TestData.createCountryCodeSettings();

		String advertiserRecTypeId = [
		select id
		from RecordType
		where DeveloperName = 'Advertiser'
		limit 1].id;

		Account acct = new Account(
		Name = 'TestAccount',
		AccountNumber = 'ABC123456',
		Type = 'Client',
		BillingStreet = 'Test Billing Street',
		BillingState = 'Test Billing State',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'London',
		Industry = 'Finance',
		IndClassLvl1__c = 'Finance',
		IndClassLvl2__c = 'Finance',
		Classified_Minor_Category__c = 'Finance',
		CustomerRef1__c = '12345',
		CustomerRef2__c = '23456',
		CustomerRef3__c = '34567',
		CustomerRef4__c = 'TestA',
		RecordTypeId = advertiserRecTypeId);
		insert acct;

		/*        Account_Mapping__c a = new Account_Mapping__c();
                            a.Account__c       = acct.Id;
                            a.Source_System__c = 'CCI Metro';
                            a.Source_Key__c    = '23747';
                            a.Active__c        = True;
                            
        insert a;
        Account_Mapping__c b = new Account_Mapping__c();
                            b.Account__c       = acct.Id;
                            b.Source_System__c = 'CCI Mail';
                            b.Source_Key__c    = '28462';
                            b.Active__c        = True;
                            
        insert b;
        Account_Mapping__c c = new Account_Mapping__c();
                            c.Account__c       = acct.Id;
                            c.Source_System__c = 'Advance';
                            c.Source_Key__c    = '2347239';
                            c.Active__c        = True;
                            
        insert c;
        Account_Mapping__c d = new Account_Mapping__c();
                            d.Account__c       = acct.Id;
                            d.Source_System__c = 'Operative One';
                            d.Source_Key__c    = 'optest23';
                            d.Active__c        = True;
                            
        insert d;
        
        Account_Mapping__c e = new Account_Mapping__c();
                            e.Account__c       = acct.Id;
                            e.Source_System__c = 'IDM Origins';
                            e.Source_Key__c    = 'IDM123';
                            e.Active__c        = True;
                            
        insert e;*/

		BatchCreateAccountMappingsAARef2 controller = new BatchCreateAccountMappingsAARef2();
		Integer batchSize = 1;
		database.executebatch(controller, batchSize);
		Test.stopTest();

		List < Account_Mapping__c > acList = [Select Source_Key__c from Account_Mapping__c where Account__c = : acct.Id];


		System.assertEquals('12345', acList[0].Source_Key__c);
		System.assertEquals('23456', acList[1].Source_Key__c);
		System.assertEquals('34567', acList[2].Source_Key__c);
		System.assertEquals('TestA', acList[3].Source_Key__c);


	}
	//////////////
}