src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCIMailCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMailCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCIMetroCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMetroCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DoCCIInt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DoCCIInt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Industry_Minor_Category__c</fullName>
        <label>Industry Minor Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>04.01.30 - GIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.10 - BEER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.12 - LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.05 - ALCOHOL FREE BEER &amp; LAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.20 - BRANDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.80 - VODKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.40 - PORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.89 - CHAMPAGNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.50 - SHERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.93 - ALCOPOPS ALCOHOL SOFT DRINKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04.01.25 - CIDER &amp; PERRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.00 - TOBACCO ACCESSORIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.02.05 - LIGHTERS,MATCHES,OTHER ACCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.00 - TOBACCO RANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.10 - CIGARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06.01.05 - CIGARETTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.99.99 - COSMETICS &amp; TOILETRIES CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.00 - PROFESSIONAL/B2B HAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.06.40 - SALONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.00 - MEN &amp; WOMENS FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.10 - PREMIUM MENS/WOMENS FRAG RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.05 - PREMIUM WOMENS PERFUMES/FRAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.05.11 - MASS MKT MENS/WOMENS FRAG RG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.00 - PERSONAL HYGIENE &amp; HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.55 - SHAVING PREPARATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.50 - SANITARY PROTECTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.65 - WET RAZORS &amp; BLADES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.91 - PERSONAL HYGIENE &amp; HEALTH GE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.05 - DENTALCARE-DENTURE CLEANERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08.04.20 - DENTALCARE-TOOTHPASTE,POLISH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.01.00 - FIRST AID</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NPA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPA</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/FinanceAccount__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Finance Accounts</relationshipLabel>
        <relationshipName>Finance_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DoCCIInt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DoCCIInt</label>
        <type>Checkbox</type>
    </fields>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/No_Validations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>No Validations</label>
</CustomObject>

src/classes/CCICustomerWebService_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */@isTest
public class CCICustomerWebService_Test {
	public static void setUpData() {
		insert TestData.createCountriesList();
		ConstantsH__c ch = new ConstantsH__c();
		ch.Acc_and_Contact_owner__c = 'A&N Media';
		ch.Department__c = 'IT';
		insert ch;

		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

		User u = new User(Alias = 'anmedia', Email = 'ANMedia@dmgmedia.com',
		EmailEncodingKey = 'UTF-8', FirstName = 'A&N', LastName = 'Media', LanguageLocaleKey = 'en_US',
		LocaleSidKey = 'en_US', ProfileId = p.Id,
		TimeZoneSidKey = 'America/Los_Angeles', UserName = 'ANMedia@dmgmedia.com');

		insert u;

		//insert custom settings for BookingSystemSettings
		insert TestData.createBookingSystemSettings();
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
		insert TestData.createCountryCodeSettings();

		//insert categories  
		insert TestData.createCustomerCategory();

	}
	private static testMethod void testcreateCCICustomerMailWithoutCategory() {
		setUpData();
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		insert acc;

		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Mail', false);
		System.debug('Response is' + response);

		System.assertNotEquals(null, response);
		Test.stopTest();

	}

	/**/
	private static testMethod void testcreateCCICustomerMailWithCategory() {
		setUpData();
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		acc.Industry_Minor_Category__c = '10.01.00 - FIRST AID';
		insert acc;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Mail', false);
		System.debug('Response is' + response);
		System.assertEquals(null, response);
		Account accUpdated = queryAccount(acc.id);
		System.assertEquals('1', accUpdated.CCIMailCustID__c);
		Test.stopTest();
	}
	/**/
	private static testMethod void testcreateCCICustomerMetroWithCategory() {
		setUpData();
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		acc.Industry_Minor_Category__c = '10.01.00 - FIRST AID';
		insert acc;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Metro', false);
		System.debug('Response is' + response);
		//System.assertEquals(null,response );
		Account accUpdated = queryAccount(acc.id);
		System.assertEquals('1', accUpdated.CCIMetroCustID__c);
		Test.stopTest();
	}
	/**/
	private static testMethod void testcreateCCICustomerMailWithDirectOrder() {
		setUpData();
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		insert acc;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Mail', true);
		System.debug('Response is' + response);
		//System.assertNotEquals(null,response );
		Account accUpdated = queryAccount(acc.id);
		System.assertEquals('1', accUpdated.CCIMailCustID__c);
		Test.stopTest();
	}



	public static Account queryAccount(Id accId) {
		return ([select Id, CCIMailCustID__c, CCIMetroCustID__c from Account where Id = : accId]);
	}


	private static testMethod void testCustomerWrapperClasses() {
		setUpData();
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		insert acc;
		Test.startTest();
		CCICustomerWrapper.AccountInfo acInfo1 = new CCICustomerWrapper.AccountInfo(acc.id, 'Test', '76236726736', 'test', 'London', 'we2 3th', 'UK', 'UK', '04.01.01', '1', '1', false, 'Direct Advertiser', '', '');
		CCICustomerWrapper.ChatterInfo chatterInfo = new CCICustomerWrapper.ChatterInfo(acc.id, 'Test');
		CCICustomerWrapper.AccessToken accessToken = new CCICustomerWrapper.AccessToken('ato', 'tto', 'rto', 'exp', 'rd');

		Test.stopTest();
	}

	private static testMethod void testcreateInactiveCustomer() {
		setUpData();
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		acc.IsActive__c = false;
		insert acc;

		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Mail', false);
		System.debug('Response is' + response);

		System.assertEquals(response, Label.InActiveAccountMessage);
		Test.stopTest();

	}

	private static testMethod void CCIAccountalreadyexists_Test() {
		setUpData();
		//No_Validations__c.Flag__c = true;
		Account acc = TestData.buildAccount('Agency', 'Billing Agency');
		acc.CCIMailCustID__c = 'test123456';
		insert acc;

		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Mail', false);
		System.debug('Response is' + response);

		System.assertEquals(response, Label.CCIAccount_already_exists);
		Test.stopTest();

	}

	private static testMethod void withFinanaceAccountMail_Test() {
		setUpData();
		//No_Validations__c.Flag__c = true;
		Account acc = TestData.buildAccount('Agency', 'Billing Agency');
		insert acc;
		Company__c testCompany = new Company__c(Name = 'Mail');
		insert testCompany;
		FinanceAccount__c testFinanceAccount = TestData.buildFinanceAccount(acc);
		testFinanceAccount.Company__c = testCompany.Id;
		insert testFinanceAccount;
		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Mail', false);
		System.debug('Response is' + response);
		Test.stopTest();
	}

	private static testMethod void withFinanaceAccountMetro_Test() {
		setUpData();
		//No_Validations__c.Flag__c = true;
		Account acc = TestData.buildAccount('Agency', 'Billing Agency');
		insert acc;
		Company__c testCompany = new Company__c(Name = 'Metro');
		insert testCompany;
		FinanceAccount__c testFinanceAccount = TestData.buildFinanceAccount(acc);
		testFinanceAccount.Company__c = testCompany.Id;
		insert testFinanceAccount;
		Test.startTest();
		String response = CCICustomerWebService.createCCICustomer(acc.id, 'Metro', false);
		System.debug('Response is' + response);
		Test.stopTest();
	}

	private static testMethod void testgetCCIAccount_mail() {
		setUpData();
		Account newAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		newAcc.Name = 'New Account';
		newAcc.Phone = '0123456789123';
		newAcc.BillingStreet = 'new account';
		newAcc.BillingCity = 'new city';
		newAcc.BillingPostalCode = 'aa111aa';
		newAcc.BillingState = 'new state';
		newAcc.BillingCountry = 'United Kingdom';
		newAcc.Industry_Minor_Category__c = '10.05.10 - HEALTH & FITNESS APPLIANCES';
		newAcc.CCIMailCustID__c = 'testmail123';
		newAcc.CCIMetroCustID__c = null;
		newAcc.NPA__c = false;
		newAcc.Type = 'Direct Advertiser';
		insert newAcc;

		Account oldAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		oldAcc.Name = 'Old Account';
		oldAcc.Phone = '01234567891';
		oldAcc.BillingStreet = 'old account';
		oldAcc.BillingCity = 'old city';
		oldAcc.BillingPostalCode = 'aa111aa';
		oldAcc.BillingState = 'old state';
		oldAcc.BillingCountry = 'United Kingdom';
		oldAcc.Industry_Minor_Category__c = '10.05.11 - ATHLETES PULSE MONITOR';
		oldAcc.CCIMailCustID__c = 'testmail123';
		oldAcc.CCIMetroCustID__c = null;
		oldAcc.NPA__c = false;
		oldAcc.Type = 'Direct Advertiser';

		List < String > oldAccInfo = new List < String > ();
		List < String > newAccInfo = new List < String > ();

		CCICustomerWrapper.AccountInfo ai = new CCICustomerWrapper.AccountInfo(newAcc.Id, newAcc.Name, newAcc.Phone, newAcc.BillingStreet, newAcc.BillingCity, newAcc.BillingPostalCode, newAcc.BillingState, newAcc.BillingCountry, newAcc.Industry_Minor_Category__c, newAcc.CCIMailCustID__c, newAcc.CCIMetroCustID__c, newAcc.NPA__c, newAcc.Type, '', '');
		newAccInfo.add(JSON.serialize(ai));
		CCICustomerWrapper.AccountInfo oldai = new CCICustomerWrapper.AccountInfo(newAcc.Id, oldAcc.Name, oldAcc.Phone, oldAcc.BillingStreet, oldAcc.BillingCity, oldAcc.BillingPostalCode, oldAcc.BillingState, oldAcc.BillingCountry, oldAcc.Industry_Minor_Category__c, oldAcc.CCIMailCustID__c, oldAcc.CCIMetroCustID__c, oldAcc.NPA__c, oldAcc.Type, '', '');
		oldAccInfo.add(JSON.serialize(oldai));
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		Test.startTest();
		CCICustomerWebService.getCCIAccount(newAccInfo, oldAccInfo, true);
		Test.stopTest();
	}

	private static testMethod void testgetCCIAccount_metro() {
		setUpData();
		Account newAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		newAcc.Name = 'New Account';
		newAcc.Phone = '0123456789123';
		newAcc.BillingStreet = 'new account';
		newAcc.BillingCity = 'new city';
		newAcc.BillingPostalCode = 'aa111aa';
		newAcc.BillingState = 'new state';
		newAcc.BillingCountry = 'United Kingdom';
		newAcc.Industry_Minor_Category__c = '10.05.10 - HEALTH & FITNESS APPLIANCES';
		newAcc.CCIMailCustID__c = null;
		newAcc.CCIMetroCustID__c = 'testmetro123';
		newAcc.NPA__c = false;
		newAcc.Type = 'Direct Advertiser';
		insert newAcc;

		Account oldAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		oldAcc.Name = 'Old Account';
		oldAcc.Phone = '01234567891';
		oldAcc.BillingStreet = 'old account';
		oldAcc.BillingCity = 'old city';
		oldAcc.BillingPostalCode = 'aa111aa';
		oldAcc.BillingState = 'old state';
		oldAcc.BillingCountry = 'United Kingdom';
		oldAcc.Industry_Minor_Category__c = '10.05.11 - ATHLETES PULSE MONITOR';
		oldAcc.CCIMailCustID__c = null;
		oldAcc.CCIMetroCustID__c = 'testmetro123';
		oldAcc.NPA__c = false;
		oldAcc.Type = 'Direct Advertiser';

		List < String > oldAccInfo = new List < String > ();
		List < String > newAccInfo = new List < String > ();

		CCICustomerWrapper.AccountInfo ai = new CCICustomerWrapper.AccountInfo(newAcc.Id, newAcc.Name, newAcc.Phone, newAcc.BillingStreet, newAcc.BillingCity, newAcc.BillingPostalCode, newAcc.BillingState, newAcc.BillingCountry, newAcc.Industry_Minor_Category__c, newAcc.CCIMailCustID__c, newAcc.CCIMetroCustID__c, newAcc.NPA__c, newAcc.Type, '', '');
		newAccInfo.add(JSON.serialize(ai));
		CCICustomerWrapper.AccountInfo oldai = new CCICustomerWrapper.AccountInfo(newAcc.Id, oldAcc.Name, oldAcc.Phone, oldAcc.BillingStreet, oldAcc.BillingCity, oldAcc.BillingPostalCode, oldAcc.BillingState, oldAcc.BillingCountry, oldAcc.Industry_Minor_Category__c, oldAcc.CCIMailCustID__c, oldAcc.CCIMetroCustID__c, oldAcc.NPA__c, oldAcc.Type, '', '');
		oldAccInfo.add(JSON.serialize(oldai));
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		Test.startTest();
		CCICustomerWebService.getCCIAccount(newAccInfo, oldAccInfo, false);
		Test.stopTest();
	}

	private static testMethod void testgetCCIAccount_fullsync() {
		setUpData();
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		Account newAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		newAcc.Name = 'New Account';
		newAcc.Phone = '0123456789123';
		newAcc.BillingStreet = 'new account';
		newAcc.BillingCity = 'new city';
		newAcc.BillingPostalCode = 'aa111aa';
		newAcc.BillingState = 'new state';
		newAcc.BillingCountry = 'United Kingdom';
		newAcc.Industry_Minor_Category__c = '10.05.10 - HEALTH & FITNESS APPLIANCES';
		newAcc.CCIMailCustID__c = null;
		newAcc.CCIMetroCustID__c = 'testmetro123';
		newAcc.NPA__c = false;
		newAcc.Type = 'Direct Advertiser';
		newAcc.DoCCIInt__c = true;
		insert newAcc;

		Account oldAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		oldAcc.Name = 'Old Account';
		oldAcc.Phone = '01234567891';
		oldAcc.BillingStreet = 'old account';
		oldAcc.BillingCity = 'old city';
		oldAcc.BillingPostalCode = 'aa111aa';
		oldAcc.BillingState = 'old state';
		oldAcc.BillingCountry = 'United Kingdom';
		oldAcc.Industry_Minor_Category__c = '10.05.11 - ATHLETES PULSE MONITOR';
		oldAcc.CCIMailCustID__c = null;
		oldAcc.CCIMetroCustID__c = 'testmetro123';
		oldAcc.NPA__c = false;
		oldAcc.Type = 'Direct Advertiser';

		List < String > oldAccInfo = new List < String > ();
		List < String > newAccInfo = new List < String > ();

		CCICustomerWrapper.AccountInfo ai = new CCICustomerWrapper.AccountInfo(newAcc.Id, newAcc.Name, newAcc.Phone, newAcc.BillingStreet, newAcc.BillingCity, newAcc.BillingPostalCode, newAcc.BillingState, newAcc.BillingCountry, newAcc.Industry_Minor_Category__c, newAcc.CCIMailCustID__c, newAcc.CCIMetroCustID__c, newAcc.NPA__c, newAcc.Type, '', '');
		newAccInfo.add(JSON.serialize(ai));
		CCICustomerWrapper.AccountInfo oldai = new CCICustomerWrapper.AccountInfo(newAcc.Id, oldAcc.Name, oldAcc.Phone, oldAcc.BillingStreet, oldAcc.BillingCity, oldAcc.BillingPostalCode, oldAcc.BillingState, oldAcc.BillingCountry, oldAcc.Industry_Minor_Category__c, oldAcc.CCIMailCustID__c, oldAcc.CCIMetroCustID__c, oldAcc.NPA__c, oldAcc.Type, '', '');
		oldAccInfo.add(JSON.serialize(oldai));
		Test.startTest();
		CCICustomerWebService.getCCIAccount(newAccInfo, oldAccInfo, null);
		Test.stopTest();
	}

	private static testMethod void testgetCCIAccount_exceptionHandeling() {
		setUpData();
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		Account newAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		newAcc.Name = 'New Account';
		newAcc.Phone = '0123456789123';
		newAcc.BillingStreet = 'new account';
		newAcc.BillingCity = 'new city';
		newAcc.BillingPostalCode = 'aa111aa';
		newAcc.BillingState = 'new state';
		newAcc.BillingCountry = 'United Kingdom';
		newAcc.Industry_Minor_Category__c = '10.05.10 - HEALTH & FITNESS APPLIANCES';
		newAcc.CCIMailCustID__c = null;
		newAcc.CCIMetroCustID__c = 'testexception123';
		newAcc.NPA__c = false;
		newAcc.Type = 'Direct Advertiser';
		newAcc.DoCCIInt__c = true;
		insert newAcc;

		Account oldAcc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		oldAcc.Name = 'Old Account';
		oldAcc.Phone = '01234567891';
		oldAcc.BillingStreet = 'old account';
		oldAcc.BillingCity = 'old city';
		oldAcc.BillingPostalCode = 'aa111aa';
		oldAcc.BillingState = 'old state';
		oldAcc.BillingCountry = 'United Kingdom';
		oldAcc.Industry_Minor_Category__c = '10.05.11 - ATHLETES PULSE MONITOR';
		oldAcc.CCIMailCustID__c = null;
		oldAcc.CCIMetroCustID__c = 'testexception123';
		oldAcc.NPA__c = false;
		oldAcc.Type = 'Direct Advertiser';

		List < String > oldAccInfo = new List < String > ();
		List < String > newAccInfo = new List < String > ();

		CCICustomerWrapper.AccountInfo ai = new CCICustomerWrapper.AccountInfo(newAcc.Id, newAcc.Name, newAcc.Phone, newAcc.BillingStreet, newAcc.BillingCity, newAcc.BillingPostalCode, newAcc.BillingState, newAcc.BillingCountry, newAcc.Industry_Minor_Category__c, newAcc.CCIMailCustID__c, newAcc.CCIMetroCustID__c, newAcc.NPA__c, newAcc.Type, '', '');
		newAccInfo.add(JSON.serialize(ai));
		system.debug('newAccountInfo : ' + newAccInfo);
		CCICustomerWrapper.AccountInfo oldai = new CCICustomerWrapper.AccountInfo(newAcc.Id, oldAcc.Name, oldAcc.Phone, oldAcc.BillingStreet, oldAcc.BillingCity, oldAcc.BillingPostalCode, oldAcc.BillingState, oldAcc.BillingCountry, oldAcc.Industry_Minor_Category__c, oldAcc.CCIMailCustID__c, oldAcc.CCIMetroCustID__c, oldAcc.NPA__c, oldAcc.Type, '', '');
		oldAccInfo.add(JSON.serialize(oldai));
		Test.startTest();
		CCICustomerWebService.getCCIAccount(newAccInfo, oldAccInfo, null);
		Test.stopTest();
	}
}