src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCIMailCustID__c</fullName>
        <externalId>true</externalId>
        <label>CCIMailCustID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Advertiser</fullName>
        <active>true</active>
        <description>Please use this record type to create an Advertiser.</description>
        <label>Advertiser</label>
    </recordTypes>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/classes/OrderCreationTest.cls
@isTest(SeeAllData = true)
private class OrderCreationTest {
	static{
		BookingSystemSettings__c bSS = BookingSystemSettings__c.getInstance('CCI');
		if (bSS == null) insert TestData.createBookingSystemSettings();
		if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
			insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
		}
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
	}
	static testmethod void OrderCreationTests() {
		//  setUpData(); 
		Account acc = TestData.buildAccount('Advertiser', 'Direct Advertiser');
		insert acc;
		Account billingAcc = new Account();
		billingAcc.Name = 'BillingAgency';
		billingAcc.Type = 'Billing Agency';
		billingAcc.Phone = '0208426234';
		billingAcc.BillingStreet = 'testStreet2';
		billingAcc.BillingPostalCode = 'ha5 4re';
		Id agencyRecordTypeId = Account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Agency').RecordTypeId;
		billingAcc.RecordTypeId = agencyRecordTypeId;
		// billingAcc.CCIMailCustID__c = '1';
		insert billingAcc;

		Account bookingAcc = new Account();
		bookingAcc.Name = 'Booking Agency';
		bookingAcc.Type = 'Booking Agency';
		bookingAcc.Phone = '0208426234';
		bookingAcc.BillingStreet = 'testStreet2';
		bookingAcc.BillingPostalCode = 'ha5 4re';
		bookingAcc.RecordTypeId = agencyRecordTypeId;
		//        bookingAcc.CCIMailCustID__c = '1';
		insert bookingAcc;
		OrderCreation plugin = new OrderCreation();

		Map < String, Object > inputParams = new Map < String, Object > ();
		InputParams.put('Id', acc.id);
		InputParams.put('BookingAgency', bookingAcc.id);
		InputParams.put('BillingAgency', billingAcc.id);
		Test.startTest();
		plugin.describe();
		Process.PluginRequest request = new Process.PluginRequest(inputParams);
		plugin.invoke(request);
		Test.stopTest();
	}


}