src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Please select this record type to create an Agency.</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/objects/Business_Team_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Team Activities</relationshipLabel>
        <relationshipName>Business_Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Team Activity</label>
    <nameField>
        <label>Business Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Team Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Constants__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Advertiser_Record_Type__c</fullName>
        <defaultValue>&apos;Advertiser&apos;</defaultValue>
        <label>Advertiser Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Record_Type__c</fullName>
        <defaultValue>&apos;Agency&apos;</defaultValue>
        <label>Agency Record Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Constants</label>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts / Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H.R.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FInance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Agency account type should be Agency or Direct Advertiser and it needs to be Active.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Direct Advertiser,Billing Agency,Charity,Private Advertiser,Brand, Booking Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pitches (Agency)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Lead Ad Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product (Account)</relationshipLabel>
        <relationshipName>Opportunity_Product1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Specification__c</fullName>
        <label>Color Specification</label>
        <picklist>
            <picklistValues>
                <fullName>Mono</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>false</active>
        <description>DO NOT ACTIVATE</description>
        <label>Test</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PitchHubController_Test.cls
@isTest(SeeAllData = true)
private class PitchHubController_Test {
	static{
		BookingSystemSettings__c bSS = BookingSystemSettings__c.getInstance('CCI');
		if (bSS == null) insert TestData.createBookingSystemSettings();
		if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
			insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
		}
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
	}
	static testMethod void testPitchHub() {
		User testUser = [
		Select name, email, ProfileId, Profile.Name
		From User
		Where isActive = true /*and managerId != null*/
		And Profile.Name = 'System Administrator'
		Limit 1];

		List < SelectOption > productOptions;
		List < SelectOption > stageOptions;
		List < SelectOption > roleOptions;
		List < OpportunityLineItem > oppLine;
		List < SelectOption > noOfProducts;
		List < SelectOption > dateIncrement;

		OpportunityContactRole cr = new OpportunityContactRole();

		Pricebook2 testPB = [Select
		name
		From Pricebook2
		Where isActive = true
		Limit 1];

		String testProfileId = [Select id
		From Profile
		Limit 1].id;


		//#  
		//# Ensure that the test results will not depend
		//# on running user's Custom Settings
		//# 

		ConstantsH__c constH = [
		select Name, Price_Book__c, Acc_and_Contact_owner__c
		from ConstantsH__c
		where SetupOwnerId = : testUser.ProfileId
		limit 1];
		delete constH;

		ConstantsH__c newConstH = new ConstantsH__c(
		Acc_and_Contact_owner__c = testUser.Name,
		Department__c = 'None',
		IsManager__c = false,
		Price_Book__c = testPB.Name,
		SetupOwnerId = testUser.ProfileId);
		insert newConstH;


		String advertiserRecTypeId = [
		Select id
		From RecordType
		Where DeveloperName = : Constants__c.getInstance('All').Advertiser_Record_Type__c].id;

		String agencyRecTypeId = [
		Select id
		From RecordType
		Where DeveloperName = : Constants__c.getInstance('All').Agency_Record_Type__c
		Limit 1].id;

		Account acct = new Account(
		Name = 'Test Account',
		AccountNumber = 'ABC123456',
		Type = 'Client',
		Industry = 'Finance',
		RecordTypeId = advertiserRecTypeId,
		BillingCountry = 'United Kingdom');
		insert acct;

		Account agency = new Account(
		Name = 'Test Agency',
		AccountNumber = 'AGN123456',
		Type = 'Billing Agency',
		Industry = 'Finance',
		RecordTypeId = agencyRecTypeId,
		BillingStreet = '1',
		BillingPostalCode = 'a111aa',
		Phone = '01236547896',
		BillingCountry = 'United Kingdom');
		insert agency;

		Contact cnt = new Contact();
		cnt.AccountId = acct.Id;
		cnt.LastName = 'Test Last Name';
		cnt.FirstName = 'Test First Name';
		cnt.MailingCity = 'Test Mailing City';
		cnt.MailingCountry = 'Test Mailing Country';
		cnt.MailingPostalCode = 'TestMPC';
		cnt.MailingState = 'Test Mailing State';
		cnt.MailingStreet = 'Test Mailing Street';
		cnt.MailingCountry = 'United Kingdom';
		insert cnt;

		Pricebook2 priceBook = [
		Select
		p.Name
		From Pricebook2 p
		Where p.Name = : newConstH.Price_Book__c
		Limit 1];


		PricebookEntry priceBookEntry = [
		Select
		name,
		Product2Id
		From PricebookEntry
		Where pricebook2Id = : priceBook.Id
		limit 1];


		PitchHubController cPHC;


		Test.startTest();

		system.runAs(testUser) {

			Business_Team_Activity__c bta = [Select id From Business_Team_Activity__c Where Account__c = : acct.Id Limit 1];
			Event event = new Event(whatid = bta.id, DurationInMinutes = 30, ActivityDateTime = Date.today());
			insert event;
			Task tsk = new Task(whatid = bta.id);
			insert tsk;

			PageReference pageRef = Page.PitchHub;
			pageRef.getParameters().put('Contactid', cnt.Id);
			pageRef.getParameters().put('Eventid', event.Id);
			pageRef.getParameters().put('Activityid', tsk.Id);
			Test.setCurrentPageReference(pageRef);

			Date d1PastFirstInsertionDates = Date.today().addDays(-1);
			Date d2FirstInsertionDates = Date.today().addDays(5);
			Date d3FirstInsertionDates = Date.today().addDays(10);

			String sArrFirstInsertionDatesWithPastDates;
			sArrFirstInsertionDatesWithPastDates = d1PastFirstInsertionDates.format() + ',' + d2FirstInsertionDates.format() + ',' + d3FirstInsertionDates.format();

			String sArrFirstInsertionDatesWithoutPastDates;
			sArrFirstInsertionDatesWithoutPastDates = d2FirstInsertionDates.format() + ',' + d3FirstInsertionDates.format();


			for (Integer i = 0; i < 2; i++) {

				cPHC = new PitchHubController();
				OpportunityLineItem sOppLineItem = new OpportunityLineItem();

				productOptions = cPHC.getProductOptions();
				stageOptions = cPHC.getStageOptions();
				roleOptions = cPHC.roleOptions;

				cPHC.stageSelectList = 'Preparation';

				cPHC.account = acct;
				cPHC.opportunity.AccountId = acct.Id;
				cPHC.opportunity.Type = 'Proactive';
				cPHC.opportunity.CloseDate = date.today();
				cPHC.opportunity.Name = 'Test Oppty';
				cPHC.opportunity.Agency__c = agency.Id;

				cPHC.contactRole = new OpportunityContactRole();
				//cPHC.contactRole.ContactId  = cnt.id;

				cPHC.productsSelectList = priceBookEntry.Product2Id;

				if (i == 0) cPHC.SelectedInsertionDates = (String) sArrFirstInsertionDatesWithPastDates;
				else if (i == 1) cPHC.SelectedInsertionDates = (String) sArrFirstInsertionDatesWithoutPastDates;

				sOppLineItem.PricebookEntryId = priceBookEntry.Product2Id;
				sOppLineItem.Description = 'Test Description';
				sOppLineItem.UnitPrice = 1000;
				//sOppLineItem.ServiceDate                = date.today().addDays(5);    
				sOppLineItem.Quantity = 1;
				sOppLineItem.Brand__c = 'Special Brand';
				sOppLineItem.Color_Specification__c = 'Color';
				sOppLineItem.Region__c = 'National';
				sOppLineItem.Size__c = '24x4';
				sOppLineItem.Position__c = 'Front Page';


				cPHC.save();


				List < Opportunity > opList = [
				Select
				Id
				From Opportunity
				Where AccountId = : acct.Id];


				List < OpportunityLineItem > oplList = [
				Select
				Id
				From OpportunityLineItem
				Where Opportunity.AccountId = : acct.Id];

				/*
                if(i == 0){                
                    System.assertEquals(0, opList.size());
                    System.assertEquals(0, oplList.size());               
                }
                else if(i == 1){
                    System.assertEquals(1, opList.size());
                    System.assertEquals(2, oplList.size());
                }
                */

			}

			cPHC.cancel();

		}


		newConstH.Price_Book__c = 'None';
		update newConstH;


		system.runAs(testUser) {
			cPHC = new PitchHubController();
			productOptions = cPHC.getProductOptions();
		}


		Test.stopTest();

	}
}