src/objects/BookingSystemCountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping Table to Convert Glue Countries to CCI Country Codes</description>
    <label>BookingSystemCountryCodes</label>
</CustomObject>

src/objects/BookingSystemSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Booking System Integration</description>
    <label>BookingSystemSettings</label>
</CustomObject>

src/objects/Constants__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Advertiser_Record_Type__c</fullName>
        <defaultValue>&apos;Advertiser&apos;</defaultValue>
        <label>Advertiser Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Record_Type__c</fullName>
        <defaultValue>&apos;Agency&apos;</defaultValue>
        <label>Agency Record Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Constants</label>
</CustomObject>

src/objects/Deal_Product__c.object
<CustomObject>
    <description>Used for the price and commission information for the deal info on single and multiple price point deals.</description>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <formula>( Product_Usual_Selling_Price__c - Product_price__c )/ Product_Usual_Selling_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Pitch</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Products</relationshipLabel>
        <relationshipName>Deal_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Cap__c</fullName>
        <label>Cap</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Media_Surcharge__c</fullName>
        <label>Media Surcharge</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Supplier_Rate__c</fullName>
        <label>Supplier % Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Supplier_Unredeemed_Rate__c</fullName>
        <label>Supplier Unredeemed % Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Usual_Selling_Price__c</fullName>
        <label>Usual Selling Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Wowcher_Commission__c</fullName>
        <formula>1 -  Product_Supplier_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wowcher Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_price__c</fullName>
        <label>Deal Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Deal Product</label>
    <nameField>
        <label>Deal Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Products__c</fullName>
        <label>Deal Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deal_Region__c</fullName>
        <label>Deal Region</label>
        <picklist>
            <picklistValues>
                <fullName>Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <formula>(Usual_Selling_Price__c - Amount) /  Usual_Selling_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Followup_Due_Date__c</fullName>
        <label>Followup Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Followup_Subject__c</fullName>
        <label>Followup Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DealProduct_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */@isTest(SeeAllData = true)
private class DealProduct_Test {
	static{
		BookingSystemSettings__c bSS = BookingSystemSettings__c.getInstance('CCI');
		if (bSS == null) insert TestData.createBookingSystemSettings();
		if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
			insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
		}
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();
	}
	static testMethod void testDealProduct() {
		// TO DO: implement unit test
		String advertiserRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants__c.getInstance('All').Advertiser_Record_Type__c).getRecordTypeId();
		String agencyRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants__c.getInstance('All').Agency_Record_Type__c).getRecordTypeId();
		String wowcherEcommOppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Wowcher Merchant (ecomm)').getRecordTypeId();

		Profile p;
		try {
			p = [SELECT Id FROM Profile WHERE Name = 'Wowcher User'];
		} catch (QueryException e) {

		}

		User u = new User(Alias = 'wuser', Email = 'wowcheruser@wowcher.com',
		EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
		LocaleSidKey = 'en_US', ProfileId = p.Id,
		TimeZoneSidKey = 'America/Los_Angeles', UserName = 'wowcheruser@wowcher.com');

		insert u;


		Account acctAdv = new Account(
		Name = 'Test Account',
		AccountNumber = 'ABC123456',
		Type = 'Client',
		BillingStreet = 'Street',
		BillingState = 'TestState',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'City',
		Industry = 'Finance',
		RecordTypeId = advertiserRecTypeId);
		insert acctAdv;

		Account acctAgency = new Account(
		Name = 'Test Account2',
		AccountNumber = 'ABC1234562',
		RecordTypeId = agencyRecTypeId,
		BillingStreet = 'Street',
		BillingState = 'TestState',
		BillingPostalCode = 'A111AA',
		BillingCountry = 'United Kingdom',
		BillingCity = 'City',
		ownerId = u.Id,
		Phone = '1236547896');
		insert acctAgency;

		//System.runAs(u)
		{
			Opportunity oppty = new Opportunity(
			Name = 'Test Oppty',
			AccountId = acctAdv.id,
			StageName = 'Final Negotiations',
			CloseDate = Date.today(),
			LeadSource = 'Organic - Google',
			// OwnerId              = testUser.Id,
			Followup_Due_Date__c = Date.today().addDays(4),
			Followup_Subject__c = 'Test Subject',
			RecordTypeId = wowcherEcommOppRecTypeId,
			Deal_Region__c = 'Scotland');

			insert oppty;

			Deal_Product__c dealProduct = new Deal_Product__c(
			Name = 'New Product',
			Opportunity__c = oppty.Id,
			Product_Price__c = 100,
			Product_Usual_Selling_Price__c = 120,
			Product_Supplier_Rate__c = 0.05,
			Product_Media_Surcharge__c = 0.02,
			Product_Cap__c = 98);

			insert dealProduct;

			Deal_Product__c checkDealProduct = [
			Select
			Name,
			Opportunity__c,
			Product_Price__c,
			Product_Usual_Selling_Price__c,
			Product_Supplier_Rate__c,
			Product_Media_Surcharge__c,
			Product_wowcher_commission__c,
			Product_Cap__c,
			Product_supplier_unredeemed_rate__c,
			Product_description__c,
			discount_percentage__c
			From Deal_Product__c
			Where Id = : dealProduct.Id];

			Opportunity checkOpportunity = [
			Select Deal_Products__c
			From Opportunity
			Where Id = : oppty.Id];


			String prodMediaSurcharge;
			String prodSupplierUnredeemedRate;

			if (checkDealProduct.Product_media_surcharge__c != Null) {
				prodMediaSurcharge = ', Media Surcharge: ' + checkDealProduct.Product_media_surcharge__c;
			} else {
				prodMediaSurcharge = '';
			}


			if (checkDealProduct.Product_supplier_unredeemed_rate__c != Null) {
				prodSupplierUnredeemedRate = ', Supplier Unredeemed Rate: ' + checkDealProduct.Product_supplier_unredeemed_rate__c + '%';
			} else {
				prodSupplierUnredeemedRate = '';
			}



			String dealCompare = ('Product Title: ' + checkDealProduct.Name + ', Deal Price: £' + checkDealProduct.Product_price__c + ', Usual Selling Price: £' + checkDealProduct.product_usual_selling_price__c + ', Discount Percentage: ' + checkDealProduct.discount_percentage__c + '%' + ', Deal Cap: ' + checkDealProduct.Product_Cap__c + ', Supplier Percentage Rate: ' + checkDealProduct.Product_supplier_rate__c + '%' + '\r\n\r\n\r\n');



			System.debug('dealCompare:' + dealCompare);
			System.debug('checkOpportunity.Deal_Products__c:' + checkOpportunity.Deal_Products__c);
			System.debug('dealCompare:' + dealCompare.trim().length());
			System.debug('checkOpportunity.Deal_Products__c:' + checkOpportunity.Deal_Products__c.trim().length());
			//System.assertEquals(checkOpportunity.Deal_Products__c.trim(), dealCompare.trim());


		}
	}
}