src/objects/Business_Team_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Team Activities</relationshipLabel>
        <relationshipName>Business_Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Team Activity</label>
    <nameField>
        <label>Business Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Team Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateAccountBTAsController.cls
/**
	Page to create Business Team Activities for Account.
*/
public with sharing class CreateAccountBTAsController {

	private final Account a { get; set; }
	public boolean HasBTAs { get; set; }
	
	public CreateAccountBTAsController(ApexPages.StandardController stdController)
	{
		this.a = (Account)stdController.getRecord();
		this.HasBTAs = [select count() from Business_Team_Activity__c where account__c = :this.a.id] > 0;
	}
	
	public PageReference CreateBTAs()
	{
		try
		{
			AccountBTAsUtility.CreateBTAs(a.id);
			return RedirectToAccountPage();
		}
		catch(Exception ex)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
			return null;
		}
	}
	
	public PageReference CancelCreateBTAs()
	{
		return RedirectToAccountPage();
	}
	
	private PageReference RedirectToAccountPage()
	{
		PageReference pr = new ApexPages.StandardController(a).view();
		pr.setRedirect(true);
		return pr;
	}
}