src/objects/Business_Team_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Team Activities</relationshipLabel>
        <relationshipName>Business_Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Team Activity</label>
    <nameField>
        <label>Business Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Team Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/classes/ViewBTAHistoryController.cls
public with sharing class ViewBTAHistoryController {
 
 //private ApexPages.StandardController controller;
 public Account acc;
 static User testUser  = 
            [
            select id, name, email, ProfileId, Profile.Name 
            from User 
            where isActive = true /*and managerId != null*/ and Profile.Name = 'System Administrator' 
        limit 1
        ];
            
 public ViewBTAHistoryController(ApexPages.StandardController std1controller) {
        this.acc= (Account)std1Controller.getRecord();
 }
 
    
String currentUser=UserInfo.getUserId() ; 
String currentUserProfile=UserInfo.getProfileId(); 
 
ConstantsH__c ch    = ConstantsH__c.getInstance(UserInfo.getProfileId());
Public String Department =  ch.Department__c;



public List <Business_Team_Activity__c> AllBTAActivity {
        get{
            if(AllBTAActivity == null) {
                
                AllBTAActivity = [select 
                                    id, name 
                                    from Business_Team_Activity__c
                                    where Business_Team_Activity__c.Account__c= :acc.id 
                                    and Business_Team_Activity__c.name = :acc.name + ' ('+Department+')'];
            }
            return AllBTAActivity;
        }
        set;    
    }



public List<Task> acthist {
    get {
    if(acthist == null) {

        acthist =[Select Subject,
                         ActivityDate,
                         Description,
                         Status,
                         OwnerId,
                         WhoId
                        // ,Who.Name 
                    From Task
                    Where Task.WhatId= :AllBTAActivity[0].id and Task.Status!= 'Completed'
                    Order By ActivityDate ASC
                    Limit 100];
         List<Task> acthistCompleted =[Select Subject,
                         ActivityDate,
                         Description,
                         Status,
                         OwnerId,
                         WhoId
                        // ,Who.Name 
                    From Task
                    Where Task.WhatId= :AllBTAActivity[0].id and Task.Status= 'Completed'
                    Order By ActivityDate ASC
                    Limit 100];           
         acthist.addAll(acthistCompleted);           
         }
            return acthist;
        }
        set;
}

public List<Event> acteventhist {
    get {
    if(acteventhist == null) {

        acteventhist =[Select Subject,
                         ActivityDate,
                         Description,
                         OwnerId,
                         WhoId
                        // ,Who.Name 
                    From Event
                    Where Event.WhatId= :AllBTAActivity[0].id
                    Order By ActivityDate DESC
                    Limit 100];
         }
            return acteventhist;
        }
        set;
}



public List<Task> getactivityPagination() {
         return acthist;
    }
public List<Event> geteventactivityPagination() {
         return acteventhist;
    }    
}