src/objects/Constants__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Advertiser_Record_Type__c</fullName>
        <defaultValue>&apos;Advertiser&apos;</defaultValue>
        <label>Advertiser Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Record_Type__c</fullName>
        <defaultValue>&apos;Agency&apos;</defaultValue>
        <label>Agency Record Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regular_Opp_Record_Type__c</fullName>
        <defaultValue>&apos;New_Business&apos;</defaultValue>
        <label>Regular Opp Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Constants</label>
</CustomObject>

src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/Inactive_Pitch_Idea__c.object
<CustomObject>
    <description>Pitches - individual options given to clients</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomerRef__c</fullName>
        <label>CustomerRef</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Ideas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Inactive2__c</fullName>
        <label>Reason for Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Activity already booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity discussed as value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business titles only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign date moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Date moved Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn’t Use Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free/House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea Not Suited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to A&amp;N Media Brand Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mids Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed a tactical opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not core to activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed to classified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pops Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quails Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quals only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong target audience</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ServiceDate__c</fullName>
        <label>First Insertion Date</label>
        <type>Date</type>
    </fields>
    <label>Inactive Product</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>Inactive Pitch Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inactive Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Agency account type should be Agency or Direct Advertiser and it needs to be Active.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Direct Advertiser,Billing Agency,Charity,Private Advertiser,Brand, Booking Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pitches (Agency)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomerRef__c</fullName>
        <label>CustomerRef</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Inactive2__c</fullName>
        <label>Reason for Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Activity already booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity discussed as value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business titles only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign date moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Date moved Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn’t Use Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free/House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea Not Suited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to A&amp;N Media Brand Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mids Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed a tactical opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Creative Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not core to activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed to classified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pops Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quails Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quals Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong target audience</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CustomerRef__c</fullName>
        <label>CustomerRef</label>
        <picklist>
            <picklistValues>
                <fullName>CustomerRef1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerRef5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/ActivateDeactivatePitchIdeaContr_Test.cls
@isTest
private class ActivateDeactivatePitchIdeaContr_Test {

	static User testUser = [select id, name, email, ProfileId, Profile.Name
							from User
							where isActive = true and managerId != null /*and Profile.Name = 'System Administrator'*/
							limit 1];

	static OpportunityLineItem CreateTestOpportunity() {
		if (BookingSystemSettings__c.getAll().get('CCI') == null) {
			insert TestData.createBookingSystemSettings();
		}
		if (BookingSystemCountryCodes__c.getAll().get('United Kingdom') == null) {
			insert TestData.createCountryCodeSetting('United Kingdom', 'UK');
		}
		insert TestData.buildCompany();
		insert TestData.buildMetroCompany();

		Map < String, RecordTypeInfo > opportunityRecTypeByName = Opportunity.SObjectType.getDescribe().getRecordTypeInfosByName();

		System.debug(opportunityRecTypeByName);
		System.debug('Regular_Opp_Record_Type__c:' + Constants__c.getInstance('All').Regular_Opp_Record_Type__c);

		String opportunityRecTypeId = opportunityRecTypeByName.get('Pitch').RecordTypeId;
		Map < String, RecordTypeInfo > accountRecTypeByName = Account.SObjectType.getDescribe().getRecordTypeInfosByName();

		String advertiserRecTypeId = accountRecTypeByName.get(Constants__c.getInstance('All').Advertiser_Record_Type__c).RecordTypeId;
		String agencyRecTypeId = accountRecTypeByName.get(Constants__c.getInstance('All').Agency_Record_Type__c).RecordTypeId;

		Pricebook2 testPB = [select id, name from Pricebook2 where isActive = true limit 1];
		String testProfileId = [select id from Profile limit 1].id;
		User manager = [select id, name from User where isActive = true and id != : testUser.Id limit 1];

		//#  
		//# Ensure that the test results will not depend
		//# on running user's Custom Settings
		//# 
		ConstantsH__c constH = [select id, Name, Price_Book__c, Acc_and_Contact_owner__c
								from ConstantsH__c
								where SetupOwnerId = : testUser.ProfileId
								limit 1];
		delete constH;

		ConstantsH__c newConstH = new ConstantsH__c(Acc_and_Contact_owner__c = testUser.Name,
													Department__c = 'None',
													IsManager__c = false,
													Price_Book__c = testPB.Name,
													SetupOwnerId = testUser.ProfileId);
		insert newConstH;

		list < Account > accountsList = new list < Account > ();
		Account acct = new Account(Name = 'Test Account',
									AccountNumber = 'ABC123456',
									Industry = 'Finance',
									Type = 'Booking Agency',
									BillingStreet = 'Agency Street',
									BillingState = 'Agency TestState',
									BillingPostalCode = 'A111AA',
									BillingCountry = 'United Kingdom',
									BillingCity = 'Agency City',
									RecordTypeId = advertiserRecTypeId,
									Phone = '012364788996');
									accountsList.add(acct);

		Account acct2 = new Account(Name = 'Test Adv',
									AccountNumber = 'ABC1234562',
									Industry = 'Finance',
									Type = 'Direct Advertiser',
									BillingStreet = 'Street',
									BillingState = 'TestState',
									BillingPostalCode = 'A111AA',
									BillingCountry = 'United Kingdom',
									BillingCity = 'City',
									RecordTypeId = advertiserRecTypeId,
									Phone = '01236547891');
		accountsList.add(acct2);

		Account acct3 = new Account(Name = 'Test Agency',
									AccountNumber = 'ABC1234563',
									Industry = 'Finance',
									Type = 'Billing Agency',
									BillingStreet = 'Street',
									BillingState = 'TestState',
									BillingPostalCode = 'A111AA',
									BillingCountry = 'United Kingdom',
									BillingCity = 'City',
									RecordTypeId = agencyRecTypeId,
									Phone = '01236547896');
		accountsList.add(acct3);
		insert accountsList;
		Opportunity oppty = new Opportunity(Name = 'Test Oppty',
											recordTypeId = opportunityRecTypeId,
											AccountId = acct.id,
											Agency__c = acct3.id,
											StageName = 'Final Negotiations',
											CloseDate = Date.today(),
											LeadSource = 'Organic - Google',
											Type = 'Proactive',
											OwnerId = testUser.id);
		try {
			insert oppty;
		} catch (exception e) {
			system.debug('>>>>>>>>>>>>>>>>> Exception : ' + e.getMessage());
		}
		//#
		//# Create and insert all test products
		//#

		List < Product2 > newProducts = new List < Product2 > ();

		Product2 tmpproduct1 = new Product2();
		tmpproduct1.IsActive = true;
		tmpproduct1.Family = 'Test Family1';
		tmpproduct1.Name = 'Test product1';
		tmpproduct1.CustomerRef__c = 'CustomerRef1';
		newProducts.add(tmpProduct1);

		Product2 tmpproduct2 = new Product2();
		tmpproduct2.IsActive = true;
		tmpproduct2.Family = 'Test Family2';
		tmpproduct2.Name = 'Test product2';
		tmpproduct2.CustomerRef__c = 'CustomerRef2';
		newProducts.add(tmpProduct2);

		Product2 tmpproduct3 = new Product2();
		tmpproduct3.IsActive = true;
		tmpproduct3.Family = 'Test Family3';
		tmpproduct3.Name = 'Test product3';
		tmpproduct3.CustomerRef__c = 'CustomerRef3';
		newProducts.add(tmpProduct3);

		Product2 tmpproduct4 = new Product2();
		tmpproduct4.IsActive = true;
		tmpproduct4.Family = 'Test Family4';
		tmpproduct4.Name = 'Test product4';
		tmpproduct4.CustomerRef__c = 'CustomerRef4';
		newProducts.add(tmpProduct4);

		Product2 tmpproduct5 = new Product2();
		tmpproduct5.IsActive = true;
		tmpproduct5.Family = 'Test Family5';
		tmpproduct5.Name = 'Test product5';
		tmpproduct5.CustomerRef__c = 'CustomerRef5';
		newProducts.add(tmpProduct5);


		insert newProducts;

		Pricebook2 standardPB = [select id from Pricebook2 where isStandard = true];

		//#
		//# Create and insert all test pricebook entries
		//# 

		List < PricebookEntry > newPricebookEntries = new List < PricebookEntry > ();

		PricebookEntry newPBE1 = new PricebookEntry(
		Product2Id = tmpproduct1.id,
		isActive = true,
		//  PriceBook2Id                = priceBook.id,
		PriceBook2Id = standardPB.id,
		UnitPrice = 100.0,
		UseStandardPrice = false);
		newPricebookEntries.add(newPBE1);

		PricebookEntry newPBE2 = new PricebookEntry(
		Product2Id = tmpproduct2.id,
		isActive = true,
		//PriceBook2Id              = priceBook.id,
		PriceBook2Id = standardPB.id,
		UnitPrice = 200.0,
		UseStandardPrice = false);
		newPricebookEntries.add(newPBE2);

		PricebookEntry newPBE3 = new PricebookEntry(
		Product2Id = tmpproduct3.id,
		isActive = true,
		//PriceBook2Id              = priceBook.id,
		PriceBook2Id = standardPB.id,
		UnitPrice = 300.0,
		UseStandardPrice = false);
		newPricebookEntries.add(newPBE3);

		PricebookEntry newPBE4 = new PricebookEntry(
		Product2Id = tmpproduct4.id,
		isActive = true,
		//PriceBook2Id              = priceBook.id,
		PriceBook2Id = standardPB.id,
		UnitPrice = 400.0,
		UseStandardPrice = false);
		newPricebookEntries.add(newPBE4);

		PricebookEntry newPBE5 = new PricebookEntry(
		Product2Id = tmpproduct5.id,
		isActive = true,
		//PriceBook2Id              = priceBook.id,
		PriceBook2Id = standardPB.id,
		UnitPrice = 500.0,
		UseStandardPrice = false);
		newPricebookEntries.add(newPBE5);


		insert newPricebookEntries;



		//#
		//# test Notifications (AllOpportunityLineItemTriggers)
		//#

		List < OpportunityLineItem > newOLIs = new List < OpportunityLineItem > ();

		OpportunityLineItem opplineitem1 = new OpportunityLineItem();
		opplineitem1.OpportunityId = oppty.Id;
		opplineitem1.Quantity = 10;
		opplineitem1.UnitPrice = 100;
		opplineitem1.PricebookEntryId = newPBE1.Id;
		opplineitem1.ServiceDate = date.today() + 5;
		opplineitem1.active__c = true;
		newOLIs.add(opplineitem1);

		OpportunityLineItem opplineitem2 = new OpportunityLineItem();
		opplineitem2.OpportunityId = oppty.Id;
		opplineitem2.Quantity = 10;
		opplineitem2.UnitPrice = 100;
		opplineitem2.PricebookEntryId = newPBE2.Id;
		opplineitem2.ServiceDate = date.today() + 5;
		opplineitem1.active__c = true;
		newOLIs.add(opplineitem2);

		OpportunityLineItem opplineitem3 = new OpportunityLineItem();
		opplineitem3.OpportunityId = oppty.Id;
		opplineitem3.Quantity = 10;
		opplineitem3.UnitPrice = 100;
		opplineitem3.PricebookEntryId = newPBE3.Id;
		opplineitem3.ServiceDate = date.today() + 5;
		opplineitem1.active__c = true;
		newOLIs.add(opplineitem3);

		OpportunityLineItem opplineitem4 = new OpportunityLineItem();
		opplineitem4.OpportunityId = oppty.Id;
		opplineitem4.Quantity = 10;
		opplineitem4.UnitPrice = 100;
		opplineitem4.PricebookEntryId = newPBE4.Id;
		opplineitem4.ServiceDate = date.today() + 5;
		opplineitem1.active__c = true;
		newOLIs.add(opplineitem4);

		OpportunityLineItem opplineitem5 = new OpportunityLineItem();
		opplineitem5.OpportunityId = oppty.Id;
		opplineitem5.Quantity = 10;
		opplineitem5.UnitPrice = 100;
		opplineitem5.PricebookEntryId = newPBE5.Id;
		opplineitem5.ServiceDate = date.today() + 5;
		opplineitem1.active__c = true;
		newOLIs.add(opplineitem5);


		system.runAs(testUser) {
			insert newOLIs;
		}

		newConstH.IsManager__c = true;
		update newConstH;

		System.debug('newOLIs[0]:' + newOLIs[0]);

		return newOLIs[0];

	}



	static testMethod void ActivateDeactivatePitchIdeaContrTest() {

		List < Selectoption > inactiveOpts;
		List < Selectoption > lostToCompOptions;


		OpportunityLineItem oli = CreateTestOpportunity();


		ApexPages.currentPage().getParameters().put('id', oli.Id);
		Apexpages.Standardcontroller stdCon = new Apexpages.Standardcontroller(oli);


		Test.startTest();


		system.runAs(testUser) {

			ActivateDeactivatePitchIdeaController adpic = new ActivateDeactivatePitchIdeaController(stdCon);

			inactiveOpts = adpic.getInactiveOpts();
			lostToCompOptions = adpic.getLostToCompOpts();
			adpic.oli = oli;
			System.debug('pitchIdeaId:' + adpic.pitchIdeaId);

			//#
			//# Deactivate Pitch Idea (cover all possibilities)
			//#

			adpic.Deactivate();

			System.debug('oli:' + oli);

			adpic.inactiveReason = 'Lost to Competitor';
			adpic.Deactivate();
			System.debug('oli:' + oli);

			adpic.competitorTitle = 'Mobile';
			adpic.Deactivate();
			System.debug('oli:' + oli);


			//#
			//# Activate deactivated Pitch Idea (cover all possibilities)
			//#

			Inactive_Pitch_Idea__c ipi = [
			select id, name, Reason_for_Inactive2__c, Opportunity__c, Opportunity__r.Id, Opportunity__r.CloseDate, ServiceDate__c
			from Inactive_Pitch_Idea__c
			//where Reason_for_Inactive2__c = 'Lost to Competitor' and Competitor_Title__c = 'Mobile' 
			limit 1];

			System.debug('ipi:' + ipi);
			ApexPages.currentPage().getParameters().put('id', ipi.Id);


			Apexpages.Standardcontroller stdCon2 = new Apexpages.Standardcontroller(ipi);
			ActivateDeactivatePitchIdeaController adpic2 = new ActivateDeactivatePitchIdeaController(stdCon2);


			ipi.ServiceDate__c = date.today() - 10;
			try {
				update ipi;
			} catch (Exception e) {
				system.debug('>>>>>>>>>>>>>>>>>> Exception : ' + e.getMessage());
			}


			ipi.ServiceDate__c = date.today() + 20;
			ipi.Cost__c = 10000;
			update ipi;


			adpic2.Activate();

			adpic.cancel();

		}


		Test.stopTest();

	}
}