src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts / Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H.R.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FInance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_Team__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Teams</relationshipLabel>
        <relationshipName>Contact_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Internal_User_Role__c</fullName>
        <formula>Internal_User__r.UserRole.Name</formula>
        <label>User Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Department__c</fullName>
        <label>User Department</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Contact Team</label>
    <nameField>
        <displayFormat>CTM-{0000}</displayFormat>
        <label>Contact Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddUserToContactTeam.cls
// Apex class which adds the user to a contact team of a specific contact

public with sharing class AddUserToContactTeam {
    
    public Id ContactID {get;set;}
    
    public AddUserToContactTeam(){
        ContactID   =   ApexPages.currentPage().getParameters().get('Id');
    }

    public PageReference AddToContactTeam(){
        
        
        // System.debug('Contact ID:'+ContactID);
        ConstantsH__c ch                    = ConstantsH__c.getInstance(UserInfo.getProfileId());   
        List<Contact_Team__c> lContactTeams = [SELECT Id, Internal_User__c, User_Department__c, Internal_User_Role__c
                                               FROM contact_team__c where Contact__c = :ContactID  and Internal_User__c =: UserInfo.getUserId()];
        // System.debug('Contact Team Size:'+lContactTeams);
        
        // Check if the user is a member of the contact team. If yes - no action needed. If no - add user to the contact team. 
        
        if(lContactTeams.size() == 0){
            Contact_Team__c sContactTeam    =   new Contact_Team__c();
            sContactTeam.Contact__c         =   ContactID;
            sContactTeam.Internal_User__c   =   UserInfo.getUserId();
            sContactTeam.User_Department__c =   ch.Department__c;
            
            try{
                insert  sContactTeam;
            }
            catch(Exception e){
                return null;
            }
                        
        }
        
        PageReference contactPage = new PageReference('/'+ContactID);
        contactPage.setRedirect(true);
     
        return contactPage;     

                                               
        
    }

@isTest(SeeAllData=true)
 private static void testAddUserToContactTeam()
    {
       User testUser  = 
                [
                Select name, email, ProfileId, Profile.Name 
                From User 
                Where isActive = true /*and managerId != null*/ 
                And Profile.Name = 'System Administrator' 
                Limit 1
                ];

 
        Contact sContact = new Contact(FirstName='Jane', LastName='Doe');
        insert sContact;
        // Contact sContact = [select id from contact order by createddate desc limit 1];

        Test.startTest();
            system.runAs(testUser)
            {
                PageReference pageRef = Page.AddUserToContactTeam;
                Test.setCurrentPageReference(pageRef);
                
                ApexPages.currentPage().getParameters().put('Id', sContact.id);
                        
                AddUserToContactTeam    oAUTCT = new AddUserToContactTeam();
                oAUTCT.AddToContactTeam();
                
             }
        Test.stopTest();
        
        Contact_Team__c ct = [
        						Select Contact__c
        						From Contact_Team__c
        						Where Contact__c = :sContact.Id
        						Limit 1
        						];
        System.assertEquals(ct.Contact__c, sContact.Id);
        
    }
    

}