src/objects/ConstantsH__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Acc_and_Contact_owner__c</fullName>
        <defaultValue>&apos;A&amp;N Media&apos;</defaultValue>
        <label>Acc and Contact owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ConstantsH</label>
</CustomObject>

src/objects/Contact_Details__c.object
<CustomObject>
    <label>Private Contact Details</label>
    <nameField>
        <label>Contact Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Private Contact Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AllContactDetailsTriggers_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AllContactDetailsTriggers_Test {
	static User u;
	
	static{
		ConstantsH__c ch = new ConstantsH__c();
		ch.Acc_and_Contact_owner__c = 'A&N Media';
		ch.Department__c = 'IT';
		insert ch;

		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

		u = new User(Alias = 'anmedia', Email = 'ANMedia@dmgmedia.com',
		EmailEncodingKey = 'UTF-8', FirstName = 'A&N', LastName = 'Media', LanguageLocaleKey = 'en_US',
		LocaleSidKey = 'en_US', ProfileId = p.Id,
		TimeZoneSidKey = 'America/Los_Angeles', UserName = 'ANMedia@dmgmedia.com');

		insert u;
	}
	
    static testMethod void afterUpdate_Test() {
        Contact_Details__c cD = new Contact_Details__c();
        insert cD;
        
        test.StartTest();
        	cD.ownerId = u.ID; 
        	update cD;
        test.stopTest();
        
    }
}