src/objects/Constants__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Creative_Snapshot_URL__c</fullName>
        <defaultValue>&apos;http://www.addynamix.co.uk/Press/Alerts/CreativeSnapshot.aspx&apos;</defaultValue>
        <description>This URL will be used to display the Advert from the Account Page.</description>
        <label>Creative Snapshot URL</label>
        <type>Url</type>
    </fields>
    <label>Constants</label>
</CustomObject>

src/objects/Nielsen_Data__c.object
<CustomObject>
    <description>This Object has been created as part of the CRM Quick Wins2 Project. It will be populated from an external system by BIU.</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>NielsenData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Advert_Size__c</fullName>
        <label>Advert Size</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <label>Brand Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreativeId__c</fullName>
        <label>CreativeId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expenditure__c</fullName>
        <label>Expenditure</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Seen__c</fullName>
        <label>First Seen</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Incidence__c</fullName>
        <label>Incidence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Seen__c</fullName>
        <label>Last Seen</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Media_Type__c</fullName>
        <label>Media Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Group__c</fullName>
        <label>Publication Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Nielsen Data</label>
    <nameField>
        <displayFormat>ND-{00000000}</displayFormat>
        <label>ND Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nielsen Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewNielsenDataWithinAccountController.cls
public with sharing class ViewNielsenDataWithinAccountController
{

	private transient Account acc;
	// public Account acc;
	
	// public transient final String creativeSnapshotURL = Constants__c.getInstance('All').Creative_Snapshot_URL__c ;
	
	public transient String creativeSnapshotURL{get; set;}
	
    private Set<Id> accountSet
    {
    	get
    	{
    		if(accountSet==null||accountSet.size()==0)
    		{
    			accountSet = new Set<Id>();
    			String currentId;
    			List<Account> al            = new List<Account>{};
        		Set<ID> currentParent      = new Set <ID>();
        		//Set<ID> accountIdSet      = new Set <ID>();
		        Integer count               = 0;
        		Integer level               = 0;
        		Boolean endOfStructure      = false;
        		currentParent.add(acc.Id);
		        //Loop though all children
       			while ( !endOfStructure )
       			{

		            if( level == 0 )
		            {
		                //Change below     
		                al = [ SELECT a.Type, a.ParentId, a.OwnerId, a.Name, a.Industry
		                		FROM Account a
		                		WHERE a.id IN : CurrentParent
		                		ORDER BY a.Name ];
		            } 
		            else 
		            {
		                //Change below      
		                al = [ SELECT a.Type, a.ParentId, a.OwnerId, a.Name, a.Industry
		                		FROM Account a
		                		WHERE a.ParentID IN : CurrentParent
		                		ORDER BY a.Name ];
		            }
		
		            if( al.size() == 0 )
		            {
		                endOfStructure = true;
		            }
		            else
		            {
		                currentParent.clear();
		                for ( Integer i = 0 ; i < al.size(); i++ )
		                {
		                    //Change below
		                    Account a = al[i];
		                    currentParent.add( a.id );
		                    accountSet.add(a.id);
		                 }
		                 level++;
		            }
		        }

				System.debug('accountSet:'+accountSet);    	
		
    		}
            return accountSet;
    	}
    	set;
    }
	
	
 	public ViewNielsenDataWithinAccountController(ApexPages.StandardController std1controller) 
 	{
        this.acc= (Account)std1Controller.getRecord();
        // System.debug('Account: '+acc);
        try
        {
        	creativeSnapshotURL = Constants__c.getInstance('All').Creative_Snapshot_URL__c;
        }
        catch(exception e)
        {
        	creativeSnapshotURL = 'http://www.addynamix.co.uk/Press/Alerts/CreativeSnapshot.aspx';
        }

 	}

	public List<Nielsen_Data__c> getAllNielsenData()
	{
		List<Nielsen_Data__c> ndList = [Select
											Publication__c,
											Publication_Group__c,
											Name,
											Media_Type__c,
											Last_Seen__c, 
											Incidence__c,
											First_Seen__c,
											Expenditure__c,
											Description__c,
											CreativeId__c,
											Category__c,
											Brand_Name__c,
											Advert_Size__c, 
											AccountID__c
											From Nielsen_Data__c
											Where AccountID__c IN :accountSet
											Order By Last_Seen__c Desc];
		return ndList;
	}

}