src/objects/CreditApprover__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ANy Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>CreditApprovers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesSectionEmail__c</fullName>
        <label>Sales Section Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesSection__c</fullName>
        <label>Sales Section</label>
        <picklist>
            <controllingField>BusinessUnit__c</controllingField>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicester SSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order, Motors, Homes &amp; Gardens, Interiors &amp; Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility, Health, Career Mail, Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overseas Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy &amp; Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems &amp; Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Barry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Hendle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Stevens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Approver</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Approvers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Query__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ANy Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Queries (Sales Manager)</relationshipLabel>
        <relationshipName>Queries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesPersonEmail__c</fullName>
        <label>Sales Person Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesSectionEmail__c</fullName>
        <label>Sales Section Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesSection__c</fullName>
        <label>Sales Section</label>
        <picklist>
            <controllingField>BusinessUnit__c</controllingField>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicester SSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order, Motors, Homes &amp; Gardens, Interiors &amp; Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility, Health, Career Mail, Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overseas Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy &amp; Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems &amp; Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Barry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Hendle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Stevens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Query</description>
        <inlineHelpText>Status of Query</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Approval Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Credit Controller Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note Created</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalQueryAmount__c</fullName>
        <label>Total Query Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Query</label>
    <nameField>
        <displayFormat>QRY{00000}</displayFormat>
        <label>Query Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QueryHandler.cls
/**
 * Trigger handler for the Query Object
 */
public without sharing class QueryHandler
	implements ITrigger
{
	private Map<Id, CreditApprover__c> m_creditApproverMap;
	private Set<Id> m_queriesToAllocate;
	private List<Query__c> m_queriesWithStatusChanged;

	public void bulkBefore()
	{
		if (Trigger.isInsert || Trigger.isUpdate)
		{
			// Populate Map of Credit Approvers
			m_creditApproverMap = new Map<Id, CreditApprover__c>();

			Set<Id> approverIds = new Set<Id>();

			for(Query__c q : (List<Query__c>)Trigger.New)
			{
				approverIds.add(q.SalesPerson__c);
			}

			m_creditApproverMap = CreditApproverGateway.mapCreditApproversByIds(approverIds);
		}
	}
	
	public void bulkAfter()
	{
		if (Trigger.isUpdate)
		{
			m_queriesToAllocate = new Set<Id>();
			m_queriesWithStatusChanged = new List<Query__c>();
		}
	}
		
	public void beforeInsert(SObject so)
	{
		populateSalesPersonFields((Query__c)so);
	}
	
	public void beforeUpdate(SObject oldSo, SObject so)
	{
		Query__c oldQuery = (Query__c)oldSo;
		Query__c query = (Query__c)so;

		// If the Sales Person has changed populate the related fields
		if (query.SalesPerson__c != oldQuery.SalesPerson__c)
		{
			populateSalesPersonFields(query);
		}
	}
	
	public void beforeDelete(SObject so)
	{
	}
	
	public void afterInsert(SObject so)
	{
	}
	
	public void afterUpdate(SObject oldSo, SObject so)
	{
		// Check if we need to Allocate the Total Query Amount down the Lines
		Query__c oldQuery = (Query__c)oldSo;
		Query__c query = (Query__c)so;

		// If the Total Query Amount was previously null or zero and has since changed
		if (query.TotalQueryAmount__c != oldQuery.TotalQueryAmount__c &&
			(oldQuery.TotalQueryAmount__c == null || oldQuery.TotalQueryAmount__c == 0))
		{
			m_queriesToAllocate.add(so.Id);
		}

		// If the Status has changed add it to the list to trigger the necessary invoice updates
		if (query.Status__c != oldQuery.Status__c)
		{
			m_queriesWithStatusChanged.add(query);
		}
	}
	
	public void afterDelete(SObject so)
	{
	}
	
	public void andFinally()
	{
		if (Trigger.isAfter)
		{
			if (Trigger.isInsert)
			{
				// if inserting, populate the Query
				QueryManagementService.populateQueriesFromSalesInvoices(Trigger.new);
			}
			else if (Trigger.isUpdate)
			{
				 if (!m_queriesToAllocate.isEmpty())
				 {
					// if update and we have queries to allocate then allocate down the lines
					QueryManagementService.allocateQueryAmount(m_queriesToAllocate);				 	
				 }

				 if (!m_queriesWithStatusChanged.isEmpty())
				 {
				 	// if we have status changes update the invoices document credit status
				 	QueryManagementService.updateInvoicesDocumentCreditStatus(m_queriesWithStatusChanged);
				 }
			}
		}
	}

	private void populateSalesPersonFields(Query__c qry)
	{
		if (qry.SalesPerson__c == null)
		{
			qry.SalesPersonEmail__c = null;
			qry.SalesSection__c = null;
			qry.SalesSectionEmail__c = null;
			qry.SalesManager__c = null;
			qry.BusinessUnit__c = null;
		}
		else
		{
			CreditApprover__c salesPerson = m_creditApproverMap.get(qry.SalesPerson__c);

			qry.SalesPersonEmail__c = salesPerson.Email__c;
			qry.SalesSection__c = salesPerson.SalesSection__c;
			qry.SalesSectionEmail__c = salesPerson.SalesSectionEmail__c;
			qry.SalesManager__c = salesPerson.SalesManager__c;
			qry.BusinessUnit__c = salesPerson.BusinessUnit__c;
		}
	}
}