src/objects/Deal_Product__c.object
<CustomObject>
    <description>Used for the price and commission information for the deal info on single and multiple price point deals.</description>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <formula>( Product_Usual_Selling_Price__c - Product_price__c )/ Product_Usual_Selling_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Pitch</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Products</relationshipLabel>
        <relationshipName>Deal_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Cap__c</fullName>
        <label>Cap</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Media_Surcharge__c</fullName>
        <label>Media Surcharge</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Supplier_Rate__c</fullName>
        <label>Supplier % Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Supplier_Unredeemed_Rate__c</fullName>
        <label>Supplier Unredeemed % Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Usual_Selling_Price__c</fullName>
        <label>Usual Selling Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Wowcher_Commission__c</fullName>
        <formula>1 -  Product_Supplier_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wowcher Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_price__c</fullName>
        <label>Deal Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Deal Product</label>
    <nameField>
        <label>Deal Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Products__c</fullName>
        <label>Deal Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <formula>(Usual_Selling_Price__c - Amount) /  Usual_Selling_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DealProductTriggerMethods.cls
public with sharing class DealProductTriggerMethods 
{
    public static void setProductNames(List<Deal_Product__c> dealProductList)
    {
            List<Id> oppIds = new List<Id>();
            
            for( Deal_Product__c deal : dealProductList ) 
            {
                oppIds.add( deal.Opportunity__c );
            }
            
            List<Opportunity> opps = [SELECT
                                        Deal_Products__c
                                        From Opportunity
                                        Where Id IN :oppIds];
            
            List<Deal_Product__c> deals = [SELECT
            								Name,
                                            Opportunity__c,
                                            Product_Cap__c,
                                            Product_price__c, 
                                            Product_media_surcharge__c,
                                            Product_description__c,
                                            Product_supplier_rate__c,
                                            Product_supplier_unredeemed_rate__c, 
                                            Product_usual_selling_price__c,
                                            Product_wowcher_commission__c, 
                                            Discount_percentage__c 
                                            From Deal_Product__c
                                            Where Opportunity__c IN :opps];
            
            Map<Id,List<Deal_Product__c>> dealsMap = new Map<Id,List<Deal_Product__c>>();
            
            for( Deal_Product__c deal : deals ) 
            {
                List<Deal_Product__c> curDeals = dealsMap.get( deal.Opportunity__c );
                if( curDeals == null ) 
                {
                    curDeals = new List<Deal_Product__c>();
                    
                    dealsMap.put(deal.Opportunity__c, curDeals);
                }
                
                curDeals.add(deal);
            }
            
            for( Opportunity opp : opps ) 
            {
                opp.Deal_Products__c = '';
                if(dealsMap.containsKey(opp.Id))
                {
                
	                List<Deal_Product__c> curDeals = dealsMap.get(opp.Id);
	                
	                for( Deal_Product__c deal : curDeals )
	                {
	                    
	                    String prodMediaSurcharge;
	                    String prodSupplierUnredeemedRate;
	                    
	                  if (deal.Product_media_surcharge__c != Null)
	                  {
	                    prodMediaSurcharge=', Media Surcharge: ' + deal.Product_media_surcharge__c;
	                  }
	                  else
	                  {
	                    prodMediaSurcharge='';
	                  }
	               
	                  
	                  if (deal.Product_supplier_unredeemed_rate__c != Null)
	                  {
	                    prodSupplierUnredeemedRate=', Supplier Unredeemed Rate: ' + deal.Product_supplier_unredeemed_rate__c +'%';
	                  }
	                  else
	                  {
	                    prodSupplierUnredeemedRate='';
	                  }                 
	                 
	                     opp.Deal_Products__c += ( 'Product Title: ' + deal.Name + ', Deal Price: £' + deal.Product_price__c + ', Usual Selling Price: £' + deal.product_usual_selling_price__c +', Discount Percentage: ' + deal.discount_percentage__c +'%'+', Deal Cap: ' + deal.Product_Cap__c +', Supplier Percentage Rate: ' + deal.Product_supplier_rate__c +'%'+'\r\n\r\n\r\n');
	                    //prodMediaSurcharge='';
	                    //prodSupplierUnredeemedRate='';
	                  
	                }
                }
            }
            
            update opps;
        
    }
}