src/objects/FinanceAccount__c.object
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Query__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ANy Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateOpened__c</fullName>
        <label>Date Opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FinanceAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Account</label>
        <referenceTo>ffps_dmg__FinanceAccount__c</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesInvoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Invoice</label>
        <referenceTo>c2g__codaInvoice__c</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesManagerEmail__c</fullName>
        <label>Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Queries (Sales Manager)</relationshipLabel>
        <relationshipName>Queries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesPersonEmail__c</fullName>
        <label>Sales Person Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>CreditApprover__c</referenceTo>
        <relationshipLabel>Queries</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesSectionEmail__c</fullName>
        <label>Sales Section Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SalesSection__c</fullName>
        <label>Sales Section</label>
        <picklist>
            <controllingField>BusinessUnit__c</controllingField>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leicester SSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Order, Motors, Homes &amp; Gardens, Interiors &amp; Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility, Health, Career Mail, Notices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overseas Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy &amp; Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems &amp; Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Barry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Hendle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Stevens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send48HrEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set by a background process to flag that a 48 Hour Email followup should be sent. This field is a trigger for an email to be sent via a workflow.</description>
        <inlineHelpText>Set by a background process to flag that a 48 Hour Email followup should be sent. This field is a trigger for an email to be sent via a workflow.</inlineHelpText>
        <label>Send 48hr Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ToBeAllocatedQueryAmount__c</fullName>
        <formula>TotalQueryAmount__c -  AllocatedQueryAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>To Be Allocated Query Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalQueryAmount__c</fullName>
        <label>Total Query Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Query</label>
    <nameField>
        <displayFormat>QRY{00000}</displayFormat>
        <label>Query Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QueryLineItem__c.object
<CustomObject>
    <fields>
        <fullName>NetValue__c</fullName>
        <formula>SalesInvoiceLineItem__r.c2g__NetValue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QueryValue__c</fullName>
        <label>Query Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <referenceTo>Query__c</referenceTo>
        <relationshipLabel>Query Line Items</relationshipLabel>
        <relationshipName>QueryLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesInvoiceLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Invoice Line Item</label>
        <referenceTo>c2g__codaInvoiceLineItem__c</referenceTo>
        <relationshipLabel>Query Line Items</relationshipLabel>
        <relationshipName>QueryLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Query Line Item</label>
    <nameField>
        <displayFormat>QLI{00000}</displayFormat>
        <label>Query Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Query Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QueryGateway.cls
/**
 * Gateway methods for the Query Object
 */
public with sharing class QueryGateway 
{
    public static Map<Id, Query__c> mapQueriesAndLinesByIds(Set<Id> queryIds) 
    {
        return new Map<Id, Query__c>([Select Id, Name, Client__c, FinanceAccount__c, SalesInvoice__c, SalesPerson__c, SalesPersonEmail__c,
                                            SalesManager__c, SalesManagerEmail__c, SalesSection__c, SalesSectionEmail__c, BusinessUnit__c,
                                            TotalQueryAmount__c, ToBeAllocatedQueryAmount__c,
                                            (Select Id, Name, QueryValue__c, NetValue__c From QueryLineItems__r Order By SalesInvoiceLineItem__r.c2g__LineNumber__c)
                                        From Query__c
                                        Where Id in :queryIds]);
    }

    public static List<Query__c> findOverdueQueries(DateTime targetDateTime)
    {
        return [Select Id, Name, DateOpened__c, Send48HrEmail__c from Query__c Where Send48HrEmail__c = false and DateOpened__c <= :targetDateTime];
    }
}