src/objects/Inactive_Pitch_Idea__c.object
<CustomObject>
    <description>Pitches - individual options given to clients</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Competitor_Title__c</fullName>
        <label>Competitor</label>
        <picklist>
            <controllingField>Reason_for_Inactive2__c</controllingField>
            <picklistValues>
                <fullName>City AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Express - Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Mirror Saturday - We Love Telly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star Saturday - Hot Tv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star Sunday (T)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star Sunday - Ok Extra/Take 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Telegraph</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Telegraph Saturday - Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evening Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Times Saturday- Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian Saturday- Listings/ Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian Saturday- Weekend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent &amp; I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent On Sunday (B/t)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent On Sunday - Review (T)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Saturday - Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Saturday - Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mids only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observer Sunday(B/bl)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observer Sunday - Observer Mag (A4)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Media - Digital</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Insertion_Date__c</fullName>
        <label>First Insertion Date Old</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Ideas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Inactive2__c</fullName>
        <label>Reason for Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Activity already booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity discussed as value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business titles only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign date moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Date moved Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn’t Use Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free/House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea Not Suited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to A&amp;N Media Brand Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mids Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed a tactical opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not core to activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed to classified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pops Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quails Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quals only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong target audience</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ServiceDate__c</fullName>
        <label>First Insertion Date</label>
        <type>Date</type>
    </fields>
    <label>Inactive Product</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>Inactive Pitch Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inactive Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>First_Insertion_Date__c</fullName>
        <label>MigFirst Insertion Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Competitor_Title__c</fullName>
        <label>Competitor</label>
        <picklist>
            <controllingField>Reason_for_Inactive2__c</controllingField>
            <picklistValues>
                <fullName>City AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Mirror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Telegraph</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evening Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent &amp; I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mids only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Media - Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Media - Magazines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Media - Outdoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Media - Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Media - TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pops only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quals only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shortlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stylist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Times</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Express - Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Mirror Saturday - We Love Telly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star Saturday - Hot Tv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star Sunday - Ok Extra/Take 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Star Sunday (T)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Insertion_Date__c</fullName>
        <label>First Insertion Date Old</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_for_Inactive2__c</fullName>
        <label>Reason for Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Activity already booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity discussed as value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business titles only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign date moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Date moved Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn’t Use Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free/House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea Not Suited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to A&amp;N Media Brand Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mids Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed a tactical opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Creative Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Solutions booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not core to activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed to classified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pops Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quails Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quals Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong target audience</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/ActivateDeactivatePitchIdeaController.cls
/*******************************************************************************************
********************************************************************************************
****																					****
****	Users are able to make inactive Pitch Idea active - the pitch is removed		****			 
****	from Inactive Pitch Ideas list and brought back as an active pitch.				****
****																					****
****	Also, users are able to deactivate Pitch Ideas. After deactivation, 			****
****	record gets created in Inactive Pitch Ideas related list and 					****
****	Pitch Idea gets removed from the Opportunity.  									****
****																					****
********************************************************************************************
*******************************************************************************************/


public class ActivateDeactivatePitchIdeaController 
{
	
	private PageReference retPage;
	public Id pitchIdeaId;
	
	public string errorMessage 			{ get; set; }
	public boolean showSelectList 		{ get; private set; }
	public boolean showLostToCompList 	{ get; private set; }
	public boolean renderPage 			{ get; private set; }
	public string inactiveReason 		{ get; set; }
	public string competitorTitle 		{ get; set; }
	
	public OpportunityLineItem oli 		{ get; set; }

	
	
	public ActivateDeactivatePitchIdeaController(ApexPages.StandardController controller) 
	{
		
		pitchIdeaId = Apexpages.currentPage().getParameters().get('id');
		system.debug('>>>>>>>>>>>>> pitchIdeaId ' + pitchIdeaId);
		
		showSelectList 		= false;
		showLostToCompList 	= false;
		renderPage			= true;

	}



	//#
	//# Activate inactive Pitch Idea
	//#
	public PageReference Activate() 
	{
		
		errorMessage = null;
		
		Inactive_Pitch_Idea__c ipi = 
				[
				select id, name, Active__c, Opportunity__c, Opportunity__r.Id, Opportunity__r.CloseDate, ServiceDate__c
				from Inactive_Pitch_Idea__c 
				where id =: pitchIdeaId
				];

		
		ipi.Active__c = true;
		
		
		// if (ipi.First_Insertion_Date__c < ipi.Opportunity__r.CloseDate) 
		if (ipi.ServiceDate__c < ipi.Opportunity__r.CloseDate) 
		{
		   	ipi.addError('First Insertion Date has to be equal or higher then Opp Close Date.');
		}
		
		
		try
		{
			update ipi;
		}
		catch(DmlException dmle)
		{
				
			if(dmle.getMessage().contains('higher then Opp Close Date')) 
					errorMessage = 'First Insertion Date has to be equal or higher then Opp Close Date.';
			else 	errorMessage = dmle.getMessage();
				
			return null;
				
		}
		catch(exception e)
		{
			errorMessage = e.getMessage();
			return null;
		}
		
		retPage = new Pagereference('/' + ipi.Opportunity__r.Id);
		retPage.setRedirect(true);
		
		
		return retPage;
		
	}
	
	
	
	//#
	//# Dectivate active Pitch Idea
	//#
	
	public PageReference Deactivate() 
	{
		
		
		oli =
				[
				select id, Active__c, OpportunityId, Reason_for_Inactive2__c, Competitor_Title__c, ServiceDate
				from OpportunityLineItem 
				where id =: pitchIdeaId
				];


		Opportunity oppty = 
				[
				select id, Name, CloseDate
				from Opportunity 
				where id =: oli.OpportunityId
				];
				

		if (inactiveReason  == null)		inactiveReason	= oli.Reason_for_Inactive2__c;
		if (competitorTitle == null) 		competitorTitle	= oli.Competitor_Title__c;
	    System.debug('inactiveReason:'+inactiveReason);
	    System.debug('competitorTitle:'+competitorTitle);
	
		if	(
			((inactiveReason == 'Lost to Competitor' && competitorTitle != null) || (inactiveReason != null && inactiveReason != 'Lost to Competitor'))
			&&
			(oli.ServiceDate >= oppty.CloseDate)
			)
		{
			System.debug('Setting inactive flag');
			oli.Active__c = false;
			
			
			try
			{ 
				
				oli.Reason_for_Inactive2__c = InactiveReason;
				oli.Competitor_Title__c = competitorTitle;
				System.debug('******** oli'+oli);
				update oli; 
				
				retPage = new Pagereference('/' + oli.OpportunityId);
				retPage.setRedirect(true);
			
				return retPage;
				
			}
			catch(Exception e)
			{
				
				System.debug('>>>>>>>>>>> EXCEPTION!!!! ' + e); 
				errorMessage = e.getMessage();
				
				return null;
			}
			
		}
		else if(oli.ServiceDate < oppty.CloseDate)
		{
			errorMessage = 'First Insertion Date has to be equal or higher then Opp Close Date.';
			renderPage = false;
			return null; 
		}
		
		
		if(oli.Reason_for_Inactive2__c == null && !showSelectList)
		{
				showSelectList = true;
				return null;
				
		}
		showSelectList = false;
		
		
		
		if(inactiveReason == 'Lost to Competitor' && oli.Competitor_Title__c == null && !showLostToCompList)
		{
		
				showLostToCompList = true;
				return null;
				
		}
		
		
		return null;
		
	}
	
	
	
	//#
	//# Get all Reason for Inactive options
	//#
	
	public List<Selectoption> getInactiveOpts()
	{
		
		List<Selectoption> opts 		= new List<Selectoption>();
		List<Schema.PicklistEntry> vals = Schema.SObjectType.OpportunityLineItem.fields.Reason_for_Inactive2__c.getPicklistValues();
		for(Schema.PicklistEntry val : vals) opts.add(new selectOption(val.getValue(), val.getLabel()));
		return opts;
		
	}
	
	
	
	//#
	//# Get all Competitor Title options
	//#
	
	public List<Selectoption> getLostToCompOpts()
	{
		
		List<Selectoption> opts 		= new List<Selectoption>();
		List<Schema.PicklistEntry> vals = Schema.SObjectType.OpportunityLineItem.fields.Competitor_Title__c.getPicklistValues();
		for(Schema.PicklistEntry val : vals) opts.add(new selectOption(val.getValue(), val.getLabel()));
		return opts;
		
	}
	
	
	
	//#
	//# Cancel and return to the Pitch Idea
	//#
	
	public PageReference cancel()
    {
   		
   		PageReference opptyPage = new PageReference('/' + oli.Id);
      	opptyPage.setRedirect(true);

      	return opptyPage;
		
    }
    
    
	//#
	//# Delete OpportunityLine which have already been archived
	//#
	@future 
	public static void deleteOpportunityLine (Set<Id> oplIdSet)
	{
		if(oplIdset.size()>0)
		{
			System.debug('oplIdset:'+oplIdset);
			List<OpportunityLineItem> oplList = new List<OpportunityLineItem>();
			for(Id opl:oplIdSet)
			{
				oplList.add(new OpportunityLineItem(Id=opl));
			}
			system.debug('oplList:'+oplList);
			delete oplList;
		}
	}

}