src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Agency account type should be Agency or Direct Advertiser and it needs to be Active.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Direct Advertiser,Billing Agency,Charity,Private Advertiser,Brand, Booking Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pitches (Agency)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Lead Ad Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Specification__c</fullName>
        <label>Color Specification</label>
        <picklist>
            <picklistValues>
                <fullName>Mono</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Booked__c</fullName>
        <label>Date Booked</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URN__c</fullName>
        <label>URN</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BookingConfirmationController.cls
public with sharing class BookingConfirmationController {
    
    public List<OpportunityLineItem> sOppLineItems {get; set;}
    public Id oppID {get; set;}
    public Boolean showPrice {get; set;}
    public Boolean lineDesc {get; set;}
    
   	public Boolean lc {get;set;}
    
    public List<OpportunityLineItem> getOppLineItems()
    {

        sOppLineItems   =   [Select Opportunity.Agency__r.name, Opportunity.Account.Name, ServiceDate, 
                                                 Brand__c, Size__c, Color_Specification__c, Region__c,
                                                 Position__c, TotalPrice, URN__c, 
                                                 Date_Booked__c,
                                                 Product_Name__c,
                                                 Opportunity.Amount,
                                                 Description
                              From OpportunityLineItem
                              Where OpportunityID = : oppID
                              Order by ServiceDate asc];       
        
        return sOppLineItems;
    }
    
    public Decimal getTotalPrice()
    {
    	return sOppLineItems.size()>0?sOppLineItems[0].Opportunity.Amount:0;
    }
    
/*    public String getLCimageurl () 
    {  
    	document doc = [  
    						Select
    							Id
    						From Document
    						Where Name = 'London Classified Footer Logo'
						];
    	string imageid = doc.id; 
    	imageid = imageid.substring(0,15);
    	System.debug('LC: '+imageid);
    	return '/servlet/servlet.FileDownload?file=' + imageid;
	}

    public String getNCimageurl () 
    {  
    	document doc = [  
    						Select
    							Id
    						From Document
    						Where Name = 'NorthCliffe Footer Logo'
						];
    	string imageid = doc.id; 
    	imageid = imageid.substring(0,15);
    	System.debug('NC: '+imageid);
    	return '/servlet/servlet.FileDownload?file=' + imageid;
	}*/
    
    @isTest   
    private static void testBookingConfirmationController()
    {
       BookingConfirmationController cBookingController    =    new BookingConfirmationController();
       cBookingController.getOppLineItems();  
       System.assert(cBookingController.getTotalPrice()>=0);     
    }

}